// Defibrillation pre-test — Set A. Diagnostic check before starting the lessons
// (not a certificate requirement — same pattern as bls-hcp/preTest/setA.js).
export const setA = {
  id: 'df-pretest-a',
  title: 'ชุด A',
  questions: [
    { id: 'df-pt-a1', question: 'จังหวะใดเป็น shockable rhythm?', choices: [{ id: 'a', text: 'Asystole' }, { id: 'b', text: 'VF' }, { id: 'c', text: 'PEA' }, { id: 'd', text: 'Sinus rhythm' }], correctId: 'b', explanation: 'VF และ pulseless VT เป็น shockable rhythms' },
    { id: 'df-pt-a2', question: 'PEA คือจังหวะแบบใด?', choices: [{ id: 'a', text: 'มีไฟฟ้าแต่คลำชีพจรไม่ได้' }, { id: 'b', text: 'ไม่มีไฟฟ้าเลย' }, { id: 'c', text: 'หัวใจเต้นปกติ' }, { id: 'd', text: 'Shockable เสมอ' }], correctId: 'a', explanation: 'PEA มีกิจกรรมไฟฟ้าบนจอแต่ไม่มีการบีบตัวที่มีประสิทธิภาพ' },
    { id: 'df-pt-a3', question: 'เครื่อง biphasic ต่างจาก monophasic อย่างไร?', choices: [{ id: 'a', text: 'มีประสิทธิภาพสูงกว่าที่พลังงานต่ำกว่า' }, { id: 'b', text: 'ไม่ต้องใช้ pads' }, { id: 'c', text: 'ใช้ได้เฉพาะเด็ก' }, { id: 'd', text: 'ไม่มีความแตกต่าง' }], correctId: 'a', explanation: 'Biphasic ใช้กระแสไฟสองทิศทาง มีประสิทธิภาพสูงกว่าที่พลังงานต่ำกว่า' },
    { id: 'df-pt-a4', question: 'หลัง AED shock ควรทำอะไรทันที?', choices: [{ id: 'a', text: 'ตรวจชีพจรก่อน' }, { id: 'b', text: 'กดหน้าอกต่อทันที' }, { id: 'c', text: 'ปิดเครื่อง' }, { id: 'd', text: 'รอ 1 นาที' }], correctId: 'b', explanation: 'กลับมากดหน้าอกทันทีโดยไม่ต้องตรวจชีพจรก่อน' },
    { id: 'df-pt-a5', question: 'ตำแหน่ง pads มาตรฐาน anterior-lateral อยู่ที่ใด?', choices: [{ id: 'a', text: 'ใต้ไหปลาร้าขวา + ชายโครงซ้ายแนวรักแร้' }, { id: 'b', text: 'กลางหน้าอกทั้งสองแผ่น' }, { id: 'c', text: 'หลังทั้งสองแผ่น' }, { id: 'd', text: 'ท้องทั้งสองแผ่น' }], correctId: 'a', explanation: 'ตำแหน่งมาตรฐานที่นิยมที่สุด' },
    { id: 'df-pt-a6', question: 'ผู้ป่วยมี pacemaker ควรวาง pad อย่างไร?', choices: [{ id: 'a', text: 'วางทับได้เลย' }, { id: 'b', text: 'เว้นระยะห่างจากตัวเครื่อง' }, { id: 'c', text: 'ห้าม shock เด็ดขาด' }, { id: 'd', text: 'ถอด pacemaker ก่อน' }], correctId: 'b', explanation: 'เว้นระยะห่างจากตัวเครื่องอย่างน้อยราว 8 ซม.' },
    { id: 'df-pt-a7', question: 'Peri-shock pause คืออะไร?', choices: [{ id: 'a', text: 'ช่วงเวลาหยุดกดหน้าอกก่อน-หลัง shock' }, { id: 'b', text: 'เวลาที่เครื่องชาร์จแบตเตอรี่' }, { id: 'c', text: 'เวลาเตรียมยา' }, { id: 'd', text: 'ไม่มีความหมาย' }], correctId: 'a', explanation: 'ยิ่งนานยิ่งลดโอกาสสำเร็จของ shock' },
    { id: 'df-pt-a8', question: 'CCF เป้าหมายตามแนวทาง 2025 คือ?', choices: [{ id: 'a', text: '> 40%' }, { id: 'b', text: '> 80%' }, { id: 'c', text: '100%' }, { id: 'd', text: '> 20%' }], correctId: 'b', explanation: 'CCF > 80% เป็น quality benchmark' },
    { id: 'df-pt-a9', question: 'Synchronized cardioversion sync กับส่วนใดของ EKG?', choices: [{ id: 'a', text: 'T wave' }, { id: 'b', text: 'R wave' }, { id: 'c', text: 'P wave' }, { id: 'd', text: 'U wave' }], correctId: 'b', explanation: 'Sync กับ R wave เพื่อหลีกเลี่ยงปล่อยไฟตรง T wave' },
    { id: 'df-pt-a10', question: 'Synchronized cardioversion ใช้กับผู้ป่วยแบบใด?', choices: [{ id: 'a', text: 'ไม่มีชีพจร' }, { id: 'b', text: 'มีชีพจรแต่ไม่คงที่ (tachyarrhythmia)' }, { id: 'c', text: 'หัวใจปกติ' }, { id: 'd', text: 'Bradycardia' }], correctId: 'b', explanation: 'ใช้กับผู้ป่วยมีชีพจรที่เต้นเร็วผิดปกติและไม่คงที่' },
    { id: 'df-pt-a11', question: 'ทำไมต้องเปิด SYNC ใหม่ทุกครั้งหลัง shock?', choices: [{ id: 'a', text: 'เครื่องปิดโหมด sync อัตโนมัติหลัง shock' }, { id: 'b', text: 'ไม่จำเป็น' }, { id: 'c', text: 'เพื่อประหยัดแบตเตอรี่' }, { id: 'd', text: 'เพื่อเปลี่ยนพลังงาน' }], correctId: 'a', explanation: 'เครื่องส่วนใหญ่ปิดโหมด sync อัตโนมัติหลัง shock แต่ละครั้ง' },
    { id: 'df-pt-a12', question: 'Transcutaneous pacing ใช้ในผู้ป่วยกลุ่มใด?', choices: [{ id: 'a', text: 'Tachycardia ไม่คงที่' }, { id: 'b', text: 'Bradycardia ไม่คงที่ที่ยาไม่ได้ผล' }, { id: 'c', text: 'VF' }, { id: 'd', text: 'หัวใจปกติ' }], correctId: 'b', explanation: 'ใช้กับ bradycardia ที่ไม่คงที่และไม่ตอบสนองต่อยา' },
    { id: 'df-pt-a13', question: 'Mechanical capture ยืนยันได้อย่างไร?', choices: [{ id: 'a', text: 'ดู pacing spike บนจอ' }, { id: 'b', text: 'คลำชีพจรตรงกับอัตราที่ตั้งไว้' }, { id: 'c', text: 'วัดอุณหภูมิ' }, { id: 'd', text: 'ฟังเสียงหัวใจ' }], correctId: 'b', explanation: 'ต้องคลำชีพจรยืนยันว่าหัวใจบีบตัวจริง' },
    { id: 'df-pt-a14', question: 'ระหว่าง AED วิเคราะห์จังหวะ ทุกคนควรทำอย่างไร?', choices: [{ id: 'a', text: 'กดหน้าอกต่อ' }, { id: 'b', text: 'ห่างตัวผู้ป่วย ไม่แตะต้อง' }, { id: 'c', text: 'จับชีพจร' }, { id: 'd', text: 'เขย่าตัว' }], correctId: 'b', explanation: 'การสัมผัสรบกวนการวิเคราะห์' },
    { id: 'df-pt-a15', question: 'เครื่อง monophasic ใช้พลังงานเท่าไรในการ defibrillate ผู้ใหญ่?', choices: [{ id: 'a', text: '50 J' }, { id: 'b', text: '360 J' }, { id: 'c', text: '10 J' }, { id: 'd', text: '1000 J' }], correctId: 'b', explanation: 'Monophasic ใช้ 360 J ทุกครั้ง' },
  ],
};
