// Defibrillation pre-test — Set A. Diagnostic check before starting the lessons
// (not a certificate requirement — same pattern as bls-hcp/preTest/setA.js).
// คำเฉลยเขียนเชิงสอน: ทำไมถูก + กลไก + ทำไมตัวเลือกที่ล่อผิด
export const setA = {
  id: 'df-pretest-a',
  title: 'ชุด A',
  questions: [
    { id: 'df-pt-a1', question: 'จังหวะใดเป็น shockable rhythm?', choices: [{ id: 'a', text: 'Asystole' }, { id: 'b', text: 'VF' }, { id: 'c', text: 'PEA' }, { id: 'd', text: 'Sinus rhythm' }], correctId: 'b', explanation: 'VF (และ pulseless VT) เป็นปัญหา "ไฟฟ้าวุ่นวาย" ที่ defibrillation รีเซ็ตได้ตรงจุด — Asystole ไม่มีไฟฟ้าให้รีเซ็ต, PEA ปัญหาอยู่ที่สาเหตุอื่น (H\'s & T\'s) ไม่ใช่ไฟฟ้าวุ่นวาย, Sinus rhythm เป็นจังหวะปกติ ทั้งสามจึงไม่ช็อก' },
    { id: 'df-pt-a2', question: 'PEA คือจังหวะแบบใด?', choices: [{ id: 'a', text: 'มีไฟฟ้าแต่คลำชีพจรไม่ได้' }, { id: 'b', text: 'ไม่มีไฟฟ้าเลย' }, { id: 'c', text: 'หัวใจเต้นปกติ' }, { id: 'd', text: 'Shockable เสมอ' }], correctId: 'a', explanation: 'PEA = มีกิจกรรมไฟฟ้าบนจอแต่หัวใจบีบตัวไม่มีประสิทธิภาพพอจนคลำชีพจรไม่ได้ — "ไม่มีไฟฟ้าเลย" คือ asystole; PEA ไม่ shock (ปัญหาไม่ใช่ไฟฟ้า) รักษาด้วย CPR + หา/แก้ H\'s & T\'s' },
    { id: 'df-pt-a3', question: 'เครื่อง biphasic ต่างจาก monophasic อย่างไร?', choices: [{ id: 'a', text: 'มีประสิทธิภาพสูงกว่าที่พลังงานต่ำกว่า' }, { id: 'b', text: 'ไม่ต้องใช้ pads' }, { id: 'c', text: 'ใช้ได้เฉพาะเด็ก' }, { id: 'd', text: 'ไม่มีความแตกต่าง' }], correctId: 'a', explanation: 'Biphasic ปล่อยกระแสสองทิศสลับกันในช็อกครั้งเดียว depolarize มวลกล้ามเนื้อได้ทั่วถึงกว่าที่พลังงานต่ำกว่า (มัก 120–200 J เทียบ monophasic 360 J) และหลายรุ่นชดเชย impedance อัตโนมัติ — ยังต้องใช้ pads และใช้ได้ทุกวัย' },
    { id: 'df-pt-a4', question: 'หลัง AED shock ควรทำอะไรทันที?', choices: [{ id: 'a', text: 'ตรวจชีพจรก่อน' }, { id: 'b', text: 'กดหน้าอกต่อทันที' }, { id: 'c', text: 'ปิดเครื่อง' }, { id: 'd', text: 'รอ 1 นาที' }], correctId: 'b', explanation: 'แม้ช็อกหยุด VF สำเร็จ หัวใจมักยังบีบอ่อนช่วงแรก (myocardial stunning) การหยุดคลำชีพจรทันทีเป็นการหยุดกดที่ไม่จำเป็น ทำให้ CPP ที่เพิ่งสร้างตกอีก — ให้ CPR ต่อทันที 2 นาทีแล้วค่อยประเมิน rhythm/ชีพจร' },
    { id: 'df-pt-a5', question: 'ตำแหน่ง pads มาตรฐาน anterior-lateral อยู่ที่ใด?', choices: [{ id: 'a', text: 'ใต้ไหปลาร้าขวา + ชายโครงซ้ายแนวรักแร้' }, { id: 'b', text: 'กลางหน้าอกทั้งสองแผ่น' }, { id: 'c', text: 'หลังทั้งสองแผ่น' }, { id: 'd', text: 'ท้องทั้งสองแผ่น' }], correctId: 'a', explanation: 'วางใต้ไหปลาร้าขวา + ชายโครงซ้ายแนวรักแร้กลาง เพื่อให้กระแส "หนีบหัวใจไว้ระหว่าง pad" ไหลผ่าน myocardium มากที่สุด — วางสองแผ่นชิดกัน/กลางหน้าอก กระแสจะลัดตามผิวไม่ผ่านหัวใจ' },
    { id: 'df-pt-a6', question: 'ผู้ป่วยมี pacemaker ควรวาง pad อย่างไร?', choices: [{ id: 'a', text: 'วางทับได้เลย' }, { id: 'b', text: 'เว้นระยะห่างจากตัวเครื่อง' }, { id: 'c', text: 'ห้าม shock เด็ดขาด' }, { id: 'd', text: 'ถอด pacemaker ก่อน' }], correctId: 'b', explanation: 'วาง pad ห่างตัวเครื่อง pacemaker/ICD (≥ ~2.5 ซม.) ไม่วางทับ เพราะการวางทับทำให้กระแสถูก shunt เข้าเครื่อง (ช็อกหัวใจได้น้อยลง + อาจทำเครื่องเสียหาย) — ยังต้อง shock ได้ตามปกติ ไม่ต้องถอดเครื่อง (ทำไม่ได้เฉียบพลันอยู่แล้ว)' },
    { id: 'df-pt-a7', question: 'Peri-shock pause คืออะไร?', choices: [{ id: 'a', text: 'ช่วงเวลาหยุดกดหน้าอกก่อน-หลัง shock' }, { id: 'b', text: 'เวลาที่เครื่องชาร์จแบตเตอรี่' }, { id: 'c', text: 'เวลาเตรียมยา' }, { id: 'd', text: 'ไม่มีความหมาย' }], correctId: 'a', explanation: 'Peri-shock pause = ช่วงหยุดกดรอบ ๆ การช็อก — ยิ่งยาว coronary perfusion pressure ยิ่งตก (และต้องกดหลายครั้งกว่าจะไต่กลับ) ลดโอกาสช็อกสำเร็จและการรอดชีวิต จึงต้องทำให้สั้นที่สุด (เช่น ชาร์จระหว่างยังกดอยู่)' },
    { id: 'df-pt-a8', question: 'CCF เป้าหมายตามแนวทาง 2025 คือ?', choices: [{ id: 'a', text: '> 40%' }, { id: 'b', text: '> 80%' }, { id: 'c', text: '100%' }, { id: 'd', text: '> 20%' }], correctId: 'b', explanation: 'Chest Compression Fraction (สัดส่วนเวลาที่มือกดจริงต่อเวลาทั้งหมด) เป้าหมาย > 80% — สูงพอจะคงการไหลเวียน แต่ 100% เป็นไปไม่ได้จริงเพราะยังต้องมีช่วง shock/วิเคราะห์จังหวะ; วิธีเพิ่มที่ได้ผลสุดคือลด pause ทุกชนิด' },
    { id: 'df-pt-a9', question: 'Synchronized cardioversion sync กับส่วนใดของ EKG?', choices: [{ id: 'a', text: 'T wave' }, { id: 'b', text: 'R wave' }, { id: 'c', text: 'P wave' }, { id: 'd', text: 'U wave' }], correctId: 'b', explanation: 'เครื่อง sync ปล่อยไฟให้ตรง R wave โดยเจตนา เพื่อ "หลบ" T wave (ช่วง repolarization ที่เปราะบาง) — ถ้าไฟตกตรง T wave (R-on-T) อาจเหนี่ยวนำ VF; จึง sync กับ R ไม่ใช่ T/P/U' },
    { id: 'df-pt-a10', question: 'Synchronized cardioversion ใช้กับผู้ป่วยแบบใด?', choices: [{ id: 'a', text: 'ไม่มีชีพจร' }, { id: 'b', text: 'มีชีพจรแต่ไม่คงที่ (tachyarrhythmia)' }, { id: 'c', text: 'หัวใจปกติ' }, { id: 'd', text: 'Bradycardia' }], correctId: 'b', explanation: 'Cardioversion ใช้กับผู้ที่ "ยังมีชีพจร" แต่เต้นเร็วผิดปกติและไม่คงที่ (unstable tachyarrhythmia) — ผู้ไม่มีชีพจร (VF/pVT) ใช้ defibrillation (ไม่ sync), bradycardia ใช้ pacing/atropine' },
    { id: 'df-pt-a11', question: 'ทำไมต้องเปิด SYNC ใหม่ทุกครั้งหลัง shock?', choices: [{ id: 'a', text: 'เครื่องปิดโหมด sync อัตโนมัติหลัง shock' }, { id: 'b', text: 'ไม่จำเป็น' }, { id: 'c', text: 'เพื่อประหยัดแบตเตอรี่' }, { id: 'd', text: 'เพื่อเปลี่ยนพลังงาน' }], correctId: 'a', explanation: 'เครื่องส่วนใหญ่กลับไปโหมด defib (unsync) อัตโนมัติหลังปล่อยไฟ ถ้าลืมเปิด SYNC ใหม่ก่อน cardiovert ซ้ำ ไฟอาจตกตรง T wave → R-on-T → เหนี่ยวนำ VF ในผู้ป่วยที่ยังมีชีพจร' },
    { id: 'df-pt-a12', question: 'Transcutaneous pacing ใช้ในผู้ป่วยกลุ่มใด?', choices: [{ id: 'a', text: 'Tachycardia ไม่คงที่' }, { id: 'b', text: 'Bradycardia ไม่คงที่ที่ยาไม่ได้ผล' }, { id: 'c', text: 'VF' }, { id: 'd', text: 'หัวใจปกติ' }], correctId: 'b', explanation: 'Pacing กระตุ้นให้หัวใจเต้นในอัตราที่ตั้ง จึงใช้กับ bradycardia ที่ไม่คงที่และไม่ตอบสนองต่อยา (เช่น atropine) — tachycardia ไม่คงที่ใช้ cardioversion, VF ใช้ defibrillation' },
    { id: 'df-pt-a13', question: 'Mechanical capture ยืนยันได้อย่างไร?', choices: [{ id: 'a', text: 'ดู pacing spike บนจอ' }, { id: 'b', text: 'คลำชีพจรตรงกับอัตราที่ตั้งไว้' }, { id: 'c', text: 'วัดอุณหภูมิ' }, { id: 'd', text: 'ฟังเสียงหัวใจ' }], correctId: 'b', explanation: 'Pacing spike + QRS บนจอเป็นเพียง electrical capture — ต้องคลำชีพจร (เช่น femoral) ให้ตรงอัตราที่ตั้ง จึงยืนยันว่าไฟฟ้าที่ capture "แปลงเป็นการบีบตัว/ไหลเวียนเลือดจริง" (mechanical capture) ไม่ใช่แค่สัญญาณบนจอ' },
    { id: 'df-pt-a14', question: 'ระหว่าง AED วิเคราะห์จังหวะ ทุกคนควรทำอย่างไร?', choices: [{ id: 'a', text: 'กดหน้าอกต่อ' }, { id: 'b', text: 'ห่างตัวผู้ป่วย ไม่แตะต้อง' }, { id: 'c', text: 'จับชีพจร' }, { id: 'd', text: 'เขย่าตัว' }], correctId: 'b', explanation: 'การสัมผัส/กดหน้าอกทำให้เกิดการเคลื่อนไหว (artifact) รบกวนการอ่านจังหวะของ AED อาจวิเคราะห์ผิด — ต้องห่างตัวไม่แตะต้องระหว่าง analyzing แล้วกลับมากดทันทีที่เครื่องเสร็จ (บริหาร pause ให้สั้น)' },
    { id: 'df-pt-a15', question: 'เครื่อง monophasic ใช้พลังงานเท่าไรในการ defibrillate ผู้ใหญ่?', choices: [{ id: 'a', text: '50 J' }, { id: 'b', text: '360 J' }, { id: 'c', text: '10 J' }, { id: 'd', text: '1000 J' }], correctId: 'b', explanation: 'Monophasic ปล่อยกระแสทิศเดียว ต้องใช้พลังงานสูงคงที่ 360 J เพื่อให้กระแสมากพอ depolarize มวลกล้ามเนื้อ — เทียบ biphasic ที่ได้ผลที่พลังงานต่ำกว่า (120–200 J); 10–50 J น้อยเกินสำหรับ defibrillation ผู้ใหญ่' },
    { id: 'df-pt-a16', question: 'ถ้า VF ยังไม่หายหลัง shock ครั้งแรกด้วย biphasic ควรปรับพลังงานอย่างไรในครั้งถัดไป?', choices: [{ id: 'a', text: 'ใช้ค่าเดิมหรือเพิ่มขึ้น (จนถึงค่าสูงสุดของเครื่อง)' }, { id: 'b', text: 'ลดพลังงานลงครึ่งหนึ่ง' }, { id: 'c', text: 'ใช้ค่าเดิมเสมอ ห้ามเปลี่ยน' }, { id: 'd', text: 'หยุด shock' }], correctId: 'a', explanation: 'เมื่อ shock แรกไม่สำเร็จ แนวทางแนะนำให้ใช้พลังงานเท่าเดิมหรือ "เพิ่มขึ้น" (escalating) ในครั้งถัด ๆ ไปจนถึงค่าสูงสุดของเครื่อง เพื่อเพิ่มโอกาส depolarize มวลกล้ามเนื้อ — การลดพลังงานลดโอกาสสำเร็จ และห้ามหยุด shock ตราบใดยังเป็น VF/pVT' },
    { id: 'df-pt-a17', question: 'พลังงาน defibrillation ครั้งแรกในเด็กคือเท่าไร?', choices: [{ id: 'a', text: '~2 J/kg' }, { id: 'b', text: '~10 J/kg' }, { id: 'c', text: '360 J เท่าผู้ใหญ่' }, { id: 'd', text: '~0.5 J/kg' }], correctId: 'a', explanation: 'เด็กใช้พลังงานตามน้ำหนัก: ครั้งแรก ~2 J/kg แล้วเพิ่มเป็น ~4 J/kg ในครั้งถัด ๆ ไป (อาจถึง ~10 J/kg แต่ไม่เกินขนาดผู้ใหญ่) — ใช้ 360 J คงที่แบบผู้ใหญ่มากเกินไปสำหรับเด็ก และ 0.5 J/kg น้อยเกิน' },
    { id: 'df-pt-a18', question: 'จอแสดงเส้นเกือบราบเรียบ สงสัยระหว่าง fine VF กับ asystole ควรทำอย่างไร?', choices: [{ id: 'a', text: 'ตรวจ lead/gain และดูหลาย lead ก่อนตัดสิน' }, { id: 'b', text: 'ช็อกทันทีเสมอ' }, { id: 'c', text: 'สรุปว่าเป็น asystole เสมอ' }, { id: 'd', text: 'ปิดเครื่อง' }], correctId: 'a', explanation: 'Fine VF (คลื่นเล็ก) อาจดูคล้าย asystole ได้ ถ้าตัดสินผิดเป็น asystole จะพลาดโอกาส shock — ตรวจว่า lead ต่อครบ เพิ่ม gain และดูหลาย lead ก่อน; แต่ไม่ "ช็อกทุกเส้นราบ" เพราะ asystole จริงไม่ควร shock ต้องยืนยันก่อน' },
    { id: 'df-pt-a19', question: 'ก่อนกดปุ่ม shock ต้องทำสิ่งใดเพื่อความปลอดภัย?', choices: [{ id: 'a', text: 'ตะโกน "ฉันพ้น คุณพ้น ออกซิเจนพ้น" และมองรอบให้ทุกคนห่างตัวผู้ป่วย' }, { id: 'b', text: 'ไม่ต้องเตือนใคร' }, { id: 'c', text: 'ให้ทุกคนช่วยจับผู้ป่วยไว้' }, { id: 'd', text: 'เปิดออกซิเจนจ่อหน้าอก' }], correctId: 'a', explanation: 'ต้องประกาศเคลียร์และตรวจด้วยตาว่าไม่มีใครสัมผัสผู้ป่วย/เตียง และย้ายแหล่งออกซิเจนที่ไหลอิสระออกห่าง เพราะกระแสไฟอาจช็อตผู้สัมผัส และประกายไฟใกล้ออกซิเจนเสี่ยงไฟลุก — การให้คนจับ/จ่อออกซิเจนอันตรายมาก' },
    { id: 'df-pt-a20', question: 'ถ้า VF ดื้อต่อการช็อกหลายครั้งในตำแหน่ง anterior-lateral อาจลองทำอะไรกับ pad?', choices: [{ id: 'a', text: 'เปลี่ยนเป็นตำแหน่ง anterior-posterior' }, { id: 'b', text: 'ถอด pad ออกเลย' }, { id: 'c', text: 'วาง pad สองแผ่นชิดกัน' }, { id: 'd', text: 'ไม่มีอะไรทำได้' }], correctId: 'a', explanation: 'สำหรับ VF ที่ดื้อ การเปลี่ยนแนวกระแส (เช่นเปลี่ยนไป anterior-posterior) อาจทำให้กระแสผ่าน myocardium ในแกนต่างออกไปและ defibrillate สำเร็จ — ควบคู่กับการปรับคุณภาพ CPR และให้ antiarrhythmic; การวาง pad ชิดกันทำให้กระแสลัดไม่ผ่านหัวใจ' },
  ],
};
