// Defibrillation post-test — Set B. Certificate requirement (pass ≥ 80%).
// ชุดสำรองสุ่มสลับกับ Set A · คำเฉลยเชิงสอน · paraphrase เชิงหลักการ · ต้องผ่าน medical review
export const setB = {
  id: 'df-posttest-b',
  title: 'ชุด B',
  questions: [
    { id: 'df-post-b1', question: 'ข้อใดคือความจริงเกี่ยวกับ shockable rhythm?', choices: [{ id: 'a', text: 'VF และ pulseless VT เท่านั้นที่เป็น shockable' }, { id: 'b', text: 'PEA เป็น shockable' }, { id: 'c', text: 'Asystole เป็น shockable' }, { id: 'd', text: 'ทุกจังหวะ shock ได้' }], correctId: 'a', explanation: 'มีเพียง VF และ pVT ที่เป็น "ไฟฟ้าวุ่นวายที่รีเซ็ตได้" จึงช็อก — PEA/asystole ปัญหาไม่ใช่ไฟฟ้าวุ่นวาย ช็อกไม่ช่วยและเสียเวลา รักษาด้วย CPR + หา/แก้สาเหตุ' },
    { id: 'df-post-b2', question: 'EtCO₂ ระหว่าง CPR มีประโยชน์อย่างไรในบริบท defibrillation?', choices: [{ id: 'a', text: 'สะท้อนคุณภาพการกดหน้าอกและช่วยจับ ROSC' }, { id: 'b', text: 'บอกชนิดของ pad' }, { id: 'c', text: 'บอกพลังงานที่ควรใช้' }, { id: 'd', text: 'ไม่มีประโยชน์' }], correctId: 'a', explanation: 'EtCO₂ ต่ำมากบ่งการกดหน้าอกด้อยคุณภาพ (ควรปรับ) และการพุ่งขึ้นฉับพลันบ่ง ROSC — ช่วยทีมประเมินระหว่างรอบ CPR/ช็อก แต่ไม่ได้บอกชนิด pad หรือพลังงาน' },
    { id: 'df-post-b3', question: 'VF ยังคงอยู่หลังช็อกครั้งแรก (biphasic) ควรทำอย่างไรกับพลังงานครั้งถัดไป?', choices: [{ id: 'a', text: 'ใช้ค่าเดิมหรือเพิ่มขึ้น (escalating) จนถึงค่าสูงสุดของเครื่อง' }, { id: 'b', text: 'ลดลงครึ่งหนึ่ง' }, { id: 'c', text: 'หยุดช็อก' }, { id: 'd', text: 'สลับไป monophasic' }], correctId: 'a', explanation: 'แนวทางแนะนำใช้พลังงานเท่าเดิมหรือเพิ่มขึ้นในครั้งถัด ๆ ไปเพื่อเพิ่มโอกาส depolarize มวลกล้ามเนื้อ — การลดพลังงานลดโอกาสสำเร็จ และห้ามหยุดช็อกตราบยังเป็น VF/pVT' },
    { id: 'df-post-b4', question: 'สำหรับ VF ที่ดื้อต่อการช็อกซ้ำหลายครั้ง อาจพิจารณาอะไรร่วมด้วย?', choices: [{ id: 'a', text: 'ปรับคุณภาพ CPR, ให้ antiarrhythmic และลองเปลี่ยนแนว pad (เช่น anterior-posterior)' }, { id: 'b', text: 'หยุด CPR' }, { id: 'c', text: 'ถอด pad ออก' }, { id: 'd', text: 'ลดพลังงาน' }], correctId: 'a', explanation: 'VF ดื้อควรทบทวนคุณภาพ CPR, ให้ยา antiarrhythmic (เช่น amiodarone/lidocaine) และอาจเปลี่ยนแนวกระแสด้วยตำแหน่ง pad อื่นเพื่อให้ผ่าน myocardium ในแกนต่างออกไป — ไม่ใช่หยุด CPR/ลดพลังงาน' },
    { id: 'df-post-b5', question: 'บทบาทหลักของ epinephrine ระหว่าง cardiac arrest คืออะไร?', choices: [{ id: 'a', text: 'เป็น vasopressor เพิ่ม coronary/cerebral perfusion ระหว่าง CPR' }, { id: 'b', text: 'ละลายลิ่มเลือด' }, { id: 'c', text: 'ลดไข้' }, { id: 'd', text: 'ทำให้หลับ' }], correctId: 'a', explanation: 'Epinephrine กระตุ้น α₁ ให้หลอดเลือดหดตัว เพิ่มแรงดันเลือดไปเลี้ยงหัวใจ/สมองระหว่าง CPR ออกฤทธิ์สั้นจึงให้ซ้ำเป็นระยะ — ขนาด/จังหวะยึดแนวทาง+คำสั่งแพทย์ (เนื้อหานี้สอนหลักการ)' },
    { id: 'df-post-b6', question: 'ทำไม CCF > 80% จึงสำคัญ?', choices: [{ id: 'a', text: 'ยิ่งมือกดจริงมาก ยิ่งคงการไหลเวียนไปเลี้ยงหัวใจ/สมอง สัมพันธ์กับ ROSC/รอดชีวิตดีขึ้น' }, { id: 'b', text: 'เพื่อประหยัดเวลา' }, { id: 'c', text: 'เพื่อลดพลังงานช็อก' }, { id: 'd', text: 'ไม่มีผลจริง' }], correctId: 'a', explanation: 'Chest Compression Fraction คือสัดส่วนเวลาที่มือกดจริงต่อเวลารวม เป้าหมาย > 80% เพราะการหยุดกดทำให้ CPP ตกเร็ว — วิธีเพิ่มที่ได้ผลสุดคือลด peri-shock pause และการหยุดกดทุกชนิด' },
    { id: 'df-post-b7', question: 'ระหว่าง AED กำลังวิเคราะห์จังหวะ ทีมควรทำอย่างไร?', choices: [{ id: 'a', text: 'ห่างตัวผู้ป่วย ไม่แตะต้อง' }, { id: 'b', text: 'กดหน้าอกต่อเพื่อไม่ให้ CPR ขาด' }, { id: 'c', text: 'ช่วยจับผู้ป่วยไว้' }, { id: 'd', text: 'เขย่าเรียกผู้ป่วย' }], correctId: 'a', explanation: 'การสัมผัส/เคลื่อนไหวสร้าง artifact รบกวนการวิเคราะห์ อาจทำให้เครื่องตัดสินจังหวะผิด — ต้องห่างตัวช่วงวิเคราะห์ แล้วกลับมากดทันทีที่เสร็จ (บริหาร pause ให้สั้น)' },
    { id: 'df-post-b8', question: 'ตำแหน่ง anterior-lateral วาง pad อย่างไร?', choices: [{ id: 'a', text: 'ใต้ไหปลาร้าขวา + ชายโครงซ้ายแนวรักแร้กลาง' }, { id: 'b', text: 'สองแผ่นกลางอก' }, { id: 'c', text: 'สองแผ่นกลางหลัง' }, { id: 'd', text: 'บนไหล่ทั้งสองข้าง' }], correctId: 'a', explanation: 'เป้าหมายคือให้กระแส "หนีบหัวใจไว้ระหว่าง pad" ไหลผ่าน myocardium มากสุด — วางใต้ไหปลาร้าขวา + ชายโครงซ้ายแนวรักแร้; วางชิดกัน/กลางอกกระแสจะลัดตามผิว' },
    { id: 'df-post-b9', question: 'pad สองแผ่นวางชิดกันเกินไปจะเกิดอะไร?', choices: [{ id: 'a', text: 'กระแสลัดตามผิวหนัง (arcing) ไม่ผ่านหัวใจ ช็อกไม่ได้ผล' }, { id: 'b', text: 'ช็อกได้ผลดีขึ้น' }, { id: 'c', text: 'ประหยัดพลังงาน' }, { id: 'd', text: 'ไม่มีผล' }], correctId: 'a', explanation: 'ถ้า pad ชิด/แตะกัน กระแสจะวิ่งลัดตามผิวระหว่างแผ่น (arcing) แทนที่จะผ่านหัวใจ ทำให้ defibrillate ไม่สำเร็จ — ต้องเว้นระยะให้กระแสถูกบังคับผ่าน myocardium' },
    { id: 'df-post-b10', question: 'พลังงาน defibrillation ครั้งแรกในเด็กโดยหลักการคือ?', choices: [{ id: 'a', text: 'ตามน้ำหนักตัว ~2 J/kg แล้วเพิ่มในครั้งถัดไป' }, { id: 'b', text: '360 J คงที่เท่าผู้ใหญ่' }, { id: 'c', text: '1000 J' }, { id: 'd', text: '~0.2 J/kg' }], correctId: 'a', explanation: 'เด็กคิดพลังงานตามน้ำหนัก: ครั้งแรก ~2 J/kg แล้วเพิ่ม ~4 J/kg ในครั้งถัดไป (อาจถึง ~10 J/kg แต่ไม่เกินขนาดผู้ใหญ่) — ค่าคงที่ 360 J สูงเกินสำหรับเด็ก และ 0.2 J/kg น้อยเกิน' },
    { id: 'df-post-b11', question: 'ทำไมต้องเปิดโหมด SYNC ใหม่ก่อน cardioversion ซ้ำแต่ละครั้ง?', choices: [{ id: 'a', text: 'เครื่องมักกลับไปโหมด defib (unsync) อัตโนมัติหลังปล่อยไฟ' }, { id: 'b', text: 'เพื่อประหยัดแบตเตอรี่' }, { id: 'c', text: 'เพื่อเพิ่มพลังงาน' }, { id: 'd', text: 'ไม่จำเป็น' }], correctId: 'a', explanation: 'เครื่องส่วนใหญ่ปิดโหมด sync อัตโนมัติหลัง shock ถ้าลืมเปิดใหม่ก่อน cardiovert ซ้ำ ไฟอาจตกตรง T wave (R-on-T) เหนี่ยวนำ VF ในผู้ป่วยที่ยังมีชีพจร' },
    { id: 'df-post-b12', question: 'Synchronized cardioversion ใช้กับข้อใด?', choices: [{ id: 'a', text: 'Unstable tachyarrhythmia ที่ยังมีชีพจร (เช่น unstable SVT/AF/VT มีชีพจร)' }, { id: 'b', text: 'VF' }, { id: 'c', text: 'Asystole' }, { id: 'd', text: 'PEA' }], correctId: 'a', explanation: 'Cardioversion ใช้กับผู้ที่ "ยังมีชีพจร" แต่เต้นเร็วผิดจังหวะและไม่คงที่ — ผู้ไม่มีชีพจร (VF/pVT/PEA/asystole) ไม่ใช้ cardioversion (VF/pVT ใช้ defib, PEA/asystole ใช้ CPR+หาสาเหตุ)' },
    { id: 'df-post-b13', question: 'ยากลุ่ม antiarrhythmic (เช่น amiodarone/lidocaine) ใช้เมื่อใดใน arrest?', choices: [{ id: 'a', text: 'VF/pVT ที่ดื้อต่อการช็อก' }, { id: 'b', text: 'Asystole' }, { id: 'c', text: 'PEA เสมอ' }, { id: 'd', text: 'หัวใจปกติ' }], correctId: 'a', explanation: 'Antiarrhythmic ช่วยทำให้ myocardium เสถียรขึ้น ใช้เสริมเมื่อ shockable rhythm ดื้อต่อการช็อก — ไม่ใช่การรักษาหลักของ asystole/PEA ที่เน้น CPR + หา/แก้สาเหตุ' },
    { id: 'df-post-b14', question: 'ต้องยืนยันทั้ง electrical และ mechanical capture ระหว่าง pacing เพราะอะไร?', choices: [{ id: 'a', text: 'บางครั้งเห็น spike/QRS บนจอ แต่หัวใจไม่บีบตัวจริง (คลำชีพจรไม่ได้)' }, { id: 'b', text: 'เพื่อความสวยงามของกราฟ' }, { id: 'c', text: 'เครื่องบังคับให้ทำ' }, { id: 'd', text: 'ไม่จำเป็น' }], correctId: 'a', explanation: 'Electrical capture (spike+QRS) ไม่รับประกันว่ากล้ามเนื้อบีบตัวมีเลือดไหลจริง — ต้องคลำชีพจรให้ตรงอัตราที่ตั้ง (mechanical capture) จึงยืนยันว่า pacing ได้ผลต่อการไหลเวียนจริง' },
    { id: 'df-post-b15', question: 'เป้าหมายของการลด pre-shock pause โดยตรงคืออะไร?', choices: [{ id: 'a', text: 'คง coronary perfusion pressure ไว้เพื่อเพิ่มโอกาสช็อกสำเร็จ' }, { id: 'b', text: 'ประหยัดไฟ' }, { id: 'c', text: 'ให้ผู้ป่วยพัก' }, { id: 'd', text: 'ลดเสียงเครื่อง' }], correctId: 'a', explanation: 'เมื่อหยุดกด CPP ตกเร็วภายในไม่กี่วินาที และต้องกดหลายครั้งกว่าจะไต่กลับ — pre-shock pause ที่สั้นคง CPP ไว้ในจังหวะสำคัญ เพิ่มโอกาสที่ช็อกจะเปลี่ยน VF กลับเป็นจังหวะมีชีพจร' },
    { id: 'df-post-b16', question: 'ผู้ป่วยมี ICD ฝังใต้ผิวหนัง ควรวาง pad อย่างไร?', choices: [{ id: 'a', text: 'เว้นระยะห่างจากตัวเครื่อง ไม่วางทับ' }, { id: 'b', text: 'วางทับตัวเครื่องพอดี' }, { id: 'c', text: 'ห้ามช็อกเด็ดขาด' }, { id: 'd', text: 'ต้องผ่าเอา ICD ออกก่อน' }], correctId: 'a', explanation: 'วาง pad ทับตัว ICD/pacemaker ทำให้กระแสถูก shunt เข้าเครื่อง (ช็อกหัวใจได้น้อยลง) และอาจทำเครื่องเสียหาย — เว้นระยะห่างแล้วช็อกได้ตามปกติ ไม่ต้องถอด/ผ่าเครื่องออก' },
    { id: 'df-post-b17', question: 'ก่อนกดปุ่มช็อก ขั้นตอนความปลอดภัยที่ถูกต้องคือ?', choices: [{ id: 'a', text: 'ประกาศเคลียร์ + มองรอบให้ทุกคนพ้นตัวผู้ป่วย + ย้ายออกซิเจนที่ไหลอิสระออก' }, { id: 'b', text: 'ให้ทุกคนช่วยจับผู้ป่วย' }, { id: 'c', text: 'ไม่ต้องเตือนใคร' }, { id: 'd', text: 'จ่อออกซิเจนที่หน้าอก' }], correctId: 'a', explanation: 'ต้องประกาศและตรวจด้วยตาว่าไม่มีใครสัมผัสผู้ป่วย/เตียง และย้ายแหล่งออกซิเจนออกห่าง เพราะกระแสอาจช็อตผู้สัมผัส และประกายไฟใกล้ออกซิเจนเสี่ยงไฟลุก' },
    { id: 'df-post-b18', question: 'เส้นเกือบราบบนจอ ยังไม่แน่ใจว่า fine VF หรือ asystole ควรทำอย่างไรก่อนตัดสินใจช็อก?', choices: [{ id: 'a', text: 'ตรวจ lead/สาย, เพิ่ม gain, ดูหลาย lead' }, { id: 'b', text: 'ช็อกทันทีเสมอ' }, { id: 'c', text: 'สรุปว่า asystole แล้วหยุด' }, { id: 'd', text: 'ปิดจอ' }], correctId: 'a', explanation: 'Fine VF อาจดูคล้าย asystole — ตรวจว่าสายต่อครบ เพิ่ม gain และดูหลาย lead ก่อน เพื่อไม่พลาดโอกาสช็อก VF จริง แต่ก็ไม่ช็อกเส้นราบทุกกรณีเพราะ asystole จริงไม่ควรช็อก' },
  ],
};
