// IV/IO pre-test — Set A. Diagnostic check before starting the lessons
// (not a certificate requirement — same pattern as bls-hcp/preTest/setA.js).
export const setA = {
  id: 'iv-pretest-a',
  title: 'ชุด A',
  questions: [
    { id: 'iv-pt-a1', question: 'เข็มขนาดใดมีรูใหญ่กว่ากัน?', choices: [{ id: 'a', text: '14G' }, { id: 'b', text: '22G' }, { id: 'c', text: 'เท่ากัน' }, { id: 'd', text: 'ไม่แน่นอน' }], correctId: 'a', explanation: 'เลขเกจยิ่งน้อย รูสายยิ่งใหญ่' },
    { id: 'iv-pt-a2', question: 'ตำแหน่งแรกที่เลือกเปิด peripheral IV ในภาวะฉุกเฉินคือ?', choices: [{ id: 'a', text: 'Antecubital fossa' }, { id: 'b', text: 'หลังเท้า' }, { id: 'c', text: 'คอ' }, { id: 'd', text: 'ขาหนีบ' }], correctId: 'a', explanation: 'ข้อพับแขนมีเส้นใหญ่ ใส่ง่าย' },
    { id: 'iv-pt-a3', question: 'Infiltration คือภาวะแทรกซ้อนแบบใด?', choices: [{ id: 'a', text: 'สารน้ำไหลเข้าเนื้อเยื่อรอบข้าง' }, { id: 'b', text: 'เส้นเลือดอักเสบ' }, { id: 'c', text: 'ติดเชื้อในกระแสเลือด' }, { id: 'd', text: 'เส้นเลือดแตก' }], correctId: 'a', explanation: 'สายเลื่อนหลุดทำให้สารน้ำไหลเข้าเนื้อเยื่อแทน' },
    { id: 'iv-pt-a4', question: 'ตำแหน่งที่นิยมที่สุดสำหรับ IO ในผู้ใหญ่คือ?', choices: [{ id: 'a', text: 'Proximal tibia' }, { id: 'b', text: 'กะโหลกศีรษะ' }, { id: 'c', text: 'ซี่โครง' }, { id: 'd', text: 'กระดูกสันหลัง' }], correctId: 'a', explanation: 'คลำจุดสังเกตได้ง่าย นิยมที่สุด' },
    { id: 'iv-pt-a5', question: 'สัญญาณที่บ่งบอกว่าเข็ม IO ถึงโพรงไขกระดูกคืออะไร?', choices: [{ id: 'a', text: 'รู้สึก "pop" หรือแรงต้านลดลงกะทันหัน' }, { id: 'b', text: 'ผู้ป่วยหายปวด' }, { id: 'c', text: 'ผิวเปลี่ยนสี' }, { id: 'd', text: 'ไม่มีสัญญาณ' }], correctId: 'a', explanation: 'ความรู้สึก pop บ่งบอกว่าทะลุ cortex แล้ว' },
    { id: 'iv-pt-a6', question: 'ข้อห้ามของ IO คือข้อใด?', choices: [{ id: 'a', text: 'กระดูกหักหรือติดเชื้อบริเวณจุดแทง' }, { id: 'b', text: 'อายุน้อย' }, { id: 'c', text: 'ไม่มีเส้นเลือดส่วนปลาย' }, { id: 'd', text: 'หมดสติ' }], correctId: 'a', explanation: 'กระดูกหัก/ติดเชื้อเป็นข้อห้ามชัดเจน' },
    { id: 'iv-pt-a7', question: 'ทำไมต้อง flush หลังฉีดยาระหว่าง CPR?', choices: [{ id: 'a', text: 'ดันยาที่ค้างในสายให้เข้าสู่ระบบไหลเวียนกลางเร็วขึ้น' }, { id: 'b', text: 'ล้างสายให้สะอาด' }, { id: 'c', text: 'ลดความเจ็บปวด' }, { id: 'd', text: 'ไม่มีเหตุผลพิเศษ' }], correctId: 'a', explanation: 'การไหลเวียนช้าระหว่าง CPR ต้องอาศัย flush ช่วยดัน' },
    { id: 'iv-pt-a8', question: 'ปริมาณ flush มาตรฐานในผู้ใหญ่คือเท่าไร?', choices: [{ id: 'a', text: '2 mL' }, { id: 'b', text: '20 mL' }, { id: 'c', text: '200 mL' }, { id: 'd', text: 'ไม่ต้อง flush' }], correctId: 'b', explanation: '20 mL เป็นมาตรฐานทั่วไป' },
    { id: 'iv-pt-a9', question: 'ควรทำอย่างไรเมื่อ IV ไม่สำเร็จในภาวะ cardiac arrest?', choices: [{ id: 'a', text: 'พยายามต่อไม่จำกัดเวลา' }, { id: 'b', text: 'เปลี่ยนไป IO ทันที' }, { id: 'c', text: 'หยุดให้ยา' }, { id: 'd', text: 'รอผู้ป่วยฟื้นเอง' }], correctId: 'b', explanation: 'เปลี่ยนไป IO ทันทีเพื่อไม่เสียเวลา' },
    { id: 'iv-pt-a10', question: 'Amiodarone/Lidocaine ใช้เมื่อใด?', choices: [{ id: 'a', text: 'VF/pVT ที่ shock ไม่หาย' }, { id: 'b', text: 'ไข้สูง' }, { id: 'c', text: 'ปวดหัว' }, { id: 'd', text: 'ท้องเสีย' }], correctId: 'a', explanation: 'เป็น antiarrhythmic สำหรับ shockable rhythm ดื้อต่อ shock' },
    { id: 'iv-pt-a11', question: 'ทำไมไม่แนะนำให้ยาผ่าน ETT แล้ว?', choices: [{ id: 'a', text: 'การดูดซึมผ่านปอดคาดเดาไม่ได้แน่นอน' }, { id: 'b', text: 'ยาจะระเหยหมด' }, { id: 'c', text: 'ETT ให้ยาไม่ได้เลย' }, { id: 'd', text: 'ไม่มีเหตุผล' }], correctId: 'a', explanation: 'ผลไม่แน่นอนกว่า IV/IO มาก' },
    { id: 'iv-pt-a12', question: 'Route ใดไม่เหมาะระหว่าง cardiac arrest?', choices: [{ id: 'a', text: 'IV' }, { id: 'b', text: 'IO' }, { id: 'c', text: 'Oral' }, { id: 'd', text: 'ทั้ง IV และ IO' }], correctId: 'c', explanation: 'ผู้ป่วยหมดสติกลืนยาไม่ได้ และดูดซึมช้าเกินไป' },
    { id: 'iv-pt-a13', question: 'ทำไมสายขนาดใหญ่สำคัญเมื่อสงสัย hypovolemia?', choices: [{ id: 'a', text: 'อัตราไหลเพิ่มขึ้นมากตามรัศมีสายที่ใหญ่ขึ้น' }, { id: 'b', text: 'เจ็บน้อยกว่า' }, { id: 'c', text: 'ไม่มีความแตกต่าง' }, { id: 'd', text: 'ราคาถูกกว่า' }], correctId: 'a', explanation: 'อัตราไหลสัมพันธ์กับรัศมีสายยกกำลังสี่' },
    { id: 'iv-pt-a14', question: 'สารน้ำหลักในภาวะ hypovolemic shock คือ?', choices: [{ id: 'a', text: 'Crystalloid และ blood products ตามความรุนแรง' }, { id: 'b', text: 'น้ำเปล่า' }, { id: 'c', text: 'ยาลดไข้' }, { id: 'd', text: 'ไม่ต้องให้สารน้ำ' }], correctId: 'a', explanation: 'Crystalloid/blood products เป็นการรักษาหลัก' },
    { id: 'iv-pt-a15', question: 'ยาที่ให้ทาง IV ได้ ให้ทาง IO ได้หรือไม่?', choices: [{ id: 'a', text: 'ได้เกือบทั้งหมด — ดูดซึมใกล้เคียง IV' }, { id: 'b', text: 'ไม่ได้เลย' }, { id: 'c', text: 'ได้เฉพาะยาแก้ปวด' }, { id: 'd', text: 'ไม่แน่นอน' }], correctId: 'a', explanation: 'IO เข้าสู่ระบบไหลเวียนกลางโดยตรง ยาที่ให้ IV ได้ให้ IO ได้เกือบทั้งหมด' },
  ],
};
