// BLS Training Scenarios — Thai language (EMR drill: /scenarios → /recording)
// รูปแบบเดียวกับ src/data/scenarios.js (ระบบ ACLS) — ดู header comment ที่นั่นสำหรับ field
// เพิ่มเติมของ BLS:
//   step.correctActions มี 2 token ใหม่ที่ SimulationEngine.jsx รู้จัก:
//     'aed_attach'  — กด "Pads ติดแล้ว" (AEDPanel mode=initial, phase=attach)
//     'aed_analyze' — AED วิเคราะห์เสร็จ ("Shock/No Shock Advised") — ไม่ gate รอบ
//   scenario.aedPlan: ['shock' | 'no_shock', ...] — ผลตัดสิน AED ของแต่ละรอบวิเคราะห์
//     ตามลำดับ (ไม่สุ่ม 50/50 แบบ default) อ่านโดย StepRouter.jsx (resolveAedVerdict)
//   category: 'cardiac_arrest' | 'pediatric_arrest' (เด็ก/ทารก — gate รอบ CPR
//     เหมือน cardiac_arrest) | 'respiratory' | 'special'
//
// ลำดับ step มาตรฐานของทุกเคส (BLS survey → CPR → AED):
//   scene_safety → check_response → call_for_help → start_cpr → monitor →
//   aed_attach → aed_analyze → (defib_aed | resume_cpr) →
//   [รอบถัดไป (ถ้ามี): check_pulse (gated, ปุ่ม "AED Analyze" รอบ 2) → aed_analyze →
//     (defib | resume_cpr)] → check_pulse (gated, เช็คสัญญาณ ROSC) → rosc
// หมายเหตุ: shock "รอบแรก" ของแต่ละเคสใช้ token 'defib_aed' (ไม่ gate) ส่วน shock
// "รอบถัดไป" ใช้ token เปล่า 'defib' (gate 110 วิ) — ตามธรรมเนียมเดียวกับ
// scenarios.js ฝั่ง ACLS (defib_200j ครั้งแรก / defib เปล่าครั้งถัดไป)

export const scenarios = [
  // =============== BASIC ===============
  {
    id: 'bls_adult_vf_01',
    title: 'Adult VF — Basic',
    title_th: 'หัวใจหยุดเต้นในฟิตเนส — พื้นฐาน',
    level: 'basic',
    category: 'cardiac_arrest',
    description_th: 'ชาย 52 ปี ล้มหมดสติขณะออกกำลังกายในฟิตเนส',
    visual: { patientLabel_th: 'ชาย 52 ปี', scene_th: 'ฟิตเนสเซ็นเตอร์' },
    aedPlan: ['shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'ชาย 52 ปี ล้มหมดสติขณะยกน้ำหนักในฟิตเนส เพื่อนออกกำลังกายวิ่งมาขอความช่วยเหลือ',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย — เข้าถึงผู้ป่วยได้!' },
        hint_th: 'ตรวจสอบความปลอดภัยของที่เกิดเหตุก่อนเสมอ',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'เข้าถึงผู้ป่วยแล้ว — นอนหงายไม่เคลื่อนไหว',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'เรียกแล้วไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'ตบไหล่ + ตะโกนเรียก "คุณเป็นอะไรไหม" พร้อมดูการหายใจ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669 แล้ว! ขอ AED ด่วน!' },
        hint_th: 'เรียกคนช่วย + โทร 1669 + ขอ AED ทันที',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร (carotid pulse ≤10 วินาที)',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'ปั๊มเลย! ลึก 5-6 ซม. 100-120 ครั้ง/นาที!' },
        hint_th: 'เริ่ม CPR ทันที — กดลึก 5-6 cm, 100-120/min, 30:2',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'กด CPR ต่อเนื่อง — เพื่อนหยิบ AED มาถึงแล้ว',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว!' },
        hint_th: 'ติดเครื่อง AED โดยไม่หยุดกดหน้าอก',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'ติด pad ใต้กระดูกไหปลาร้าขวา + ใต้รักแร้ซ้าย ไม่หยุด CPR ระหว่างติด',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์จังหวะหัวใจ — ทุกคนถอยห่างจากผู้ป่วย',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"Shock Advised" — เตรียม shock!' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์ รอผลจาก AED',
      },
      {
        trigger: 'after_analyze_shock',
        scenario_th: 'AED แนะนำ SHOCK — ตะโกน "CLEAR!" แล้วกด shock',
        ekg: 'vf',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['defib_aed'],
        onCorrect: { line_th: 'CLEAR! ⚡ Shock แล้ว — กลับไป CPR ต่อทันที!' },
        hint_th: 'ตรวจให้แน่ใจไม่มีใครแตะผู้ป่วยก่อนกด SHOCK',
      },
      {
        trigger: 'after_shock',
        scenario_th: 'กด CPR ต่อ 2 นาทีเต็ม — EtCO₂ เริ่มขยับขึ้น ผู้ป่วยเริ่มขยับแขน',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'ครบรอบ CPR 2 นาที → กดปุ่ม AED Analyze อีกครั้งเพื่อเช็คสัญญาณชีพ',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจเองได้! ROSC!',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ยอดเยี่ยมมากทีม — จัดท่า Recovery Position รอทีมส่งต่อ' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC บน Quick Bar',
      },
    ],
  },

  {
    id: 'bls_adult_noshock_01',
    title: 'Adult No-Shock — Basic',
    title_th: 'หัวใจหยุดเต้นใน Ward — พื้นฐาน',
    level: 'basic',
    category: 'cardiac_arrest',
    description_th: 'หญิง 68 ปี พบนอนนิ่งบนเตียงใน ward หลังผ่าตัด',
    visual: { patientLabel_th: 'หญิง 68 ปี', scene_th: 'Ward หลังผ่าตัด' },
    aedPlan: ['no_shock', 'no_shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'พยาบาลรอบเวรพบผู้ป่วยหญิง 68 ปี นอนนิ่งบนเตียง ไม่ขยับ',
        speaker: 'nurse_mint', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'สิ่งแวดล้อมปลอดภัย — ประเมินผู้ป่วยเลย!' },
        hint_th: 'ตรวจสอบสายระโยงระยาง/สิ่งกีดขวางรอบเตียงก่อน',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'เขย่าไหล่เรียกไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'เขย่าไหล่ + เรียกดัง ๆ พร้อมสังเกตการหายใจ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'กด Code Blue! ทีมกู้ชีพกำลังมา พร้อม AED!' },
        hint_th: 'กด Code Blue + ขอรถ Emergency + AED',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR ทันที!' },
        hint_th: 'เริ่ม CPR — 100-120/min, ลึก 5-6 cm',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ทีมกู้ชีพมาถึงพร้อม AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว!' },
        hint_th: 'ติดเครื่อง AED โดยไม่หยุดกดหน้าอก',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'ติด pad ทั้งสองข้าง ไม่หยุด CPR ระหว่างติด',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" — กลับไป CPR ต่อทันที!' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_no_shock_1',
        scenario_th: 'AED ไม่แนะนำ shock — กลับไปกด CPR ต่อทันที',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'กด CPR ต่อทันที ไม่เสียเวลาตรวจชีพจร!' },
        hint_th: 'No shock advised → กลับไป CPR ต่อทันที ห้ามเสียเวลา',
      },
      {
        trigger: 'after_resume_1',
        scenario_th: 'กด CPR ต่อครบ 2 นาที — ถึงเวลาวิเคราะห์รอบใหม่',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { line_th: 'ถึงรอบวิเคราะห์ใหม่แล้ว!' },
        hint_th: 'ครบรอบ CPR 2 นาที → กดปุ่ม AED Analyze อีกครั้ง',
      },
      {
        trigger: 'after_recheck',
        scenario_th: 'AED วิเคราะห์รอบ 2 — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" อีกครั้ง — CPR ต่อ' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_no_shock_2',
        scenario_th: 'ยังไม่ shockable — กลับไป CPR ต่อ',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อเนื่อง — EtCO₂ เริ่มขยับขึ้น' },
        hint_th: 'No shock advised → CPR ต่อทันที',
      },
      {
        trigger: 'after_resume_2',
        scenario_th: 'ครบรอบอีกครั้ง — ผู้ป่วยเริ่มไอ ขยับแขน',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'สัญญาณชีพเริ่มกลับมา → เช็คชีพจรทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจได้เอง! ROSC!',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! เตรียมส่งต่อ ICU' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC',
      },
    ],
  },

  {
    id: 'bls_ohca_bystander_01',
    title: 'OHCA Bystander — Basic',
    title_th: 'ล้มหมดสติหน้าห้าง — พื้นฐาน',
    level: 'basic',
    category: 'cardiac_arrest',
    description_th: 'ชายวัยกลางคน 60 ปี ล้มหมดสติหน้าห้างสรรพสินค้า มีคนมุงดู',
    visual: { patientLabel_th: 'ชาย 60 ปี', scene_th: 'ลานหน้าห้างสรรพสินค้า' },
    aedPlan: ['shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'คุณเดินผ่านมาเห็นชาย 60 ปี ล้มลงกะทันหันหน้าห้าง มีคนมุงดูแต่ไม่มีใครช่วย',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย ไม่มีรถวิ่งผ่าน — เข้าไปช่วยได้!' },
        hint_th: 'มองรอบตัวเช็คการจราจร/อันตรายก่อนเข้าไปช่วย',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'เข้าไปประเมินผู้ป่วย',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ! (gasping)' },
        hint_th: 'เขย่าไหล่ + เรียกดัง + สังเกตการหายใจ 5-10 วิ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง หายใจแบบ gasping (ไม่ใช่หายใจปกติ)',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! ขอให้คนไปตาม AED ที่ล็อบบี้ห้าง!' },
        hint_th: 'โทร 1669 ทันที + ส่งคนไปเอา AED (มักมีติดตั้งในห้าง)',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR ทันที ไม่รอ AED มาก่อน!' },
        hint_th: 'เริ่ม CPR ทันทีระหว่างรอ AED — อย่าเสียเวลา',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'มีคนนำ AED จากห้างมาส่งให้',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'เปิดเครื่อง AED แล้ว!' },
        hint_th: 'เปิดเครื่อง AED โดยไม่หยุดกดหน้าอก',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'ติด pad ตามรูปบนเครื่อง ไม่หยุด CPR ระหว่างติด',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — บอกคนรอบข้างให้ถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"Shock Advised" — เตรียม shock!' },
        hint_th: 'ตะโกนบอกคนมุงดูให้ถอยห่างจากผู้ป่วย',
      },
      {
        trigger: 'after_analyze_shock',
        scenario_th: 'AED แนะนำ SHOCK',
        ekg: 'vf',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['defib_aed'],
        onCorrect: { line_th: 'CLEAR! ⚡ Shock แล้ว — CPR ต่อทันที!' },
        hint_th: 'ตรวจให้แน่ใจไม่มีใครแตะผู้ป่วยก่อนกด SHOCK',
      },
      {
        trigger: 'after_shock',
        scenario_th: 'CPR ต่อ 2 นาที — รถพยาบาลใกล้ถึง',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'ครบรอบ 2 นาที → เช็คสัญญาณชีพอีกครั้ง',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจได้เอง! ROSC! รถพยาบาลมาถึงพอดี',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ส่งต่อทีม EMS' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC',
      },
    ],
  },

  // =============== INTERMEDIATE ===============
  {
    id: 'bls_two_rescuer_01',
    title: 'Two-Rescuer CPR — Intermediate',
    title_th: 'CPR สองคน — ระดับกลาง',
    level: 'intermediate',
    category: 'cardiac_arrest',
    description_th: 'ชาย 47 ปี หมดสติในห้องออกกำลังกายที่ทำงาน มีเพื่อนร่วมงาน 2 คนช่วยกัน',
    visual: { patientLabel_th: 'ชาย 47 ปี', scene_th: 'ห้องออกกำลังกายที่ทำงาน' },
    aedPlan: ['shock', 'no_shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'ชาย 47 ปี ล้มหมดสติกลางห้อง fitness ของบริษัท เพื่อนร่วมงาน 2 คนอยู่ด้วย',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย — เข้าถึงได้!' },
        hint_th: 'ตรวจสอบความปลอดภัย มอบหมายบทบาทให้เพื่อนร่วมงานช่วย',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'เข้าถึงผู้ป่วยแล้ว',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'คนแรกประเมินผู้ป่วย คนที่สองเตรียมโทร 1669',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ — เพื่อนร่วมงานคนที่ 2 พร้อมช่วย',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'คนที่ 2 โทร 1669 + วิ่งไปเอา AED!' },
        hint_th: 'แบ่งงาน: คนหนึ่งโทร 1669 อีกคนไปเอา AED',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร — คนแรกเริ่มกดหน้าอก',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR! คนที่ 2 เตรียมสลับ/ช่วยเปิดทางเดินหายใจ' },
        hint_th: '2-rescuer CPR: คนแรกกดหน้าอก คนที่สองช่วยช่วยหายใจ/เตรียมสลับทุก 2 นาที',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'เพื่อนร่วมงานนำ AED ของบริษัทมาถึง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'เปิดเครื่อง AED แล้ว!' },
        hint_th: 'เปิดเครื่อง AED โดยไม่หยุดกดหน้าอก',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'ติด pad ทั้งสองข้าง ไม่หยุด CPR ระหว่างติด',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"Shock Advised"!' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_shock',
        scenario_th: 'AED แนะนำ SHOCK',
        ekg: 'vf',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['defib_aed'],
        onCorrect: { line_th: 'CLEAR! ⚡ Shock แล้ว — สลับคนกดหน้าอกก่อนเริ่ม CPR ต่อ' },
        hint_th: 'หลัง shock ให้สลับผู้กดหน้าอกทันทีเพื่อลดความล้า แล้ว CPR ต่อ',
      },
      {
        trigger: 'after_shock',
        scenario_th: 'สลับคนกด CPR ต่อครบ 2 นาที',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { line_th: 'ถึงรอบวิเคราะห์ใหม่' },
        hint_th: 'ครบรอบ 2 นาที → กด AED Analyze อีกครั้ง',
      },
      {
        trigger: 'after_recheck',
        scenario_th: 'AED วิเคราะห์รอบ 2',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" — CPR ต่อ' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_no_shock',
        scenario_th: 'ไม่ shockable แล้ว — กลับไป CPR ต่อ',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อ — สลับคนกดเมื่อเริ่มล้า' },
        hint_th: 'No shock advised → CPR ต่อทันที สลับคนกดถ้าเหนื่อย',
      },
      {
        trigger: 'after_resume',
        scenario_th: 'ผู้ป่วยเริ่มขยับ ไอ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'สัญญาณชีพเริ่มกลับมา → เช็คชีพจรทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจเองได้! ROSC!',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ทำงานเป็นทีมได้ดีมาก' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC',
      },
    ],
  },

  {
    id: 'bls_opioid_01',
    title: 'Opioid Overdose Arrest — Intermediate',
    title_th: 'Opioid Overdose จนหัวใจหยุดเต้น — ระดับกลาง',
    level: 'intermediate',
    category: 'respiratory',
    description_th: 'ชาย 26 ปี พบหมดสติในห้องน้ำสาธารณะ รูม่านตาเล็กมาก (pinpoint pupils) หายใจแบบ agonal',
    visual: { patientLabel_th: 'ชาย 26 ปี', scene_th: 'ห้องน้ำสาธารณะ' },
    aedPlan: ['no_shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'พบชาย 26 ปี หมดสติในห้องน้ำ ข้างตัวมีเข็มฉีดยา รูม่านตาเล็กมาก หายใจเฮือกเป็นครั้งคราว',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'ระวังของมีคม/เข็ม — สวมถุงมือก่อนเข้าช่วย' },
        hint_th: 'ระวังเข็ม/ของมีคมบริเวณที่เกิดเหตุ สวม PPE ก่อนเสมอ',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'เข้าประเมินผู้ป่วย',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! หายใจเฮือก (gasping) — ไม่ใช่หายใจปกติ!' },
        hint_th: 'Gasping/agonal breathing = ไม่ใช่การหายใจปกติ ต้องรีบประเมินต่อ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง หายใจเฮือกเป็นครั้งคราว สงสัย opioid overdose',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! แจ้งสงสัย opioid overdose ขอ naloxone!' },
        hint_th: 'โทร 1669 + แจ้งอาการสงสัย opioid overdose (ถ้ามี naloxone ให้ทีม EMS บริหารยา)',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร — หายใจเฮือกไม่นับเป็นหายใจปกติ',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR ทันที!' },
        hint_th: 'ไม่มีชีพจร + gasping = cardiac arrest → เริ่ม CPR ทันที',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ทีม EMS มาถึงพร้อม AED และ naloxone',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว — เตรียมให้ naloxone ตามแนวทาง ALS ต่อไป' },
        hint_th: 'ติดเครื่อง AED โดยไม่หยุด CPR — naloxone เป็นหน้าที่ทีม advanced ให้ต่อยอด',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'ติด pad ทั้งสองข้าง ไม่หยุด CPR ระหว่างติด',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" — สาเหตุจาก respiratory arrest ไม่ใช่ VF' },
        hint_th: 'Opioid OD มักเป็น PEA/Asystole ไม่ shockable — CPR + ventilation สำคัญที่สุด',
      },
      {
        trigger: 'after_analyze_no_shock',
        scenario_th: 'ไม่ shockable — กลับไป CPR ต่อทันที',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อ — เน้นช่วยหายใจให้ดี (30:2)' },
        hint_th: 'No shock advised → CPR ต่อทันที เน้นคุณภาพการช่วยหายใจ',
      },
      {
        trigger: 'after_resume',
        scenario_th: 'ครบ 2 นาที — หลัง naloxone ผู้ป่วยเริ่มหายใจได้เอง',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร! หายใจได้เอง!' },
        hint_th: 'สัญญาณชีพกลับมาหลัง naloxone ออกฤทธิ์ → เช็คชีพจรทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจได้เอง! ROSC! เฝ้าระวัง re-sedation ต่อเนื่อง',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ต้องเฝ้าระวัง naloxone หมดฤทธิ์ซ้ำ (re-sedation)' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC แต่ต้องเฝ้าระวังต่อเนื่อง',
      },
    ],
  },

  {
    id: 'bls_drowning_child_01',
    title: 'Child Drowning — Intermediate',
    title_th: 'เด็กจมน้ำในสระ — ระดับกลาง',
    level: 'intermediate',
    category: 'pediatric_arrest',
    description_th: 'เด็กชาย 8 ปี ถูกดึงขึ้นจากสระว่ายน้ำ ไม่หายใจ ไม่ตอบสนอง',
    visual: { patientLabel_th: 'เด็กชาย 8 ปี', scene_th: 'ข้างสระว่ายน้ำ' },
    aedPlan: ['no_shock', 'shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'เด็กชาย 8 ปี ถูกไลฟ์การ์ดดึงขึ้นจากสระ วางบนพื้นข้างสระ ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย ห่างจากขอบสระ — เริ่มประเมินได้' },
        hint_th: 'ย้ายเด็กออกห่างขอบสระเล็กน้อยก่อนประเมิน ระวังพื้นลื่น',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'ประเมินเด็ก',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'เขย่าไหล่เบา ๆ + เรียกชื่อ ดูการหายใจ 5-10 วิ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ — ผู้ป่วยเด็กจมน้ำ (สาเหตุ hypoxia)',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! ในเด็กจมน้ำเน้นช่วยหายใจให้เร็วที่สุด' },
        hint_th: 'เด็กจมน้ำ = สาเหตุจาก hypoxia → เน้นเปิดทางเดินหายใจ + ช่วยหายใจให้ไวที่สุด',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR 30:2 — กดลึก 1/3 ของทรวงอก' },
        hint_th: 'เด็ก: กดลึกประมาณ 1/3 ของความหนาทรวงอก อัตรา 100-120/min อัตราส่วน 30:2',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ไลฟ์การ์ดนำ AED มาถึง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว — ใช้แผ่น pediatric ถ้ามี' },
        hint_th: 'ใช้ pediatric pads/attenuator ถ้ามี (เด็ก <8 ปี หรือ <25 กก.)',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED — เช็ดตัวเด็กให้แห้งก่อน (เพิ่งขึ้นจากน้ำ)',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'เช็ดแห้งแล้วติดแผ่น — ให้ AED วิเคราะห์!' },
        hint_th: 'เช็ดหน้าอกให้แห้งก่อนติดแผ่น AED (ผิวเปียกทำให้กระแสไฟรั่ว/แผ่นไม่แนบ)',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" — สาเหตุจาก hypoxia ไม่ใช่ VF ตั้งแต่แรก' },
        hint_th: 'จมน้ำมักเริ่มจาก asystole/PEA จาก hypoxia ไม่ shockable ในช่วงแรก',
      },
      {
        trigger: 'after_analyze_no_shock',
        scenario_th: 'ไม่ shockable — กลับไป CPR ต่อทันที เน้นช่วยหายใจ',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อ — เน้นการช่วยหายใจให้อกยกดี' },
        hint_th: 'No shock advised → CPR ต่อทันที เน้นคุณภาพการช่วยหายใจให้ดี',
      },
      {
        trigger: 'after_resume',
        scenario_th: 'ครบรอบ CPR — จังหวะเปลี่ยนเป็น VF หลังให้ออกซิเจนเพียงพอ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { line_th: 'ถึงรอบวิเคราะห์ใหม่' },
        hint_th: 'ครบรอบ 2 นาที → กด AED Analyze อีกครั้ง',
      },
      {
        trigger: 'after_recheck',
        scenario_th: 'AED วิเคราะห์รอบ 2',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"Shock Advised" — เตรียม shock!' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_shock',
        scenario_th: 'AED แนะนำ SHOCK',
        ekg: 'vf',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['defib'],
        onCorrect: { line_th: 'CLEAR! ⚡ Shock แล้ว — CPR ต่อทันที!' },
        hint_th: 'ตรวจให้แน่ใจไม่มีใครแตะเด็กก่อนกด SHOCK',
      },
      {
        trigger: 'after_shock',
        scenario_th: 'CPR ต่อ — เด็กเริ่มไอ ขยับตัว',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'สัญญาณชีพเริ่มกลับมา → เช็คชีพจรทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร ไอ หายใจได้เอง! ROSC!',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! จัดท่าตะแคง เฝ้าระวัง secondary drowning' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC เฝ้าระวังต่อเนื่อง',
      },
    ],
  },

  {
    id: 'bls_infant_cpr_01',
    title: 'Infant CPR — Intermediate',
    title_th: 'CPR ทารก — ระดับกลาง',
    level: 'intermediate',
    category: 'pediatric_arrest',
    description_th: 'ทารกชาย 6 เดือน แม่พบตัวเขียว ไม่หายใจ ขณะนอนหลับ',
    visual: { patientLabel_th: 'ทารกชาย 6 เดือน', scene_th: 'ห้องนอนที่บ้าน' },
    aedPlan: ['no_shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'แม่พบทารกชาย 6 เดือน ตัวเขียวคล้ำ ไม่หายใจในเปล รีบร้องขอความช่วยเหลือ',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย — เข้าประเมินได้ทันที' },
        hint_th: 'ประเมินสภาพแวดล้อมรอบเปลก่อนเข้าช่วย',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'ประเมินทารก — ดีดฝ่าเท้าเบา ๆ ตอบสนอง',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ! ตัวเขียว!' },
        hint_th: 'ทารก: ดีดฝ่าเท้าเบา ๆ แทนการตบไหล่ ดูการหายใจ 5-10 วิ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! ให้แม่/คนใกล้ตัวโทรระหว่างเริ่มช่วยทารก' },
        hint_th: 'ถ้าอยู่คนเดียวและเป็นทารก: ทำ CPR 2 นาทีก่อนแล้วค่อยโทร (ยกเว้นมีคนช่วยโทรได้เลย)',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'คลำชีพจรที่ brachial artery (แขนด้านใน) ไม่พบ',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR ด้วยเทคนิค two-thumb encircling!' },
        hint_th: 'ทารก: คลำชีพจรที่ brachial artery, CPR ด้วย two-thumb technique, อัตราส่วน 15:2 (2 ผู้ช่วย)',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ทีม EMS มาถึงพร้อม AED แบบมี pediatric pads',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว — ใช้ pediatric attenuator' },
        hint_th: 'ทารก/เด็กเล็ก: ใช้ pediatric pads + attenuator ถ้ามี ถ้าไม่มีใช้ adult pads แทนได้ (ห้ามให้แผ่นซ้อนกัน)',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED — แผ่นเล็กเกินไปสำหรับติดหน้า-หลังพร้อมกันถ้าจำเป็น',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว (หน้าอก-หลัง) — ให้ AED วิเคราะห์!' },
        hint_th: 'ทารกตัวเล็ก: อาจติดแผ่นหน้าอก-หลังแทนซ้าย-ขวาเพื่อไม่ให้แผ่นชนกัน',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised"' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_no_shock',
        scenario_th: 'ไม่ shockable — กลับไป CPR ต่อทันที',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อด้วย two-thumb technique 15:2' },
        hint_th: 'No shock advised → CPR ต่อทันที อัตราส่วน 15:2 ถ้ามี 2 ผู้ช่วยเหลือ',
      },
      {
        trigger: 'after_resume',
        scenario_th: 'ครบรอบ CPR — ทารกเริ่มร้องไห้ ขยับตัว',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจรที่ brachial!' },
        hint_th: 'สัญญาณชีพเริ่มกลับมา → คลำชีพจรที่ brachial artery ทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร ร้องไห้เสียงดัง! ROSC! สีผิวเริ่มกลับมาชมพู',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ห่มผ้าให้อบอุ่น รอทีมส่งต่อ' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC ดูแลรักษาอุณหภูมิกาย',
      },
    ],
  },

  {
    id: 'bls_aed_wet_01',
    title: 'Poolside AED (Wet Chest) — Intermediate',
    title_th: 'AED ข้างสระ (หน้าอกเปียก) — ระดับกลาง',
    level: 'intermediate',
    category: 'special',
    description_th: 'ชาย 35 ปี หมดสติหลังขึ้นจากสระว่ายน้ำ ตัวเปียกโชก',
    visual: { patientLabel_th: 'ชาย 35 ปี', scene_th: 'ขอบสระว่ายน้ำ' },
    aedPlan: ['shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'ชาย 35 ปี หมดสติทันทีหลังขึ้นจากสระ ตัวเปียกโชกทั้งตัว ไลฟ์การ์ดวิ่งมาช่วย',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'ย้ายห่างขอบสระเล็กน้อย — พื้นที่ปลอดภัยแล้ว' },
        hint_th: 'ระวังพื้นลื่นรอบสระ ย้ายผู้ป่วยออกห่างขอบสระก่อนเริ่มช่วย',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'ประเมินผู้ป่วย',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'เขย่าไหล่ + เรียกดัง ดูการหายใจ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! ขอ AED จากจุดปฐมพยาบาลสระว่ายน้ำ!' },
        hint_th: 'สระว่ายน้ำสาธารณะมักมี AED ประจำจุด — ส่งคนไปเอา',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR ทันที!' },
        hint_th: 'เริ่ม CPR ทันที — ลึก 5-6 cm, 100-120/min',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ไลฟ์การ์ดนำ AED มาถึง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'เปิดเครื่อง AED แล้ว!' },
        hint_th: 'เปิดเครื่อง AED โดยไม่หยุด CPR',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'หน้าอกผู้ป่วยยังเปียกอยู่ — ต้องเช็ดให้แห้งก่อนติดแผ่น',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'เช็ดหน้าอกแห้งแล้ว ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'สำคัญ: เช็ดหน้าอกให้แห้งก่อนติดแผ่น AED เสมอ — ผิวเปียกทำให้กระแสไฟรั่วออกด้านข้าง แผ่นไม่แนบ ช็อกไม่ได้ผล',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง (โดยเฉพาะจากพื้นเปียก)',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"Shock Advised" — เตรียม shock!' },
        hint_th: 'ตรวจสอบว่าพื้นรอบตัวผู้ป่วยไม่มีน้ำขังก่อน shock',
      },
      {
        trigger: 'after_analyze_shock',
        scenario_th: 'AED แนะนำ SHOCK',
        ekg: 'vf',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['defib_aed'],
        onCorrect: { line_th: 'CLEAR! ⚡ Shock แล้ว — CPR ต่อทันที!' },
        hint_th: 'ตรวจให้แน่ใจไม่มีใครแตะผู้ป่วยหรือยืนบนพื้นเปียกใกล้ตัวก่อนกด SHOCK',
      },
      {
        trigger: 'after_shock',
        scenario_th: 'CPR ต่อครบ 2 นาที',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'ครบรอบ 2 นาที → เช็คสัญญาณชีพอีกครั้ง',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจได้เอง! ROSC!',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ห่มผ้าอุ่นรอทีมส่งต่อ' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC',
      },
    ],
  },

  // =============== MEGACODE ===============
  {
    id: 'bls_pregnant_arrest_01',
    title: 'Pregnant Cardiac Arrest — Megacode',
    title_th: 'หัวใจหยุดเต้นในหญิงตั้งครรภ์ — Megacode',
    level: 'megacode',
    category: 'special',
    description_th: 'หญิงตั้งครรภ์ 32 สัปดาห์ ล้มหมดสติที่บ้าน สามีโทรขอความช่วยเหลือ',
    visual: { patientLabel_th: 'หญิงตั้งครรภ์ 32 สัปดาห์', scene_th: 'ห้องนั่งเล่นที่บ้าน' },
    aedPlan: ['shock', 'no_shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'หญิงตั้งครรภ์ 32 สัปดาห์ ล้มหมดสติกะทันหันขณะดูทีวี สามีตกใจโทรขอความช่วยเหลือ',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย — เข้าประเมินได้' },
        hint_th: 'ตรวจสอบความปลอดภัยรอบตัวก่อนเข้าช่วย',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'ประเมินผู้ป่วย',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'เขย่าไหล่ + เรียกดัง ดูการหายใจ',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! แจ้งว่าผู้ป่วยตั้งครรภ์ 32 สัปดาห์!' },
        hint_th: 'แจ้งอายุครรภ์ให้ทีม EMS ทราบตั้งแต่แรก — มีผลต่อการเตรียมทีมสูติ',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR! ให้อีกคนดัน uterus ไปทางซ้ายค้างไว้ (manual LUD)' },
        hint_th: 'หญิงตั้งครรภ์ ≥20 สัปดาห์: ทำ manual left uterine displacement (LUD) ระหว่าง CPR เพื่อลดการกดทับ IVC — CPR ทำตามปกติ ไม่ต้องปรับตำแหน่งมือ',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ทีม EMS มาถึงพร้อม AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว — LUD ยังคงค้างไว้ต่อเนื่อง' },
        hint_th: 'ติดเครื่อง AED โดยไม่หยุด CPR/LUD',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์! (ใช้ตำแหน่งปกติได้ ไม่ต้องปรับ)' },
        hint_th: 'ตำแหน่งแผ่น AED ในหญิงตั้งครรภ์ใช้ตำแหน่งมาตรฐานเดียวกัน ไม่ต้องปรับ',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง (รวมคนดัน LUD ต้องปล่อยชั่วคราว)',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"Shock Advised" — เตรียม shock!' },
        hint_th: 'AED ในหญิงตั้งครรภ์ปลอดภัยทั้งแม่และทารกในครรภ์ shock ได้ตามข้อบ่งชี้ปกติ',
      },
      {
        trigger: 'after_analyze_shock',
        scenario_th: 'AED แนะนำ SHOCK',
        ekg: 'vf',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['defib_aed'],
        onCorrect: { line_th: 'CLEAR! ⚡ Shock แล้ว — กลับไป CPR + LUD ต่อทันที!' },
        hint_th: 'ตรวจให้แน่ใจไม่มีใครแตะผู้ป่วยก่อนกด SHOCK แม้กำลังตั้งครรภ์ก็ shock ได้ตามปกติ',
      },
      {
        trigger: 'after_shock',
        scenario_th: 'CPR + LUD ต่อครบ 2 นาที',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { line_th: 'ถึงรอบวิเคราะห์ใหม่' },
        hint_th: 'ครบรอบ 2 นาที → กด AED Analyze อีกครั้ง',
      },
      {
        trigger: 'after_recheck',
        scenario_th: 'AED วิเคราะห์รอบ 2',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" — CPR ต่อ' },
        hint_th: 'ห้ามแตะผู้ป่วยระหว่างวิเคราะห์',
      },
      {
        trigger: 'after_analyze_no_shock',
        scenario_th: 'ไม่ shockable — กลับไป CPR + LUD ต่อ',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อ — เตรียมทีมสูติหากไม่ตอบสนองใน 4-5 นาที (resuscitative hysterotomy)' },
        hint_th: 'No shock advised → CPR ต่อทันที ทีมโรงพยาบาลเตรียมพร้อมสำหรับ perimortem C-section หากจำเป็น',
      },
      {
        trigger: 'after_resume',
        scenario_th: 'ผู้ป่วยเริ่มขยับ ไอ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'สัญญาณชีพเริ่มกลับมา → เช็คชีพจรทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร หายใจได้เอง! ROSC! ทารกในครรภ์ยังต้องประเมินต่อที่ รพ.',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! คง LUD ต่อระหว่างส่งต่อ รพ. เพื่อประเมินทารกในครรภ์' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC คง left tilt/LUD ระหว่างเคลื่อนย้าย',
      },
    ],
  },

  {
    id: 'bls_choking_arrest_01',
    title: 'Choking → Cardiac Arrest — Megacode',
    title_th: 'สำลักจนหมดสติและหัวใจหยุดเต้น — Megacode',
    level: 'megacode',
    category: 'special',
    description_th: 'ชาย 45 ปี สำลักอาหารในร้านอาหาร เพื่อนพยายามช่วยเหลือแต่ผู้ป่วยหมดสติไปต่อหน้า',
    visual: { patientLabel_th: 'ชาย 45 ปี', scene_th: 'ร้านอาหาร' },
    aedPlan: ['no_shock'],
    steps: [
      {
        trigger: 'initial',
        scenario_th: 'ชาย 45 ปี สำลักอาหารกลางร้าน ทำท่ากำมือที่คอ (choking sign) เพื่อนลุกขึ้นช่วยตบหลัง+ดันท้อง (back blows + abdominal thrusts) หลายครั้งแต่สิ่งแปลกปลอมไม่หลุด — ผู้ป่วยหมดสติล้มลงไปต่อหน้า',
        speaker: 'att_dech', pose: 'stern',
        correctActions: ['scene_safety'],
        onCorrect: { line_th: 'พื้นที่ปลอดภัย — วางผู้ป่วยนอนหงายบนพื้นแข็ง' },
        hint_th: 'เมื่อผู้ป่วยสำลักหมดสติ ให้วางนอนหงายบนพื้นแข็งทันที เตรียมเริ่ม CPR',
      },
      {
        trigger: 'after_scene_safety',
        scenario_th: 'ประเมินผู้ป่วยที่หมดสติ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_response'],
        onCorrect: { pose: 'panic', line_th: 'ไม่ตอบสนอง! ไม่หายใจ!' },
        hint_th: 'ผู้ป่วยสำลักที่หมดสติ = ทางเดินหายใจอุดกั้นสมบูรณ์ ต้องเริ่ม CPR ทันที (การกด CPR ช่วยดันสิ่งแปลกปลอมได้ด้วย)',
      },
      {
        trigger: 'after_check_response',
        scenario_th: 'ไม่ตอบสนอง ไม่หายใจ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['call_for_help'],
        onCorrect: { line_th: 'โทร 1669! แจ้งสำลักจนหมดสติ!' },
        hint_th: 'โทร 1669 ทันที แจ้งว่าเป็นเหตุสำลักที่นำไปสู่หมดสติ',
      },
      {
        trigger: 'after_call_help',
        scenario_th: 'ไม่มีชีพจร — เตรียมเริ่ม CPR ทุกครั้งก่อนช่วยหายใจ ให้เปิดปากดูก่อนว่ามีสิ่งแปลกปลอมมองเห็นได้หรือไม่',
        speaker: 'boy_compressor', pose: 'panic',
        correctActions: ['start_cpr'],
        onCorrect: { pose: 'stern', line_th: 'เริ่ม CPR! เปิดปากเช็คก่อนช่วยหายใจทุกรอบ — เอาออกถ้าเห็นสิ่งแปลกปลอม' },
        hint_th: 'CPR ในผู้ป่วยสำลัก: ก่อนช่วยหายใจแต่ละรอบ เปิดปากดู ถ้าเห็นสิ่งแปลกปลอมให้เขี่ยออก (ห้ามควานหาแบบไม่เห็น)',
      },
      {
        trigger: 'after_cpr_start',
        scenario_th: 'ทีม EMS มาถึงพร้อม AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['monitor'],
        onCorrect: { line_th: 'ติดเครื่อง AED แล้ว!' },
        hint_th: 'ติดเครื่อง AED โดยไม่หยุด CPR',
      },
      {
        trigger: 'after_monitor',
        scenario_th: 'พร้อมติดแผ่น AED',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_attach'],
        onCorrect: { line_th: 'ติดแผ่นแล้ว — ให้ AED วิเคราะห์!' },
        hint_th: 'ติด pad ทั้งสองข้าง ไม่หยุด CPR ระหว่างติด',
      },
      {
        trigger: 'after_attach',
        scenario_th: 'AED กำลังวิเคราะห์ — ทุกคนถอยห่าง',
        speaker: 'fon_defib', pose: 'panic',
        correctActions: ['aed_analyze'],
        onCorrect: { line_th: '"No Shock Advised" — สาเหตุจาก hypoxia ไม่ใช่ VF' },
        hint_th: 'Arrest จากสำลัก/หายใจไม่ออก มักไม่ shockable ในช่วงแรก (asystole/PEA จาก hypoxia)',
      },
      {
        trigger: 'after_analyze_no_shock',
        scenario_th: 'ไม่ shockable — กลับไป CPR ต่อทันที',
        speaker: 'boy_compressor', pose: 'stern',
        correctActions: ['resume_cpr'],
        onCorrect: { line_th: 'CPR ต่อ — เปิดปากเช็คสิ่งแปลกปลอมทุกรอบก่อนช่วยหายใจ' },
        hint_th: 'No shock advised → CPR ต่อทันที เช็คปากทุกรอบก่อนช่วยหายใจ',
      },
      {
        trigger: 'after_resume',
        scenario_th: 'ครบรอบ CPR — สิ่งแปลกปลอมหลุดออกมาระหว่างกด CPR ผู้ป่วยเริ่มไอ',
        speaker: 'nurse_mint', pose: 'panic',
        correctActions: ['check_pulse'],
        onCorrect: { pose: 'happy', line_th: 'คลำได้ชีพจร!' },
        hint_th: 'ทางเดินหายใจโล่งแล้ว สัญญาณชีพเริ่มกลับมา → เช็คชีพจรทันที',
      },
      {
        trigger: 'after_pulse_check',
        scenario_th: 'คลำได้ชีพจร ไอแรง หายใจได้เอง! ROSC!',
        rhythm: 'rosc',
        speaker: 'att_dech', pose: 'happy',
        correctActions: ['rosc'],
        onCorrect: { pose: 'happy', line_th: 'ROSC! ยืนยันไม่มีสิ่งแปลกปลอมค้างในทางเดินหายใจก่อนส่งต่อ' },
        hint_th: 'พบสัญญาณ ROSC ชัดเจน → กดปุ่ม ROSC ตรวจซ้ำว่าไม่มีเศษอาหารค้างในปาก',
      },
    ],
  },
];

// Get scenarios by level
export function getScenariosByLevel(level) {
  return scenarios.filter(s => s.level === level);
}

// Get scenarios by category
export function getScenariosByCategory(category) {
  return scenarios.filter(s => s.category === category);
}

// Get scenario by id
export function getScenarioById(id) {
  return scenarios.find(s => s.id === id);
}
