// BLS for Healthcare Providers — pre-course lessons (BLS per ILCOR 2025, ผสม TRC notes)
// ใช้ schema เดียวกับ src/data/preCourseContent.js เพื่อให้ LessonReader engine ใช้ได้เลย
//
// IMPORTANT: เนื้อหาในไฟล์นี้เป็น draft ที่ paraphrase จากแนวทาง ILCOR 2025 + TRC
// ต้องผ่าน medical review โดยแพทย์ EM/ICU ก่อนปล่อย production
// ระวังลิขสิทธิ์ ILCOR 2025 — ห้าม quote algorithm table ตรง ๆ ใช้ paraphrase เท่านั้น

export const preCourseVideos = [
  {
    platform: 'youtube',
    label: 'ดูบน YouTube',
    url: 'https://youtube.com/@jia-bu8yn',
  },
  {
    platform: 'tiktok',
    label: 'ดูบน TikTok',
    url: 'https://www.tiktok.com/@jia_lucksa',
  },
];

// Per-lesson videos — แต่ละบทมีวีดีโอเฉพาะของตัวเอง
// TODO: แทนที่ url ด้วยลิงก์วีดีโอ specific ของแต่ละบทเมื่อพร้อม
const lessonVideos = {
  'bls-1': [
    { platform: 'youtube', label: 'ดูบน YouTube', url: 'https://youtu.be/7RrA-X0vhq0' },
  ],
  'bls-2': [
    { platform: 'youtube', label: 'ดูบน YouTube', url: 'https://youtu.be/IbvE4PnW_80' },
  ],
  'bls-3': [
    { platform: 'youtube', label: 'ผู้ใหญ่ (YouTube)', url: 'https://youtu.be/dtIswl6Od2I' },
    { platform: 'youtube', label: 'เด็ก (YouTube)', url: 'https://youtu.be/lCbImOmcrNA' },
  ],
  'bls-4': [
    { platform: 'youtube', label: 'ดูบน YouTube', url: 'https://youtu.be/dQ9TcHdhIr0' },
  ],
  'bls-5': [
    { platform: 'youtube', label: 'ดูบน YouTube', url: 'https://youtu.be/0kaOCefb-xc' },
  ],
  'bls-6': [
    { platform: 'youtube', label: 'ดูบน YouTube', url: 'https://youtu.be/fu65-_ENCLo' },
  ],
  'bls-7': [
    { platform: 'youtube', label: 'ผู้ใหญ่ (YouTube)', url: 'https://youtu.be/t3WnWOOVh2c' },
    { platform: 'youtube', label: 'เด็ก (YouTube)', url: 'https://youtu.be/pCgxwQUzph0' },
  ],
  'bls-1r': [
    { platform: 'youtube', label: 'ดูบน YouTube', url: 'https://youtu.be/ayov6IVgW7w' },
  ],
};

const lessonDefs = [
  // ===================== บทที่ 1 =====================
  {
    id: 'bls-1',
    title: 'บทที่ 1: ภาพรวม BLS และ Chain of Survival',
    description: 'ห่วงโซ่การรอดชีวิตในโรงพยาบาล (IHCA) และนอกโรงพยาบาล (OHCA) บทบาทของผู้ช่วยเหลือคนแรก',
    estMinutes: 6,
    passingScore: 75,
    steps: [
      { type: 'read', heading: 'BLS คืออะไร',
        body: 'Basic Life Support (BLS) คือชุดทักษะพื้นฐานที่บุคลากรทางการแพทย์ทุกคนต้องทำได้:\n• จดจำภาวะหัวใจหยุดเต้นทันที\n• เรียกขอความช่วยเหลือ + ขอ defibrillator\n• กดหน้าอกคุณภาพสูง\n• ใช้ AED เร็วที่สุด\n• ดูแลทางเดินหายใจขั้นพื้นฐาน' },
      { type: 'read', heading: 'Universal Chain of Survival (6 links)',
        body: 'ตามแนวทางปี 2025 ใช้ Universal Chain เดียวครอบคลุมทั้งใน รพ. (IHCA) และนอก รพ. (OHCA):\n1) Early Recognition & Prevention — เฝ้าระวังสัญญาณชีพ + เรียก RRT/MET ก่อนเกิด arrest (IHCA) หรือ จดจำเหตุเร็ว (OHCA)\n2) Early High-Quality CPR — เริ่มทันที กดลึก 5–6 ซม. อัตรา 100–120/min CCF > 80%\n3) Defibrillation — AED/defib ให้เร็วที่สุดเมื่อพบ shockable rhythm\n4) Advanced Resuscitation — airway, IV/IO, ยา, capnography, ค้นหา H\'s & T\'s\n5) Post-Cardiac Arrest Care — TTM/Temperature Control, MAP target, PCI, ICU\n6) Recovery & Survivorship — ฟื้นฟูระบบประสาท, จิตใจ, การสนับสนุนครอบครัว, team debrief' },
      { type: 'read', heading: 'IHCA vs OHCA — Chain เดียว สองบริบท',
        body: '• IHCA (ใน รพ.): มักมีสัญญาณเตือนล่วงหน้า — เน้นห่วง 1 (เฝ้าระวัง + RRT/MET/code blue ก่อน arrest)\n• OHCA (นอก รพ.): เน้น bystander CPR ทันที + AED ในชุมชน + EMS — dispatcher-assisted CPR coaching ช่วยเพิ่ม survival\n• Hands-only CPR แนะนำเฉพาะ untrained bystander; BLS-HCP ต้องช่วยหายใจเสมอ' },
      { type: 'quiz', id: 'bls-1-q1',
        question: 'พบผู้ป่วยหมดสติ ไม่ตอบสนอง ใน ward — ขั้นตอนแรกที่ควรทำคืออะไร?',
        choices: [
          { id: 'a', text: 'เริ่มกดหน้าอกทันทีก่อนเรียกใคร' },
          { id: 'b', text: 'ตรวจชีพจรนาน 30 วินาที' },
          { id: 'c', text: 'เรียก code blue / RRT พร้อมขอ defibrillator' },
          { id: 'd', text: 'ไปตามแพทย์เวรเอง' },
        ],
        correctId: 'c',
        explanation: 'IHCA: เมื่อจดจำเหตุได้ ต้อง activate code blue / RRT ทันที พร้อมขอ defibrillator การช่วยเหลือคนเดียวเสียเวลา' },
      { type: 'quiz', id: 'bls-1-q2',
        question: 'Universal Chain of Survival (2025) มีกี่ห่วง และห่วงสุดท้ายคืออะไร?',
        choices: [
          { id: 'a', text: '5 ห่วง — ห่วงสุดท้าย Post-cardiac arrest care' },
          { id: 'b', text: '6 ห่วง — ห่วงสุดท้าย Recovery & Survivorship' },
          { id: 'c', text: '4 ห่วง — ห่วงสุดท้าย Defibrillation' },
          { id: 'd', text: 'แยกตาม IHCA/OHCA ไม่มีจำนวนตายตัว' },
        ],
        correctId: 'b',
        explanation: 'Universal Chain 2025 มี 6 ห่วง รวม IHCA + OHCA เข้าด้วยกัน; ห่วงที่ 6 (Recovery & Survivorship) เป็นห่วงใหม่ที่เน้นฟื้นฟูระยะยาวและการสนับสนุนครอบครัว' },
      { type: 'quiz', id: 'bls-1-q3',
        question: 'การตรวจชีพจรในผู้ใหญ่ที่หมดสติควรใช้เวลานานสุดเท่าไร?',
        choices: [
          { id: 'a', text: 'ไม่เกิน 10 วินาที' },
          { id: 'b', text: '15–20 วินาที' },
          { id: 'c', text: '30 วินาที' },
          { id: 'd', text: '1 นาที' },
        ],
        correctId: 'a',
        explanation: 'ตรวจชีพจร carotid ไม่เกิน 10 วินาที — ถ้าไม่แน่ใจให้เริ่ม CPR ทันที' },
    ],
  },

  // ===================== บทที่ 2 =====================
  {
    id: 'bls-2',
    title: 'บทที่ 2: CPR คุณภาพสูงในผู้ใหญ่',
    description: 'อัตรา ความลึก การคืนตัวของหน้าอก และการลดการหยุดกดหน้าอก',
    estMinutes: 10,
    passingScore: 75,
    steps: [
      { type: 'read', heading: '5 องค์ประกอบของ High-Quality CPR',
        body: '1) อัตรา 100–120 ครั้ง/นาที\n2) ความลึก ในผู้ใหญ่ 5–6 ซม. (อย่างน้อย 5 ซม. ไม่เกิน 6 ซม.); เด็ก/ทารก ใช้เกณฑ์ 1/3 ของ AP diameter (เด็ก ~5 ซม., ทารก ~4 ซม.)\n3) ปล่อยให้หน้าอกคืนตัวเต็มที่ (full recoil)\n4) ลดการหยุดกดหน้าอกให้น้อยที่สุด — ทุก interruption < 10 วินาที; CCF (Chest Compression Fraction) เป้าหมาย > 80%\n5) ห้าม over-ventilation (หลังใส่ advanced airway: ผู้ใหญ่ 1 ครั้งทุก 6 วินาที = 10/นาที; เด็ก/ทารก 20–30/นาที — ดูบทที่ 7)' },
      { type: 'read', heading: '⚠ BLS-HCP: ต้องช่วยหายใจเสมอ',
        body: 'Hand-only CPR (กดอย่างเดียว) เป็นทางเลือกสำหรับ lay rescuer เท่านั้น\n• BLS-HCP ในโรงพยาบาลใช้ BVM (Ambu bag) + O₂ high flow เป็นหลัก — มีอุปกรณ์ครบ ใช้ได้เลย\n• Pocket mask / face shield = ทางเลือกสำรองกรณีไม่มี BVM หรือยังไม่ถึงตำแหน่ง\n• ไม่มี advanced airway (ผู้ใหญ่) → 30:2 (กด 30 ครั้ง บีบ Ambu 2 ครั้ง)\n• หลังใส่ ETT / SGA / LMA → continuous compressions + บีบ Ambu:\n   - ผู้ใหญ่: 1 ครั้งทุก 6 วินาที (10/min)\n   - เด็ก/ทารก: 1 ครั้งทุก 2–3 วินาที (20–30/min) ตาม AHA 2020+\n• บีบ Ambu 1 วินาทีต่อครั้ง พอเห็นหน้าอกขึ้น — อย่าบีบแรง/เร็ว (กัน gastric inflation)' },
      { type: 'read', heading: 'ตำแหน่งและท่าทาง',
        body: '• วางส้นมือบนกลางหน้าอก ครึ่งล่างของกระดูก sternum\n• ประสานมือทั้งสอง แขนเหยียดตรง ไหล่อยู่เหนือมือ ใช้น้ำหนักตัวกด\n• ผู้ป่วยควรอยู่บนพื้นแข็ง (backboard ถ้าอยู่บนเตียงนุ่ม)' },
      { type: 'quiz', id: 'bls-2-q1',
        question: 'อัตราการกดหน้าอกในผู้ใหญ่ตามแนวทาง ILCOR 2025 คือเท่าไร?',
        choices: [
          { id: 'a', text: '60–80 ครั้ง/นาที' },
          { id: 'b', text: '80–100 ครั้ง/นาที' },
          { id: 'c', text: '100–120 ครั้ง/นาที' },
          { id: 'd', text: 'มากกว่า 120 ครั้ง/นาที' },
        ],
        correctId: 'c',
        explanation: 'ILCOR 2025 แนะนำ 100–120 ครั้ง/นาที กดเร็วเกินจะกดได้ไม่ลึก กดช้าเกินจะได้ flow ไม่พอ' },
      { type: 'quiz', id: 'bls-2-q2',
        question: 'ความลึกในการกดหน้าอกในผู้ใหญ่ที่เหมาะสมคือ?',
        choices: [
          { id: 'a', text: '2–3 ซม.' },
          { id: 'b', text: '3–4 ซม.' },
          { id: 'c', text: '5–6 ซม.' },
          { id: 'd', text: 'มากกว่า 7 ซม.' },
        ],
        correctId: 'c',
        explanation: 'ผู้ใหญ่: อย่างน้อย 5 ซม. ไม่เกิน 6 ซม. — กดตื้นเกิน output ไม่พอ; กดลึกเกินเสี่ยง rib fracture (เกณฑ์ 1/3 AP diameter ใช้สำหรับเด็ก/ทารกเท่านั้น)' },
      { type: 'quiz', id: 'bls-2-q3',
        question: 'Chest Compression Fraction (CCF) เป้าหมายตามแนวทาง 2025 คือเท่าไร?',
        choices: [
          { id: 'a', text: '> 40%' },
          { id: 'b', text: '> 60%' },
          { id: 'c', text: '> 80%' },
          { id: 'd', text: '100%' },
        ],
        correctId: 'c',
        explanation: 'แนวทางปี 2025 ระบุ CCF > 80% เป็น quality benchmark — เวลาที่กดหน้าอกจริงเทียบกับเวลารวมของ resuscitation; สูงขึ้นสัมพันธ์กับ ROSC + survival' },
      { type: 'quiz', id: 'bls-2-q4',
        question: 'ทำไมต้องปล่อยให้หน้าอกคืนตัวเต็มที่ระหว่าง compression?',
        choices: [
          { id: 'a', text: 'เพื่อพักกล้ามเนื้อผู้กด' },
          { id: 'b', text: 'เพื่อให้เลือดไหลกลับเข้า heart ใน diastole (venous return)' },
          { id: 'c', text: 'เพื่อให้ผู้ป่วยหายใจเอง' },
          { id: 'd', text: 'ไม่มีผลทาง physiology' },
        ],
        correctId: 'b',
        explanation: 'Incomplete recoil → ลด venous return → ลด cardiac output ของ CPR อย่างมาก' },
      { type: 'quiz', id: 'bls-2-q5',
        question: 'BLS-HCP ทำ CPR แตกต่างจาก lay rescuer อย่างไร?',
        choices: [
          { id: 'a', text: 'BLS-HCP ใช้ hand-only CPR เหมือนกัน' },
          { id: 'b', text: 'BLS-HCP ต้องช่วยหายใจด้วย (30:2 หรือ 1 ครั้ง/6 วินาที หลัง advanced airway)' },
          { id: 'c', text: 'BLS-HCP ไม่ต้องกดหน้าอก' },
          { id: 'd', text: 'BLS-HCP ใช้ rate ต่างกัน' },
        ],
        correctId: 'b',
        explanation: 'Hand-only CPR = lay rescuer; BLS-HCP ต้องช่วยหายใจเสมอ — 30:2 (no advanced airway) หรือ 1 ครั้ง/6 วินาที (มี advanced airway)' },
    ],
  },

  // ===================== บทที่ 3 =====================
  {
    id: 'bls-3',
    title: 'บทที่ 3: การใช้ AED',
    description: 'การติดและใช้ Automated External Defibrillator อย่างปลอดภัยและมีประสิทธิภาพ',
    estMinutes: 7,
    passingScore: 75,
    steps: [
      { type: 'read', heading: '4 ขั้นตอนการใช้ AED',
        body: '1) เปิดเครื่อง — ฟังคำสั่งเสียง\n2) ติด pads ที่ตำแหน่งถูกต้อง\n3) ให้ AED วิเคราะห์ rhythm (ห้ามแตะผู้ป่วย)\n4) ถ้าแนะนำ shock — เคลียร์คนรอบ → กดปุ่ม shock → เริ่ม CPR ต่อทันที 2 นาที' },
      { type: 'read', heading: '⚠ BLS-HCP: ใช้ AED mode เท่านั้น',
        body: 'ใน scope ของ BLS-HCP ใช้ AED automated mode เท่านั้น\n• ไม่ต้องอ่าน rhythm strip / interpret VF/pVT/PEA/Asystole เอง\n• ไม่ต้องเลือก Joule manual — AED จัดการพลังงานให้อัตโนมัติ\n• ทำตามคำสั่งเสียง: "Shock advised" → shock; "No shock advised" → CPR ต่อ\n• Manual defibrillator + rhythm interpretation = ทักษะระดับ ACLS' },
      { type: 'read', heading: 'ตำแหน่ง pads',
        body: '• Anterolateral: pad 1 ใต้กระดูกไหปลาร้าขวา; pad 2 กลางสีข้างซ้าย ระดับ mid-axillary line (~ICS 5–6 ระดับเดียวกับ nipple)\n• Anteroposterior: กลางอกหน้า + กลางหลัง — เป็นทางเลือก equivalent กับ anterolateral; แนะนำเมื่อมี pacemaker/ICD หรือ pads ขนาดใหญ่ทับซ้อนกัน\n• ระยะห่างจาก pacemaker/ICD อย่างน้อย 2.5 ซม.' },
      { type: 'read', heading: 'สถานการณ์พิเศษ',
        body: '• Hairy chest: โกนเร็ว ๆ หรือใช้ pads สำรองดึงขนออก\n• Wet chest: เช็ดให้แห้งก่อนติด pads\n• Patch (ยา transdermal): ดึงออก เช็ดยาออกก่อน\n• ในน้ำ: ย้ายผู้ป่วยขึ้นแห้งก่อน\n• เด็ก < 8 ปี หรือน้ำหนัก < 25 กก.: ใช้ pediatric pads / dose attenuator ถ้ามี; ถ้าไม่มีใช้ผู้ใหญ่ได้' },
      { type: 'quiz', id: 'bls-3-q1',
        question: 'ทันทีหลัง shock ควรทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'ตรวจชีพจรทันที' },
          { id: 'b', text: 'เริ่มกดหน้าอกต่อทันที 2 นาที' },
          { id: 'c', text: 'รอให้ AED วิเคราะห์ซ้ำ' },
          { id: 'd', text: 'ใส่ advanced airway' },
        ],
        correctId: 'b',
        explanation: 'หลัง shock ต้องเริ่ม CPR ต่อ 2 นาทีทันที โดยไม่ตรวจชีพจร เพื่อรักษา perfusion' },
      { type: 'quiz', id: 'bls-3-q2',
        question: 'ใช้ AED ในเด็กอายุ < 8 ปี (หรือน้ำหนัก < 25 กก.) ควรใช้อะไร?',
        choices: [
          { id: 'a', text: 'ใช้ pads ผู้ใหญ่ตามปกติ' },
          { id: 'b', text: 'ใช้ pediatric pads / dose attenuator ถ้ามี (ถ้าไม่มีใช้ผู้ใหญ่ได้)' },
          { id: 'c', text: 'ห้ามใช้ AED ในเด็กทุกกรณี' },
          { id: 'd', text: 'รอ EMS มาเท่านั้น' },
        ],
        correctId: 'b',
        explanation: 'เด็ก < 8 ปี หรือ < 25 กก. ใช้ pediatric pads / attenuator ถ้ามี; ถ้าไม่มีให้ใช้ผู้ใหญ่ — defib เป็นชีวิต ห้ามชะลอ' },
      { type: 'quiz', id: 'bls-3-q3',
        question: 'ผู้ป่วย VF ที่มีหน้าอกเปียกน้ำ ควรทำอะไรก่อนติด AED pads?',
        choices: [
          { id: 'a', text: 'รอให้แห้งเอง' },
          { id: 'b', text: 'เช็ดหน้าอกให้แห้งอย่างรวดเร็ว' },
          { id: 'c', text: 'ห้ามใช้ AED' },
          { id: 'd', text: 'ใส่ glove เพิ่ม' },
        ],
        correctId: 'b',
        explanation: 'เช็ดให้แห้งเพื่อให้ pads ติดและ shock ผ่านได้ดี ห้ามรอ' },
      { type: 'quiz', id: 'bls-3-q4',
        question: 'ผู้ป่วยใส่ pacemaker อยู่ ต้องวาง pads อย่างไร?',
        choices: [
          { id: 'a', text: 'วางตรงบน pacemaker' },
          { id: 'b', text: 'ห่างจาก pacemaker อย่างน้อย 2.5 ซม.' },
          { id: 'c', text: 'ไม่ shock เลย' },
          { id: 'd', text: 'ปิด pacemaker ก่อน' },
        ],
        correctId: 'b',
        explanation: 'หลีกเลี่ยงตรง pacemaker เพื่อไม่ให้เครื่องเสียหาย แต่ต้อง shock ได้' },
      { type: 'quiz', id: 'bls-3-q5',
        question: 'เมื่อ AED บอก "No shock advised" ขั้นตอนถัดไปคืออะไร?',
        choices: [
          { id: 'a', text: 'ตรวจชีพจรนาน 30 วินาที' },
          { id: 'b', text: 'รอ AED วิเคราะห์ซ้ำเลย' },
          { id: 'c', text: 'เริ่มกดหน้าอกต่อทันที 2 นาที แล้วให้ AED วิเคราะห์ใหม่' },
          { id: 'd', text: 'ถอดแผ่นออกแล้วใส่ใหม่' },
        ],
        correctId: 'c',
        explanation: '"No shock advised" → CPR ต่อทันที 2 นาที (rhythm อาจเป็น PEA/Asystole หรือ ROSC — BLS ไม่ต้องแยก) AED จะวิเคราะห์รอบถัดไปอัตโนมัติ' },
      { type: 'quiz', id: 'bls-3-q6',
        question: 'BLS-HCP ใช้เครื่อง defibrillator แบบใด?',
        choices: [
          { id: 'a', text: 'Manual mode — อ่าน rhythm แล้วเลือก Joule เอง' },
          { id: 'b', text: 'AED / automated mode เท่านั้น' },
          { id: 'c', text: 'ใช้ได้ทุกแบบขึ้นกับว่าใครมาก่อน' },
          { id: 'd', text: 'ไม่ใช้ defibrillator' },
        ],
        correctId: 'b',
        explanation: 'BLS-HCP ใช้ AED mode (อัตโนมัติ) เท่านั้น — ไม่ต้องอ่าน rhythm strip หรือเลือก Joule เอง Manual defibrillation = ทักษะระดับ ACLS' },
    ],
  },

  // ===================== บทที่ 4 =====================
  {
    id: 'bls-1r',
    title: 'บทที่ 4: One-rescuer CPR',
    description: 'การช่วยเหลือคนเดียวก่อนทีมมาถึง — CAB sequence, ใช้ AED คนเดียว, ขอความช่วยเหลือด้วย speakerphone',
    estMinutes: 7,
    passingScore: 75,
    steps: [
      { type: 'read', heading: 'หลักการ One-rescuer BLS',
        body: '• ผู้ช่วยเหลือคนเดียว = บุคลากร/พลเรือนคนแรกที่พบเหตุ ก่อนทีม CPR/EMS มาถึง\n• เป้าหมาย: เริ่ม CPR + ขอความช่วยเหลือ + ใช้ AED ให้เร็วที่สุด โดยไม่เสียเวลากดหน้าอก\n• ใช้ speakerphone โทร 1669 / activate code blue พร้อมกดหน้าอกไปด้วยได้\n• อย่ารอความช่วยเหลือก่อนเริ่ม CPR — early CPR + early defib = survival' },
      { type: 'read', heading: 'ขั้นตอน CAB (Compression-Airway-Breathing)',
        body: '1) Scene safety + tap and shout ปลุก\n2) ไม่ตอบสนอง → เรียก EMS / code blue ผ่าน speakerphone + ขอ AED\n3) ตรวจการหายใจ + carotid pulse พร้อมกัน ไม่เกิน 10 วินาที\n4) ไม่มี pulse หรือไม่แน่ใจ → เริ่ม CPR 30:2 ทันที (อัตรา 100–120/min)\n5) ใช้ AED ทันทีที่มาถึง วิเคราะห์ → shock → CPR ต่อ\n6) ทำต่อจนทีมมาถึง / ROSC / หมดแรง' },
      { type: 'read', heading: 'การใช้ AED คนเดียว',
        body: '• ติด pads ระหว่างที่ยังกดหน้าอกอยู่ก็ได้ — ลดเวลา interrupt\n• หยุดกดเฉพาะตอน AED วิเคราะห์ rhythm (ห้ามแตะผู้ป่วย ~5–10 วินาที)\n• สั่งเคลียร์คนรอบ ๆ ระหว่าง analyze\n• หลัง shock → กลับมากดต่อทันที (ห้ามตรวจ pulse ก่อน)\n• ทุก 2 นาที AED จะ prompt วิเคราะห์ rhythm ซ้ำ' },
      { type: 'read', heading: 'เมื่อไหร่จึงหยุด CPR ได้',
        body: '• ROSC: หายใจ + มี pulse กลับมา → จัดท่า recovery (ดูบทที่ 5)\n• ทีม CPR / EMS มาถึงและรับช่วงต่อ\n• หมดแรง ไม่สามารถกดต่อได้\n• สถานการณ์ไม่ปลอดภัย (เพลิงไหม้ น้ำท่วม)\n• แพทย์ประกาศยุติการช่วยเหลือ' },
      { type: 'quiz', id: 'bls-1r-q1',
        question: 'ผู้ช่วยเหลือคนเดียวพบผู้ป่วยหมดสติริมถนน — ขั้นตอนถูกต้องคือ?',
        choices: [
          { id: 'a', text: 'วิ่งไปตามคนช่วยก่อน แล้วค่อยกลับมาทำ CPR' },
          { id: 'b', text: 'ใช้ speakerphone เรียก 1669 พร้อมประเมิน + เริ่ม CPR' },
          { id: 'c', text: 'ตรวจชีพจร 30 วินาทีให้แน่ใจ' },
          { id: 'd', text: 'รอ ambulance ก่อนเริ่มทำอะไร' },
        ],
        correctId: 'b',
        explanation: 'Speakerphone ทำให้เรียก EMS + ทำ CPR ได้พร้อมกัน — early CPR สำคัญต่อ survival, อย่าทิ้งผู้ป่วยไปตามคน' },
      { type: 'quiz', id: 'bls-1r-q2',
        question: 'อัตราส่วน Compression:Ventilation ของ one-rescuer ในผู้ใหญ่คือ?',
        choices: [
          { id: 'a', text: '15:2' }, { id: 'b', text: '30:2' },
          { id: 'c', text: '50:2' }, { id: 'd', text: 'continuous compression อย่างเดียว' },
        ],
        correctId: 'b',
        explanation: '1-rescuer: 30:2 (ทั้งผู้ใหญ่/เด็ก/ทารก); 2-rescuer ในเด็ก/ทารก: 15:2' },
      { type: 'quiz', id: 'bls-1r-q3',
        question: 'ผู้ช่วยเหลือคนเดียวกดหน้าอกอยู่ AED มาถึง — ทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'กดต่ออีก 5 นาทีค่อยใส่ AED' },
          { id: 'b', text: 'ติด pads ระหว่างที่ยังกดอยู่ แล้วให้ AED วิเคราะห์' },
          { id: 'c', text: 'รอจน rhythm กลับมาเอง' },
          { id: 'd', text: 'ใส่ AED แล้วหยุด CPR ทั้งหมด' },
        ],
        correctId: 'b',
        explanation: 'ติด pads ระหว่างกดเพื่อลดเวลา interrupt — early defib เพิ่ม survival อย่างมาก' },
      { type: 'quiz', id: 'bls-1r-q4',
        question: 'ผู้ช่วยเหลือคนเดียวกดจนเหนื่อยมาก — ทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'หยุดทุกอย่าง รอ EMS' },
          { id: 'b', text: 'กดต่อแม้คุณภาพลด — ทำจนคนช่วยมาถึง หรือหมดแรงจริง ๆ' },
          { id: 'c', text: 'พัก 5 นาที แล้วค่อยกดใหม่' },
          { id: 'd', text: 'นวดท้องแทน' },
        ],
        correctId: 'b',
        explanation: 'การ interrupt CPR ↓ coronary perfusion → ↓ ROSC chances; กดต่อแม้คุณภาพลดยังดีกว่าหยุด' },
    ],
  },

  // ===================== บทที่ 5 =====================
  {
    id: 'bls-4',
    title: 'บทที่ 5: 2-rescuer CPR, Team Dynamics และ ROSC',
    description: 'การทำงานเป็นทีม สลับคนกด closed-loop communication และการดูแลหลัง ROSC',
    estMinutes: 10,
    passingScore: 75,
    steps: [
      { type: 'read', heading: 'อัตราส่วน Compression : Ventilation',
        body: '• ไม่มี advanced airway:\n   - ผู้ใหญ่: 30:2 (ทั้ง 1 และ 2 ผู้ช่วยเหลือ)\n   - เด็ก/ทารก: 30:2 (1 ผู้ช่วยเหลือ); 15:2 (2 ผู้ช่วยเหลือ HCP)\n• มี advanced airway (ETT/SGA/LMA): continuous compressions ไม่ pause; ventilation ผู้ใหญ่ 10/min (1 ครั้ง/6 วิ), เด็ก/ทารก 20–30/min (1 ครั้ง/2–3 วิ)' },
      { type: 'read', heading: 'การสลับคนกด',
        body: '• สลับทุก 2 นาที (หรือเร็วกว่าถ้าเหนื่อย) เพื่อรักษาคุณภาพ\n• สลับให้เร็ว ไม่หยุดเกิน 5 วินาที\n• ใช้จังหวะ "rhythm check" เป็นโอกาสสลับ' },
      { type: 'read', heading: 'หลัก 6 ข้อของ Team Dynamics',
        body: '1) Clear Roles — ทุกคนรู้บทบาทตัวเองและประกาศหน้าที่ตั้งแต่เริ่ม (Leader, Compressor, Airway, Defib operator, IV/Drug, Recorder)\n2) Knowing Limitations — ขอความช่วยเหลือทันทีเมื่อเกินขอบเขต ไม่รอจนเกิดความผิดพลาด\n3) Constructive Intervention — ทักท้วงอย่างสร้างสรรค์ เช่น "หยุดกดเกิน 10 วินาทีแล้ว กลับมากดก่อน"\n4) Knowledge Sharing — แบ่งปันข้อมูลและสิ่งที่สังเกตเห็นต่อเนื่อง (เช่น แนวโน้ม PEtCO₂)\n5) Closed-loop Communication — ผู้สั่งระบุชื่อ+คำสั่ง → ผู้รับทวน → รายงานเมื่อทำเสร็จ → ผู้สั่งยืนยัน\n6) Clear Message — เสียงดัง ชัด ระบุปริมาณ วิธีให้ และเวลา เช่น "Epinephrine 1 mg IV ตอนนี้"' },
      { type: 'read', heading: 'Closed-loop Communication — ตัวอย่าง',
        body: '• Leader: "คุณ A ขอ epinephrine 1 mg IV ตอนนี้"\n• ผู้รับ: "กำลังเตรียม epinephrine 1 mg IV ครับ"\n• เมื่อทำเสร็จ: "ให้ epinephrine 1 mg IV แล้ว เวลา 14:32"\n• Leader ยืนยัน: "รับทราบ ขอบคุณ"\n• ลด miscommunication และ documentation ผิดใน high-stress environment' },
      { type: 'read', heading: 'CPR Coach — บทบาทใหม่ในทีมสมรรถนะสูง',
        body: 'CPR Coach เป็นบทบาทเสริมที่เน้นรักษาคุณภาพการกดหน้าอกตลอด resuscitation:\n• เฝ้าดูความลึก อัตรา full recoil ช่วงหยุดกดหน้าอก และความล้าของผู้กด\n• แจ้งสลับ Compressor ทันทีเมื่อคุณภาพลดลง (ไม่จำเป็นต้องรอครบ 2 นาที)\n• คุม interruption ไม่เกิน 10 วินาที — coach แบบ real-time\n• อาจทำควบคู่กับ Recorder หรือแยกตำแหน่ง ขึ้นกับจำนวนบุคลากร\n• Coach ไม่ใช่ผู้ควบคุมทีมแทน Team Leader — focus เฉพาะคุณภาพ CPR' },
      { type: 'quiz', id: 'bls-4-q1',
        question: 'ในการทำ CPR ผู้ใหญ่ที่ใส่ advanced airway แล้ว ควร ventilate อย่างไร?',
        choices: [
          { id: 'a', text: '30:2 ตามปกติ' },
          { id: 'b', text: '1 ครั้งทุก 6 วินาที (10 ครั้ง/นาที) ร่วมกับ continuous compressions' },
          { id: 'c', text: '1 ครั้งทุก 3 วินาที' },
          { id: 'd', text: 'ไม่ต้อง ventilate' },
        ],
        correctId: 'b',
        explanation: 'หลังใส่ advanced airway: continuous compressions + 1 breath ทุก 6 วินาที ไม่ pause' },
      { type: 'quiz', id: 'bls-4-q2',
        question: 'ควรสลับคนกดหน้าอกบ่อยแค่ไหน?',
        choices: [
          { id: 'a', text: 'ทุก 30 วินาที' },
          { id: 'b', text: 'ทุก 2 นาที หรือเร็วกว่าถ้าเหนื่อย' },
          { id: 'c', text: 'ทุก 10 นาที' },
          { id: 'd', text: 'ไม่ต้องสลับ' },
        ],
        correctId: 'b',
        explanation: 'สลับทุก 2 นาทีเพื่อรักษาคุณภาพการกด เหนื่อยเร็วกว่าที่คิด' },
      { type: 'quiz', id: 'bls-4-q3',
        question: 'Closed-loop communication คืออะไร?',
        choices: [
          { id: 'a', text: 'การสั่งงานต่อกันเป็นทอด ๆ' },
          { id: 'b', text: 'การที่ leader สั่ง → ผู้รับยืนยัน → ทำเสร็จรายงานกลับ' },
          { id: 'c', text: 'การปิดประตูห้องระหว่างทำ CPR' },
          { id: 'd', text: 'การส่งสัญญาณมือ' },
        ],
        correctId: 'b',
        explanation: 'Closed-loop: สั่ง → ยืนยัน → รายงานกลับ ลด error ใน high-stress environment' },
      { type: 'quiz', id: 'bls-4-q4',
        question: 'ตามแนวทางปี 2025 ทุกการหยุดกดหน้าอก (interruption) ไม่ควรเกินกี่วินาที?',
        choices: [
          { id: 'a', text: '5 วินาที' },
          { id: 'b', text: '10 วินาที' },
          { id: 'c', text: '20 วินาที' },
          { id: 'd', text: '30 วินาที' },
        ],
        correctId: 'b',
        explanation: 'แนวทาง 2025: limit interruption ทุกประเภท (สลับคน, AED วิเคราะห์, intubation, pulse check) ไม่เกิน 10 วินาที — เป้าฝึกของการสลับคนเองคือใน 5 วินาที แต่ formal limit ตามมาตรฐานคือ 10 วินาที' },
      { type: 'quiz', id: 'bls-4-q6',
        question: 'CPR Coach มีหน้าที่หลักคืออะไร?',
        choices: [
          { id: 'a', text: 'ควบคุมทีมแทน Team Leader' },
          { id: 'b', text: 'เฝ้าดูคุณภาพการกดหน้าอก + แจ้งสลับคนเมื่อคุณภาพลด + คุม interruption ≤ 10 วิ' },
          { id: 'c', text: 'ตัดสินใจให้ยา' },
          { id: 'd', text: 'ใส่ advanced airway' },
        ],
        correctId: 'b',
        explanation: 'CPR Coach เป็นบทบาทเสริมที่ focus เฉพาะคุณภาพ CPR — เฝ้าดูความลึก, อัตรา, full recoil, ความล้าของผู้กด และคุมเวลาหยุดกด ไม่ใช่ผู้ควบคุมทีมแทน Team Leader' },
      { type: 'quiz', id: 'bls-4-q7',
        question: 'หลัก 6 ข้อของ Team Dynamics ประกอบด้วยอะไรบ้าง?',
        choices: [
          { id: 'a', text: 'Closed-loop + Clear Message อย่างเดียว' },
          { id: 'b', text: 'Clear Roles, Knowing Limitations, Constructive Intervention, Knowledge Sharing, Closed-loop, Clear Message' },
          { id: 'c', text: 'SBAR 4 ขั้น + Debrief' },
          { id: 'd', text: 'เริ่ม CPR เร็ว + ช็อกเร็ว' },
        ],
        correctId: 'b',
        explanation: 'หลัก 6 ข้อ: Clear Roles · Knowing Limitations · Constructive Intervention · Knowledge Sharing · Closed-loop Communication · Clear Message' },
      { type: 'read', heading: 'หลัง ROSC: การดูแลเบื้องต้น',
        body: '• ตรวจชีพจร + การหายใจอีกครั้ง — มี pulse กลับมาแล้ว = Return of Spontaneous Circulation (ROSC)\n• ถ้าหายใจเองได้ปกติ แต่ยังไม่รู้สึกตัว → จัดท่า Recovery position ป้องกัน aspiration\n• ถ้าหายใจไม่พอ → rescue breath: ผู้ใหญ่ 1 ครั้งทุก 6 วินาที (10/min); เด็ก/ทารก 1 ครั้งทุก 2–3 วินาที (20–30/min)\n• Monitor ใกล้ชิด — re-arrest มีโอกาสสูงในช่วงแรก\n• ห้ามถอด pads/ปิดเครื่อง AED จนกว่าจะส่งต่อ — re-arrest จะได้ shock ได้ทันที\n• เรียก ALS / ICU team รับช่วงต่อสำหรับ post-cardiac arrest care' },
      { type: 'read', heading: 'Recovery Position',
        body: '• ใช้กับผู้ป่วยที่หมดสติแต่หายใจปกติ + มี pulse (เช่น หลัง ROSC, opioid overdose ที่หายใจกลับ)\n• พลิกตัวตะแคงข้าง — มือล่างหนุนใต้แก้ม, คางเชิดขึ้นเล็กน้อยให้ airway โล่ง\n• เข่าบนงอ ขัดไว้ไม่ให้พลิกหงาย\n• ห้ามใช้ถ้าสงสัย spinal injury (อุบัติเหตุ, ตกที่สูง) — เปิด airway ด้วย jaw thrust แทน\n• ตรวจ airway + breathing ต่อเนื่อง ถ้าหยุดหายใจซ้ำ → เริ่ม CPR ทันที' },
      { type: 'quiz', id: 'bls-4-q5',
        question: 'หลัง ROSC ผู้ป่วยหายใจเองได้ปกติ แต่ยังไม่รู้สึกตัว ทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'กดหน้าอกต่อเพื่อความปลอดภัย' },
          { id: 'b', text: 'จัดท่า Recovery position + monitor + รอ ALS' },
          { id: 'c', text: 'ปิด AED แล้วถอด pads ออกทันที' },
          { id: 'd', text: 'ปลุกด้วยการตบหน้าและน้ำเย็น' },
        ],
        correctId: 'b',
        explanation: 'ROSC + หายใจปกติ + ไม่รู้สึกตัว → Recovery position ป้องกัน aspiration + monitor (re-arrest risk สูง) + ขอ ALS; ห้ามถอด AED จนส่งต่อเสร็จ' },
    ],
  },

  // ===================== บทที่ 6 =====================
  {
    id: 'bls-5',
    title: 'บทที่ 6: BLS ในโรงพยาบาล — Defib ใน AED Mode',
    description: 'ในโรงพยาบาลใช้ monitor/defibrillator แทน AED stand-alone — BLS provider ใช้ AED mode เพื่อ shock ได้ทันที',
    estMinutes: 7,
    passingScore: 75,
    steps: [
      { type: 'read', heading: 'ทำไม BLS ในโรงพยาบาลต่างจากนอก',
        body: '• นอก รพ.: ใช้ AED stand-alone (เครื่องเล็ก คำสั่งเสียง ทำงาน mode เดียว)\n• ใน รพ.: ใช้ monitor/defibrillator (Philips HeartStart, Zoll R/X, Lifepak 15/20, Mindray) — เครื่องเดียวกันที่ ALS team จะใช้\n• เครื่องในโรงพยาบาลส่วนใหญ่มี 2 modes: AED mode (สำหรับ BLS provider) + Manual mode (สำหรับ ALS)\n• ข้อดี: BLS provider ที่มาถึงก่อน shock ได้ทันที ไม่ต้องรอ ALS team ตีความ rhythm' },
      { type: 'read', heading: 'ขั้นตอนใช้ Defib ใน AED Mode',
        body: '1) เปิดเครื่อง → เลือก AED mode (ปุ่ม / สวิตช์ / เมนู ขึ้นกับรุ่น)\n2) ติด pads — anterolateral (ใต้ไหปลาร้าขวา + กลางสีข้างซ้าย ระดับ mid-axillary line) หรือ AP\n3) เครื่องวิเคราะห์ rhythm — ห้ามแตะผู้ป่วย (interruption ≤ 10 วินาที)\n4) ถ้า "shock advised": เคลียร์คนรอบ → กด shock → CPR ต่อทันที 2 นาที\n5) ถ้า "no shock advised": CPR ต่อ 2 นาที (PEA/asystole)\n6) เครื่องจะวิเคราะห์ซ้ำทุก 2 นาทีอัตโนมัติ' },
      { type: 'read', heading: 'ความแตกต่างจาก AED Stand-alone',
        body: '• Defib + monitor: ใหญ่กว่า มี ECG display + IV port + pacing + sync cardioversion (สำหรับ ALS)\n• AED stand-alone: เล็ก พกพา ทำงาน mode เดียว\n• AED mode บน defib ทำงาน flow เหมือน AED ปกติ — คำสั่งเสียงเหมือนกัน\n• ข้อระวัง: pads ของ defib อาจมีหลายแบบ (peds vs adult) — เช็คก่อนติด' },
      { type: 'read', heading: 'การส่งต่อ BLS → ALS Team',
        body: '• BLS provider เริ่ม AED mode ทันทีเมื่อเครื่องมาถึง — ห้ามรอ ALS\n• เมื่อ ALS team มา: หัวหน้าทีมจะ switch ไป manual mode เพื่ออ่าน rhythm ละเอียดขึ้น, ใช้ sync cardioversion / pacing\n• Hand-off ที่ดี: รายงาน (1) เวลาเริ่ม CPR (2) จำนวน shock + เวลา (3) rhythm ที่เห็น (4) ยาที่ให้ไปแล้ว — ใช้ closed-loop' },
      { type: 'read', heading: 'Vascular Access — IV ก่อน, IO ถ้าไม่สำเร็จ',
        body: 'BLS provider ที่ช่วย ALS เปิดทางให้ยา ควรเข้าใจหลัก:\n• แนวทาง 2025: เริ่ม peripheral IV ก่อน — ถ้าไม่สำเร็จใน 1–2 ครั้ง เปลี่ยนเป็น IO (intraosseous) ทันที\n• Central line ไม่จำเป็นระหว่าง resuscitation — เพิ่มความเสี่ยงและทำให้ CPR หยุดชะงัก\n• ETT route สำหรับให้ยา **ไม่แนะนำแล้ว** ใน 2025 — เปลี่ยนจากแนวทางเก่า\n• เทคนิคให้ยาทาง peripheral: bolus → flush 20 mL → ยกแขน/ขา 10–20 วินาที (ยาใช้เวลา 1–2 นาทีเข้า central circulation)' },
      { type: 'quiz', id: 'bls-5-q1',
        question: 'ทำไมในโรงพยาบาลถึงใช้ defib ที่มี AED mode แทน AED stand-alone?',
        choices: [
          { id: 'a', text: 'AED stand-alone ผิดกฎหมายในโรงพยาบาล' },
          { id: 'b', text: 'เพราะเป็นเครื่องเดียวกันที่ ALS team ใช้ — BLS shock ก่อน ส่งต่อ manual mode ได้เลย' },
          { id: 'c', text: 'AED stand-alone shock แรงกว่า' },
          { id: 'd', text: 'ไม่ต่างกัน เลือกอันไหนก็ได้' },
        ],
        correctId: 'b',
        explanation: 'เครื่องในโรงพยาบาลเป็น defib/monitor ที่มี AED mode สำหรับ BLS + manual mode สำหรับ ALS — ใช้ต่อเนื่องไม่ต้องเปลี่ยนเครื่อง' },
      { type: 'quiz', id: 'bls-5-q2',
        question: 'BLS provider นำ defib มาถึง — ขั้นตอนแรกหลังเปิดเครื่องคืออะไร?',
        choices: [
          { id: 'a', text: 'อ่าน rhythm บนจอแล้วเลือก energy' },
          { id: 'b', text: 'เลือก AED mode แล้วติด pads' },
          { id: 'c', text: 'รอ ALS team มาถึงก่อน' },
          { id: 'd', text: 'ใส่ IV ก่อน' },
        ],
        correctId: 'b',
        explanation: 'BLS provider ใช้ AED mode (ไม่ได้รับการสอนอ่าน rhythm) — เลือก mode → ติด pads → ให้เครื่องวิเคราะห์' },
      { type: 'quiz', id: 'bls-5-q3',
        question: 'หลังเครื่องในโหมด AED แนะนำ "shock advised" และ shock ไปแล้ว ทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'ตรวจชีพจรทันที' },
          { id: 'b', text: 'รอเครื่องวิเคราะห์ rhythm อีกครั้ง' },
          { id: 'c', text: 'เริ่ม CPR ต่อทันที 2 นาที' },
          { id: 'd', text: 'Switch ไป manual mode ทันที' },
        ],
        correctId: 'c',
        explanation: 'AED mode ใช้ flow เดียวกับ AED ปกติ: หลัง shock → CPR ต่อ 2 นาที ห้ามตรวจชีพจร' },
      { type: 'quiz', id: 'bls-5-q4',
        question: 'ALS team มาถึงระหว่าง code — ควรทำอย่างไรกับเครื่อง defib?',
        choices: [
          { id: 'a', text: 'ถอด pads ออก เปลี่ยนเครื่องใหม่' },
          { id: 'b', text: 'BLS provider continue ใน AED mode ตลอด' },
          { id: 'c', text: 'หัวหน้า ALS switch ไป manual mode + รับ hand-off (เวลา shock, rhythm, ยา)' },
          { id: 'd', text: 'ปิดเครื่องก่อนเปลี่ยน mode' },
        ],
        correctId: 'c',
        explanation: 'ALS team รับ hand-off แล้ว switch manual mode เพื่ออ่าน rhythm + ใช้ sync/pacing — pads เดิม ไม่ต้องถอด' },
    ],
  },

  // ===================== บทที่ 7 =====================
  {
    id: 'bls-6',
    title: 'บทที่ 7: CPR ในทารก (< 1 ปี)',
    description: 'เทคนิคพิเศษสำหรับทารก: 2-finger / 2-thumb encircling, brachial pulse',
    estMinutes: 7,
    passingScore: 75,
    steps: [
      { type: 'read', heading: 'การตรวจชีพจรในทารก',
        body: 'ใช้ brachial pulse (inner upper arm) เป็นมาตรฐาน; femoral pulse ใช้แทนได้ — carotid ยากในทารกเพราะคอสั้น ตรวจไม่เกิน 10 วินาที\nHR < 60 + poor perfusion (แม้ให้ ventilation/O₂ เพียงพอแล้ว) → start compressions ทันที' },
      { type: 'read', heading: 'เทคนิคการกดหน้าอก',
        body: '• 1 ผู้ช่วยเหลือ: 2-finger technique (2 นิ้วบน sternum ใต้เส้น nipple)\n• 2 ผู้ช่วยเหลือ (HCP): 2-thumb encircling technique (โอบรอบหน้าอก ใช้นิ้วโป้งกด) — ให้ output ดีกว่า\n• ความลึก ~ 4 ซม. หรือ 1/3 ของ AP diameter\n• อัตรา 100–120 ครั้ง/นาที' },
      { type: 'read', heading: 'อัตราส่วน Compression : Ventilation',
        body: '• 1-rescuer: 30:2\n• 2-rescuer (HCP): 15:2\n• AED < 1 ปี: ใช้ manual defibrillator ถ้ามี; ถ้าไม่มีใช้ AED with pediatric attenuator; ถ้าไม่มีใช้ adult AED ได้' },
      { type: 'quiz', id: 'bls-6-q1',
        question: 'ตรวจชีพจรในทารกใช้ตำแหน่งใด?',
        choices: [
          { id: 'a', text: 'Carotid' },
          { id: 'b', text: 'Radial' },
          { id: 'c', text: 'Brachial' },
          { id: 'd', text: 'Femoral หรือ Brachial' },
        ],
        correctId: 'd',
        explanation: 'Brachial pulse เป็นมาตรฐาน, femoral ก็ใช้ได้ — carotid ยากในทารกเพราะคอสั้น' },
      { type: 'quiz', id: 'bls-6-q2',
        question: 'ใน 2-rescuer CPR ของทารก เทคนิคไหนแนะนำ?',
        choices: [
          { id: 'a', text: '1-hand technique' },
          { id: 'b', text: '2-finger technique' },
          { id: 'c', text: '2-thumb encircling technique' },
          { id: 'd', text: 'Heel of hand (เหมือนผู้ใหญ่)' },
        ],
        correctId: 'c',
        explanation: '2-thumb encircling ให้ output และ depth ที่ดีกว่า 2-finger ใน 2-rescuer setting' },
      { type: 'quiz', id: 'bls-6-q3',
        question: 'ความลึกของการกดหน้าอกในทารกคือ?',
        choices: [
          { id: 'a', text: '~2 ซม.' },
          { id: 'b', text: '~4 ซม. หรือ 1/3 ของ AP diameter' },
          { id: 'c', text: '~5–6 ซม.' },
          { id: 'd', text: 'ลึกเท่ากับผู้ใหญ่' },
        ],
        correctId: 'b',
        explanation: 'ทารก: 1/3 ของ AP diameter ~ 4 ซม.' },
      { type: 'quiz', id: 'bls-6-q4',
        question: 'อัตราส่วน compression:ventilation ในทารก 1-rescuer คือ?',
        choices: [
          { id: 'a', text: '5:1' },
          { id: 'b', text: '15:2' },
          { id: 'c', text: '30:2' },
          { id: 'd', text: '10:1' },
        ],
        correctId: 'c',
        explanation: '1-rescuer: 30:2 (ทุกช่วงอายุ); 2-rescuer ในเด็ก/ทารก: 15:2' },
    ],
  },

  // ===================== บทที่ 8 =====================
  {
    id: 'bls-7',
    title: 'บทที่ 8: ทางเดินหายใจอุดกั้น (FBAO)',
    description: 'Foreign Body Airway Obstruction ในผู้ใหญ่ เด็ก ทารก',
    estMinutes: 6,
    passingScore: 75,
    steps: [
      { type: 'read', heading: 'การประเมิน FBAO',
        body: 'Mild obstruction: ไอได้ พูดได้ → ให้ไอเอง อย่ารบกวน\nSevere obstruction: ไอไม่ออก, พูดไม่ได้, จับคอ, หน้าเขียว → ต้องช่วยทันที' },
      { type: 'read', heading: 'ผู้ใหญ่ + เด็ก ≥ 1 ปี (รู้สึกตัว)',
        body: '• ILCOR 2025: 5 back blows สลับกับ 5 abdominal thrusts (Heimlich) จนกว่าสิ่งของจะออก หรือผู้ป่วยหมดสติ\n• Back blows: ก้มตัวผู้ป่วยไปข้างหน้า ใช้ส้นมือตบกลางสะบักแรง 5 ครั้ง\n• Abdominal thrusts: ยืนข้างหลัง โอบเอว วางกำปั้นเหนือสะดือ ใต้ xiphoid กระตุกขึ้น-เข้าใน 5 ครั้ง\n• หญิงตั้งครรภ์ระยะท้าย / อ้วนมาก: ใช้ chest thrusts แทน abdominal thrusts (back blows ทำได้ปกติ)' },
      { type: 'read', heading: 'ทารก < 1 ปี (รู้สึกตัว)',
        body: '• ห้าม abdominal thrust (เสี่ยง liver injury)\n• Back blows 5 ครั้ง (วางคว่ำหน้าบนแขน หัวต่ำ ตบกลางสะบัก) สลับกับ chest thrusts 5 ครั้ง\n• ตำแหน่ง chest thrusts: 2 นิ้วที่ครึ่งล่างของ sternum (ตำแหน่งเดียวกับ CPR ทารก)\n• ทำซ้ำจนสิ่งของออก' },
      { type: 'read', heading: 'ผู้ป่วยหมดสติ',
        body: '• เริ่ม CPR ทันที (ไม่ตรวจ pulse)\n• ก่อนให้ breath แต่ละครั้ง ดูในปาก ถ้าเห็นสิ่งของให้เอาออก\n• ห้าม blind finger sweep ในทุกช่วงวัย (ทั้งผู้ใหญ่ เด็ก ทารก) — เสี่ยงดันสิ่งของเข้าลึก / บาดเจ็บ' },
      { type: 'quiz', id: 'bls-7-q1',
        question: 'ผู้ใหญ่สำลักอาหาร พูดไม่ได้ จับคอ — ทำอะไรตามแนวทาง ILCOR 2025?',
        choices: [
          { id: 'a', text: 'รอให้ไอเอง' },
          { id: 'b', text: '5 back blows สลับกับ 5 abdominal thrusts (Heimlich)' },
          { id: 'c', text: 'ดื่มน้ำ' },
          { id: 'd', text: 'ฉีดอะดรีนาลีน' },
        ],
        correctId: 'b',
        explanation: 'ILCOR 2025: severe FBAO ใน adult/เด็ก ≥ 1 ปี ใช้ back blows สลับ abdominal thrusts (ครั้งละ 5) จนกว่าสิ่งของออกหรือผู้ป่วยหมดสติ' },
      { type: 'quiz', id: 'bls-7-q2',
        question: 'ทารก (< 1 ปี) สำลัก รู้สึกตัว ทำอะไร?',
        choices: [
          { id: 'a', text: 'Abdominal thrust 5 ครั้ง' },
          { id: 'b', text: 'Back blows 5 ครั้ง สลับ chest thrusts 5 ครั้ง' },
          { id: 'c', text: 'เริ่ม CPR ทันที' },
          { id: 'd', text: 'ฉีดน้ำเข้าจมูก' },
        ],
        correctId: 'b',
        explanation: 'ทารกใช้ back blows + chest thrusts (ห้าม abdominal thrust เสี่ยง liver injury)' },
      { type: 'quiz', id: 'bls-7-q3',
        question: 'หญิงตั้งครรภ์ไตรมาส 3 สำลัก พูดไม่ได้ ควรทำอะไร?',
        choices: [
          { id: 'a', text: 'Abdominal thrusts ตามปกติ' },
          { id: 'b', text: 'Chest thrusts แทน abdominal thrusts' },
          { id: 'c', text: 'Back blows อย่างเดียว' },
          { id: 'd', text: 'ทำ CPR เลย' },
        ],
        correctId: 'b',
        explanation: 'ครรภ์แก่ / อ้วนมาก: chest thrusts แทน abdominal เพื่อไม่กระทบมดลูก' },
      { type: 'quiz', id: 'bls-7-q4',
        question: 'ผู้ป่วย FBAO หมดสติแล้ว ทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'Abdominal thrusts ต่อ' },
          { id: 'b', text: 'เริ่ม CPR ทันที และดูในปากก่อนแต่ละ breath' },
          { id: 'c', text: 'รอ EMS' },
          { id: 'd', text: 'ทำ blind finger sweep' },
        ],
        correctId: 'b',
        explanation: 'หมดสติ → เริ่ม CPR; ดูในปากก่อนแต่ละ breath ถ้าเห็นสิ่งของเอาออก ห้าม blind finger sweep' },
    ],
  },

];

function deriveLesson(l) {
  const sections = l.steps.filter(s => s.type === 'read').map(s => ({ heading: s.heading, body: s.body }));
  const quiz = l.steps.filter(s => s.type === 'quiz').map(s => ({
    id: s.id,
    question: s.question,
    choices: s.choices,
    correctId: s.correctId,
    explanation: s.explanation,
  }));
  return { ...l, sections, quiz, videos: lessonVideos[l.id] ?? [] };
}

export const preCourseLessons = lessonDefs.map(deriveLesson);

export function findLessonById(id) {
  return preCourseLessons.find(l => l.id === id) || null;
}

export function getLessonStepCount(lesson) {
  return lesson?.steps?.length ?? 0;
}

export function getLessonQuizCount(lesson) {
  return lesson?.quiz?.length ?? 0;
}
