// BLS-HCP Post-test Set B — 23 questions (AHA BLS-HCP 2020 + TRC)
// Distribution: HQ-CPR 5, AED 3, team/2-rescuer 3, in-hospital-defib 4, infant 4, choking 3, chain 1
// คำถามต่างจาก Set A ครอบคลุม topic เดียวกัน
// ต้องผ่าน medical review โดยแพทย์ EM/ICU ก่อนปล่อย production

export const setB = {
  id: 'bls-set-b',
  title: 'ชุด B',
  questions: [
    // ---- Chain ----
    { id: 'bls-b-1', topic: 'chain',
      question: 'พบคนหมดสติริมถนน ไม่ตอบสนอง สิ่งแรกที่ทำคือ?',
      choices: [
        { id: 'a', text: 'เริ่ม CPR ทันที' },
        { id: 'b', text: 'ดู scene safety แล้วเรียก EMS 1669 (speakerphone)' },
        { id: 'c', text: 'ตามเจ้าหน้าที่' },
        { id: 'd', text: 'หยุดรถ' },
      ],
      correctId: 'b',
      explanation: 'OHCA: scene safety + เรียก EMS (1669) ก่อน ใช้ speakerphone จะได้ทำ CPR ได้' },

    // ---- High-Quality CPR (5) ----
    { id: 'bls-b-2', topic: 'high-quality-cpr',
      question: 'ตำแหน่งวางมือกดหน้าอกผู้ใหญ่ที่ถูกต้องคือ?',
      choices: [
        { id: 'a', text: 'กลาง sternum ครึ่งบน' },
        { id: 'b', text: 'ครึ่งล่างของ sternum กลางอก' },
        { id: 'c', text: 'ปลาย xiphoid' },
        { id: 'd', text: 'ด้านซ้ายของ sternum' },
      ],
      correctId: 'b', explanation: 'ครึ่งล่างของ sternum กลางอก ห้ามกดตรง xiphoid' },
    { id: 'bls-b-3', topic: 'high-quality-cpr',
      question: 'ถ้ากดหน้าอกเร็วเกิน 120/min จะเกิดอะไร?',
      choices: [
        { id: 'a', text: 'Cardiac output ดีขึ้น' },
        { id: 'b', text: 'ความลึกการกดมักไม่พอ' },
        { id: 'c', text: 'ไม่มีผล' },
        { id: 'd', text: 'AED ทำงานเร็วขึ้น' },
      ],
      correctId: 'b', explanation: 'กดเร็วเกิน → depth ไม่พอ + incomplete recoil' },
    { id: 'bls-b-4', topic: 'high-quality-cpr',
      question: 'ผู้ป่วยอยู่บนเตียงนุ่ม ควรทำอะไรก่อน CPR?',
      choices: [
        { id: 'a', text: 'กดบนเตียง' },
        { id: 'b', text: 'ใส่ backboard / ย้ายลงพื้นแข็ง' },
        { id: 'c', text: 'พลิกผู้ป่วยตะแคง' },
        { id: 'd', text: 'รอ EMS' },
      ],
      correctId: 'b', explanation: 'พื้นนุ่มลด effective depth → ใส่ backboard' },
    { id: 'bls-b-5', topic: 'high-quality-cpr',
      question: 'การ over-ventilation มีผลเสียอย่างไร?',
      choices: [
        { id: 'a', text: 'เพิ่ม cardiac output' },
        { id: 'b', text: 'เพิ่ม intrathoracic pressure → ลด venous return → ลด CO' },
        { id: 'c', text: 'ไม่มีผล' },
        { id: 'd', text: 'ช่วยให้ผู้ป่วยฟื้น' },
      ],
      correctId: 'b', explanation: 'Hyperventilation เพิ่ม ITP ลด venous return + แย่ neurologic outcome' },
    { id: 'bls-b-6', topic: 'high-quality-cpr',
      question: 'อัตรา ventilation ใน BVM โดยไม่มี advanced airway (30:2) แต่ละ breath ใช้เวลาเท่าไร?',
      choices: [
        { id: 'a', text: '< 0.5 วินาที' },
        { id: 'b', text: '~ 1 วินาที (จนหน้าอกขยาย)' },
        { id: 'c', text: '~ 3 วินาที' },
        { id: 'd', text: '~ 5 วินาที' },
      ],
      correctId: 'b', explanation: '~ 1 วินาที จนเห็นหน้าอกขยาย ห้ามอัดแรง' },

    // ---- AED (3) ----
    { id: 'bls-b-7', topic: 'aed',
      question: 'ผู้ป่วยขนหน้าอกหนา ติด AED ลำบาก ควรทำอะไร?',
      choices: [
        { id: 'a', text: 'ไม่ใช้ AED' },
        { id: 'b', text: 'โกนหรือดึงขนออกด้วย pads สำรอง — เร็วที่สุด' },
        { id: 'c', text: 'รอ EMS' },
        { id: 'd', text: 'กด pads แรง ๆ' },
      ],
      correctId: 'b', explanation: 'โกนเร็ว ๆ หรือใช้ pads สำรองดึงขน — ห้ามเสียเวลา' },
    { id: 'bls-b-8', topic: 'aed',
      question: 'ผู้ป่วยมี transdermal patch (เช่น nitroglycerin) ตรงตำแหน่งจะวาง pads ทำไง?',
      choices: [
        { id: 'a', text: 'วางทับ patch' },
        { id: 'b', text: 'ดึง patch ออก เช็ดยาออก แล้ววาง pads' },
        { id: 'c', text: 'หลีกเลี่ยง AED' },
        { id: 'd', text: 'รอ patch ออกฤทธิ์หมด' },
      ],
      correctId: 'b', explanation: 'ดึง patch + เช็ดออก ห้าม shock ผ่าน patch (ลุกไหม้/burn)' },
    { id: 'bls-b-9', topic: 'aed',
      question: 'AED แนะนำ "no shock advised" + ผู้ป่วยไม่มีชีพจร ทำอะไรต่อ?',
      choices: [
        { id: 'a', text: 'รอ AED วิเคราะห์ใหม่' },
        { id: 'b', text: 'เริ่ม CPR ต่อ 2 นาที' },
        { id: 'c', text: 'หยุดทุกอย่าง' },
        { id: 'd', text: 'ปิดเครื่อง' },
      ],
      correctId: 'b', explanation: 'No shock = non-shockable rhythm → CPR ต่อ 2 นาที (PEA/asystole)' },

    // ---- Team / 2-rescuer (3) ----
    { id: 'bls-b-10', topic: 'team',
      question: 'ใน team CPR ใครเป็นคนตรวจสอบคุณภาพการกด (depth/rate/recoil)?',
      choices: [
        { id: 'a', text: 'ผู้กดเอง' },
        { id: 'b', text: 'Leader / ผู้ที่ไม่ได้กด — coaching แบบ real-time' },
        { id: 'c', text: 'ผู้ป่วย' },
        { id: 'd', text: 'AED เท่านั้น' },
      ],
      correctId: 'b', explanation: 'Team member ที่ไม่ได้กด เป็นคน coach quality real-time' },
    { id: 'bls-b-11', topic: 'team',
      question: 'การส่งต่อข้อมูลผู้ป่วยจาก BLS team ไป ALS team ควรใช้รูปแบบใด?',
      choices: [
        { id: 'a', text: 'SBAR หรือ structured handover' },
        { id: 'b', text: 'เล่าตามใจ' },
        { id: 'c', text: 'ส่งเอกสารเท่านั้น' },
        { id: 'd', text: 'ไม่ต้องส่งต่อ' },
      ],
      correctId: 'a', explanation: 'SBAR (Situation-Background-Assessment-Recommendation) ลด miscommunication' },
    { id: 'bls-b-12', topic: 'team',
      question: 'หลัง code จบ ควรทำอะไรเพื่อพัฒนา team?',
      choices: [
        { id: 'a', text: 'แยกย้ายทันที' },
        { id: 'b', text: 'Debriefing — review สิ่งที่ทำได้ดี/ปรับปรุง' },
        { id: 'c', text: 'รายงานหัวหน้าอย่างเดียว' },
        { id: 'd', text: 'ลบ recording' },
      ],
      correctId: 'b', explanation: 'Hot/cold debrief พัฒนา team performance' },

    // ---- In-hospital BLS / Defib AED mode (4) ----
    { id: 'bls-b-13', topic: 'in-hospital-defib',
      question: 'รุ่น defib monitor ในโรงพยาบาล (Philips/Zoll/Lifepak/Mindray) ส่วนใหญ่มี mode อะไรบ้าง?',
      choices: [
        { id: 'a', text: 'มีแค่ manual mode' },
        { id: 'b', text: 'AED mode + Manual mode (+ sync, pacing)' },
        { id: 'c', text: 'มีแค่ AED mode' },
        { id: 'd', text: 'ขึ้นกับยี่ห้อ ไม่มีมาตรฐาน' },
      ],
      correctId: 'b', explanation: 'Defib monitor มี dual mode — BLS ใช้ AED, ALS switch manual ได้ในเครื่องเดียวกัน' },
    { id: 'bls-b-14', topic: 'in-hospital-defib',
      question: 'BLS provider เปิด defib เลือก AED mode แล้ว ขั้นตอนต่อไปคือ?',
      choices: [
        { id: 'a', text: 'รออ่าน rhythm บนจอ' },
        { id: 'b', text: 'ติด pads (anterolateral หรือ AP) — เครื่องจะวิเคราะห์เอง' },
        { id: 'c', text: 'ตั้ง energy ที่ 200J' },
        { id: 'd', text: 'ใส่ ETT ก่อน' },
      ],
      correctId: 'b', explanation: 'AED mode: ติด pads → เครื่องวิเคราะห์อัตโนมัติ → ทำตามคำสั่งเสียง' },
    { id: 'bls-b-15', topic: 'in-hospital-defib',
      question: 'AED mode บอก "no shock advised" ผู้ป่วยไม่มี pulse — ทำอะไรต่อ?',
      choices: [
        { id: 'a', text: 'Switch ไป manual mode shock เอง' },
        { id: 'b', text: 'CPR ต่อ 2 นาที (PEA/asystole — non-shockable)' },
        { id: 'c', text: 'หยุด CPR' },
        { id: 'd', text: 'รอ ALS team' },
      ],
      correctId: 'b', explanation: 'No shock advised = non-shockable rhythm → CPR ต่อ 2 นาที เครื่องจะวิเคราะห์ซ้ำเอง' },
    { id: 'bls-b-16', topic: 'in-hospital-defib',
      question: 'Hand-off จาก BLS → ALS team ควรรายงานอะไรเกี่ยวกับ defib?',
      choices: [
        { id: 'a', text: 'แค่ส่งเครื่องให้' },
        { id: 'b', text: 'เวลาเริ่ม CPR, จำนวน shock + เวลา shock ล่าสุด, rhythm ที่เห็น, ยาที่ให้' },
        { id: 'c', text: 'แค่จำนวน shock' },
        { id: 'd', text: 'ปิดเครื่องก่อน hand-off' },
      ],
      correctId: 'b', explanation: 'Structured hand-off (เช่น SBAR) ลด miscommunication; ALS ต้องรู้ context ก่อน switch manual' },

    // ---- Infant (4) ----
    { id: 'bls-b-17', topic: 'infant',
      question: 'อัตราส่วน C:V ในทารก 2-rescuer คือ?',
      choices: [
        { id: 'a', text: '30:2' }, { id: 'b', text: '15:2' },
        { id: 'c', text: '5:1' }, { id: 'd', text: '10:2' },
      ],
      correctId: 'b', explanation: '2-rescuer ทารก: 15:2 (เน้น oxygenation ในเด็ก)' },
    { id: 'bls-b-18', topic: 'infant',
      question: 'ใน 1-rescuer ทารก ใช้เทคนิคใดกดหน้าอก?',
      choices: [
        { id: 'a', text: '2-finger technique' },
        { id: 'b', text: '2-thumb encircling' },
        { id: 'c', text: 'Heel of hand' },
        { id: 'd', text: '1 hand' },
      ],
      correctId: 'a', explanation: '1-rescuer: 2-finger; 2-rescuer (HCP): 2-thumb encircling' },
    { id: 'bls-b-19', topic: 'infant',
      question: 'AED ในทารก < 1 ปี ที่ไม่มี manual defib + ไม่มี peds attenuator ใช้อะไร?',
      choices: [
        { id: 'a', text: 'รอเครื่องที่มี attenuator' },
        { id: 'b', text: 'ห้ามใช้ AED' },
        { id: 'c', text: 'ใช้ adult AED ได้' },
        { id: 'd', text: 'CPR อย่างเดียวจนกว่า EMS มา' },
      ],
      correctId: 'c', explanation: 'AHA: ถ้าไม่มี manual/attenuator ใช้ adult AED ได้ในทารก — ดีกว่าไม่ defib เลย' },
    { id: 'bls-b-20', topic: 'infant',
      question: 'ทารก HR 45 + cyanosis แต่ตรวจ pulse ได้ — ทำอะไร?',
      choices: [
        { id: 'a', text: 'ให้ O2 อย่างเดียว' },
        { id: 'b', text: 'เริ่มกดหน้าอกทันที + ventilation' },
        { id: 'c', text: 'รอดู 5 นาที' },
        { id: 'd', text: 'ฉีด epinephrine' },
      ],
      correctId: 'b', explanation: 'HR < 60 + poor perfusion ในทารก/เด็ก → start CPR ทันที' },

    // ---- Choking (3) ----
    { id: 'bls-b-21', topic: 'choking',
      question: 'ผู้ใหญ่สำลัก ไอออก พูดได้ ทำอย่างไร?',
      choices: [
        { id: 'a', text: 'Abdominal thrust ทันที' },
        { id: 'b', text: 'ให้ไอเอง อย่ารบกวน' },
        { id: 'c', text: 'เริ่ม CPR' },
        { id: 'd', text: 'ดื่มน้ำ' },
      ],
      correctId: 'b', explanation: 'Mild obstruction → ให้ไอเอง ไอเป็น cough ที่ effective ที่สุด' },
    { id: 'bls-b-22', topic: 'choking',
      question: 'เด็กอายุ 3 ปี สำลัก ไอไม่ออก พูดไม่ได้ ทำอะไร?',
      choices: [
        { id: 'a', text: 'Back blows อย่างเดียว' },
        { id: 'b', text: 'Abdominal thrusts (Heimlich)' },
        { id: 'c', text: 'CPR ทันที' },
        { id: 'd', text: 'รอ EMS' },
      ],
      correctId: 'b', explanation: 'เด็ก ≥ 1 ปี severe obstruction: abdominal thrusts (เหมือนผู้ใหญ่)' },
    { id: 'bls-b-23', topic: 'choking',
      question: 'ทารก choking — ห้ามทำสิ่งใด?',
      choices: [
        { id: 'a', text: 'Back blows' },
        { id: 'b', text: 'Chest thrusts' },
        { id: 'c', text: 'Abdominal thrust' },
        { id: 'd', text: 'CPR ถ้าหมดสติ' },
      ],
      correctId: 'c', explanation: 'ห้าม abdominal thrust ในทารก เสี่ยง liver injury' },

  ],
};
