import { useCaseStore } from '../stores/caseStore';
import { useTimerStore } from '../stores/timerStore';
import { formatTimeLong } from '../utils/formatTime';
import { exportCasePDF } from '../utils/exportPDF';

// Share/Export options — Web Share API, LINE, Email, Copy
export default function ShareExport({ caseData, onClose }) {
  const data = caseData;
  if (!data) return null;

  const duration = data.startTime && data.endTime
    ? Math.floor((new Date(data.endTime) - new Date(data.startTime)) / 1000) : 0;

  const summaryText = [
    `ACLS Case #${data.id}`,
    `Outcome: ${data.outcome?.toUpperCase() || '-'}`,
    `Duration: ${formatTimeLong(duration)}`,
    `Patient: ${data.patient?.name || '-'} (${data.patient?.age || '-'}y)`,
    `Initial Rhythm: ${data.patient?.initialRhythm || '-'}`,
    `CCF: ${data.ccf || '-'}%`,
    `Shocks: ${data.shockCount || 0}`,
    `Events: ${data.events?.length || 0}`,
    `Mode: ${data.mode?.toUpperCase() || 'CLINICAL'}`,
    '',
    'Generated by ACLS EMR — JIA Trainer Center',
  ].join('\n');

  const handleWebShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `ACLS Case #${data.id}`,
          text: summaryText,
        });
      } catch (e) { /* cancelled */ }
    }
  };

  const handleLINE = () => {
    const encoded = encodeURIComponent(summaryText);
    window.open(`https://line.me/R/msg/text/?${encoded}`, '_blank');
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`ACLS Case Report #${data.id}`);
    const body = encodeURIComponent(summaryText);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleCopy = () => {
    navigator.clipboard?.writeText(summaryText).then(() => alert('Copied!'));
  };

  const handlePDF = () => {
    exportCasePDF(data);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30" onClick={onClose}>
      <div className="w-full max-w-lg bg-white rounded-t-2xl p-4 space-y-2 animate-slide-up"
        onClick={e => e.stopPropagation()}
        style={{ boxShadow: '0 -4px 24px rgba(0,0,0,0.15)' }}>
        <div className="text-sm font-bold text-text-primary text-center mb-2">Share Case #{data.id}</div>

        <button onClick={handlePDF} className="w-full btn-action btn-info py-3 text-sm font-bold">
          📄 Export PDF
        </button>

        {navigator.share && (
          <button onClick={handleWebShare} className="w-full btn-action btn-ghost py-3 text-sm font-semibold">
            📤 Share (System)
          </button>
        )}

        <button onClick={handleLINE} className="w-full btn-action py-3 text-sm font-semibold" style={{ background: '#06C755', color: 'white' }}>
          💬 Share via LINE
        </button>

        <button onClick={handleEmail} className="w-full btn-action btn-ghost py-3 text-sm font-semibold">
          ✉️ Share via Email
        </button>

        <button onClick={handleCopy} className="w-full btn-action btn-ghost py-3 text-sm font-semibold">
          📋 Copy Summary
        </button>

        <button onClick={onClose} className="w-full text-text-muted text-xs underline text-center py-2">Cancel</button>
      </div>
    </div>
  );
}
