import { formatTimeLong } from '../utils/formatTime';
import { exportCasePDF } from '../utils/exportPDF';
import { Download, Share, MessageSquare, Mail, Copy, X } from 'lucide-react';

// Share/Export options — Web Share API, LINE, Email, Copy
export default function ShareExport({ caseData, onClose }) {
  const data = caseData;
  if (!data) return null;

  const duration = data.startTime && data.endTime
    ? Math.floor((new Date(data.endTime) - new Date(data.startTime)) / 1000) : 0;

  const summaryText = [
    `ACLS Case #${data.id}`,
    `Outcome: ${data.outcome?.toUpperCase() || '-'}`,
    `Duration: ${formatTimeLong(duration)}`,
    `Patient: ${data.patient?.name || '-'} (${data.patient?.age || '-'}y)`,
    `Initial Rhythm: ${data.patient?.initialRhythm || '-'}`,
    `CCF: ${data.ccf || '-'}%`,
    `Shocks: ${data.shockCount || 0}`,
    `Events: ${data.events?.length || 0}`,
    `Mode: ${data.mode?.toUpperCase() || 'CLINICAL'}`,
    '',
    'Generated by ACLS EMR — JIA Trainer Center',
  ].join('\n');

  const handleWebShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `ACLS Case #${data.id}`,
          text: summaryText,
        });
      } catch (e) { /* cancelled */ }
    }
  };

  const handleLINE = () => {
    const encoded = encodeURIComponent(summaryText);
    window.open(`https://line.me/R/msg/text/?${encoded}`, '_blank');
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`ACLS Case Report #${data.id}`);
    const body = encodeURIComponent(summaryText);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleCopy = () => {
    navigator.clipboard?.writeText(summaryText).then(() => alert('Copied!'));
  };

  const handlePDF = () => {
    exportCasePDF(data);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 backdrop-blur-sm animate-fade-in"
      onClick={onClose}>
      <div className="w-full max-w-lg bg-bg-secondary p-4 space-y-2 animate-slide-up"
        onClick={e => e.stopPropagation()}
        style={{
          borderTopLeftRadius: 'var(--radius-2xl)',
          borderTopRightRadius: 'var(--radius-2xl)',
          boxShadow: 'var(--shadow-pop)',
          paddingBottom: 'calc(16px + env(safe-area-inset-bottom, 0))',
        }}>
        <div className="w-10 h-1 bg-bg-tertiary mx-auto mb-2" style={{ borderRadius: 99 }} />
        <div className="flex items-center justify-between mb-1">
          <div className="text-headline text-text-primary">Share Case #{data.id}</div>
          <button onClick={onClose}
            className="w-8 h-8 inline-flex items-center justify-center text-text-muted hover:bg-bg-tertiary"
            style={{ borderRadius: 99 }} aria-label="Close">
            <X size={18} strokeWidth={2.2} />
          </button>
        </div>

        <button onClick={handlePDF} className="btn btn-info btn-lg btn-block">
          <Download size={16} strokeWidth={2.2} /> Export PDF
        </button>

        {navigator.share && (
          <button onClick={handleWebShare} className="btn btn-ghost btn-block">
            <Share size={16} strokeWidth={2.2} /> Share (System)
          </button>
        )}

        <button onClick={handleLINE}
          className="btn btn-block"
          style={{ background: '#06C755', color: 'white' }}>
          <MessageSquare size={16} strokeWidth={2.2} /> Share via LINE
        </button>

        <button onClick={handleEmail} className="btn btn-ghost btn-block">
          <Mail size={16} strokeWidth={2.2} /> Share via Email
        </button>

        <button onClick={handleCopy} className="btn btn-ghost btn-block">
          <Copy size={16} strokeWidth={2.2} /> Copy Summary
        </button>

        <button onClick={onClose} className="w-full text-text-muted text-caption text-center py-2">Cancel</button>
      </div>
    </div>
  );
}
