-- Pre-test pool expansion: 20 → 80 questions
-- Adds 60 new questions to set "pretest-default" (now selection_mode = 'pool').
-- Distribution after this script:
--   Easy   25 (existing 5  + new 20)
--   Medium 28 (existing 9  + new 19)
--   Hard   27 (existing 6  + new 21)
-- Per-exam blueprint: easy 6 / medium 7 / hard 7 = 20 questions.
-- Topic coverage: all 13 existing topics, ≥3 questions each.

INSERT INTO public.acls_assessment_questions
  (id, set_id, q_number, topic, difficulty, question, choices, correct_id, explanation, reference, active)
VALUES

-- ============================================================
-- EASY (20 new)
-- ============================================================

('pre-021','pretest-default',21,'overview','easy',
 'ห่วงโซ่ที่ถูก "เพิ่มใหม่" ใน Universal Chain of Survival ของ AHA 2025 คือห่วงใด?',
 '[{"id":"a","text":"Defibrillation"},{"id":"b","text":"Advanced care"},{"id":"c","text":"Recovery"},{"id":"d","text":"Post-cardiac arrest care"}]'::jsonb,
 'c',
 'Recovery ถูกเพิ่มเข้ามาเพื่อเน้นการฟื้นฟูระยะยาวทั้งร่างกาย จิตใจ และสังคมของผู้รอดชีวิต',
 'บทที่ 1', true),

('pre-022','pretest-default',22,'assessment','easy',
 'อัตราการกดหน้าอกที่แนะนำใน CPR ผู้ใหญ่คือกี่ครั้งต่อนาที?',
 '[{"id":"a","text":"80-100"},{"id":"b","text":"100-120"},{"id":"c","text":"120-140"},{"id":"d","text":">140"}]'::jsonb,
 'b',
 'AHA: rate 100-120/min — เร็วเกินไปทำให้ recoil ไม่สมบูรณ์ ช้าเกินไป perfusion ตก',
 'บทที่ 2', true),

('pre-023','pretest-default',23,'assessment','easy',
 'ความลึกของการกดหน้าอกในผู้ใหญ่ที่ถูกต้องคือ?',
 '[{"id":"a","text":"อย่างน้อย 3 cm"},{"id":"b","text":"อย่างน้อย 5 cm (ไม่เกิน 6 cm)"},{"id":"c","text":"อย่างน้อย 7 cm"},{"id":"d","text":"3-4 cm"}]'::jsonb,
 'b',
 'Compression depth ≥ 5 cm แต่ไม่เกิน 6 cm; ลึกเกินไปเพิ่ม injury โดยไม่เพิ่ม outcome',
 'บทที่ 2', true),

('pre-024','pretest-default',24,'rrt','easy',
 'เป้าหมายหลักของระบบ Rapid Response Team (RRT) คืออะไร?',
 '[{"id":"a","text":"ลดอัตราการใส่ท่อช่วยหายใจ"},{"id":"b","text":"ตรวจพบและช่วยผู้ป่วยเสื่อมก่อนเกิด cardiac arrest"},{"id":"c","text":"ลดจำนวนผู้ป่วย ICU"},{"id":"d","text":"เพิ่มอัตรารอดเฉพาะหลัง arrest"}]'::jsonb,
 'b',
 'RRT/MET คือ "early rescue" — ตรวจจับสัญญาณเสื่อม (vital sign trigger) เพื่อเข้าช่วยก่อน arrest',
 'บทที่ 3', true),

('pre-025','pretest-default',25,'acs','easy',
 'ขนาด Aspirin ที่แนะนำให้ครั้งแรกใน suspected ACS คือ?',
 '[{"id":"a","text":"75 mg"},{"id":"b","text":"100 mg"},{"id":"c","text":"162-325 mg เคี้ยว"},{"id":"d","text":"500 mg"}]'::jsonb,
 'c',
 'Loading dose Aspirin 162-325 mg เคี้ยว (non-enteric coated) — เพื่อ antiplatelet effect รวดเร็ว',
 'บทที่ 4', true),

('pre-026','pretest-default',26,'acs','easy',
 'อาการเตือนของ ACS ในผู้หญิงและผู้สูงอายุที่ "atypical" ที่พบบ่อยคือ?',
 '[{"id":"a","text":"เจ็บหน้าอกร้าวลงแขนซ้ายเสมอ"},{"id":"b","text":"เหนื่อย คลื่นไส้ แน่นลิ้นปี่ ไม่มีเจ็บอกชัดเจน"},{"id":"c","text":"ปวดศีรษะ"},{"id":"d","text":"ปวดข้อ"}]'::jsonb,
 'b',
 'Atypical presentation พบมากในหญิง สูงอายุ และผู้ป่วยเบาหวาน — เหนื่อย คลื่นไส้ แน่นลิ้นปี่ อ่อนเพลีย',
 'บทที่ 4', true),

('pre-027','pretest-default',27,'stroke','easy',
 'เครื่องมือ pre-hospital ที่นิยมใช้คัดกรอง stroke คือข้อใด?',
 '[{"id":"a","text":"GCS"},{"id":"b","text":"FAST หรือ BE-FAST"},{"id":"c","text":"MEWS"},{"id":"d","text":"NIHSS เท่านั้น"}]'::jsonb,
 'b',
 'FAST = Face/Arm/Speech/Time; BE-FAST เพิ่ม Balance + Eyes — ใช้ที่จุดเกิดเหตุได้ง่าย',
 'บทที่ 5', true),

('pre-028','pretest-default',28,'bradycardia','easy',
 'AHA ACLS bradycardia algorithm ใช้เกณฑ์อัตราหัวใจน้อยกว่าเท่าใด ร่วมกับมีอาการ จึงเข้าทาง?',
 '[{"id":"a","text":"< 40 /min"},{"id":"b","text":"< 50 /min"},{"id":"c","text":"< 60 /min"},{"id":"d","text":"< 70 /min"}]'::jsonb,
 'b',
 'HR < 50/min ร่วมกับ poor perfusion (hypotension, altered mental status, shock, ischemic chest pain, acute HF) จึงเข้า bradycardia algorithm',
 'บทที่ 6', true),

('pre-029','pretest-default',29,'tachycardia','easy',
 'AHA ACLS tachycardia algorithm ใช้เกณฑ์อัตราหัวใจมากกว่าเท่าใด?',
 '[{"id":"a","text":"> 100"},{"id":"b","text":"> 120"},{"id":"c","text":"> 150"},{"id":"d","text":"> 180"}]'::jsonb,
 'c',
 'HR > 150/min ร่วมกับ instability → cardioversion; ถ้า stable → ประเมิน QRS แคบ/กว้าง',
 'บทที่ 7', true),

('pre-030','pretest-default',30,'team','easy',
 'บทบาทที่สำคัญที่สุดของ Team Leader ใน resuscitation คือ?',
 '[{"id":"a","text":"กดหน้าอกเอง"},{"id":"b","text":"ใส่ท่อช่วยหายใจ"},{"id":"c","text":"ประสานงาน วางแผน ตัดสินใจ ไม่ทำหัตถการเอง"},{"id":"d","text":"ฉีดยาเอง"}]'::jsonb,
 'c',
 'Leader = hands-off — มีหน้าที่ situational awareness, task assignment, decision making',
 'บทที่ 8', true),

('pre-031','pretest-default',31,'team','easy',
 'สมาชิกทีมควรเรียก Team Leader ด้วยอะไร?',
 '[{"id":"a","text":"คำเรียกรวมๆ เช่น พี่/หมอ โดยไม่ระบุชื่อ"},{"id":"b","text":"ชื่อหรือบทบาทเฉพาะ เช่น ผู้นำทีม / หมอเอ"},{"id":"c","text":"ไม่ต้องเรียก ส่งสัญญาณตา"},{"id":"d","text":"ส่งสัญญาณมือเท่านั้น"}]'::jsonb,
 'b',
 'การระบุชื่อ/บทบาทชัดเจนเป็นส่วนหนึ่งของ closed-loop communication ป้องกันความสับสน',
 'บทที่ 8', true),

('pre-032','pretest-default',32,'airway','easy',
 'อุปกรณ์ใดต่อไปนี้จัดเป็น Basic Airway?',
 '[{"id":"a","text":"Endotracheal tube"},{"id":"b","text":"LMA"},{"id":"c","text":"Oropharyngeal airway (OPA)"},{"id":"d","text":"Bougie"}]'::jsonb,
 'c',
 'OPA และ NPA = basic; LMA/i-gel = supraglottic; ETT = advanced',
 'บทที่ 9', true),

('pre-033','pretest-default',33,'airway','easy',
 'การใช้ OPA มีข้อห้ามในผู้ป่วยกลุ่มใด?',
 '[{"id":"a","text":"ผู้ป่วยหมดสติสนิท ไม่มี gag reflex"},{"id":"b","text":"ผู้ป่วยที่ยังมี gag reflex"},{"id":"c","text":"ผู้ป่วย arrest"},{"id":"d","text":"ผู้ป่วยอ้วน"}]'::jsonb,
 'b',
 'OPA ใช้ได้เฉพาะผู้ป่วยที่ไม่มี gag reflex — มิฉะนั้นเสี่ยง vomiting / aspiration',
 'บทที่ 9', true),

('pre-034','pretest-default',34,'vf_pvt','easy',
 'VF เป็น rhythm ประเภทใด?',
 '[{"id":"a","text":"Non-shockable"},{"id":"b","text":"Shockable"},{"id":"c","text":"Sinus rhythm"},{"id":"d","text":"Junctional rhythm"}]'::jsonb,
 'b',
 'VF และ pulseless VT = shockable; Asystole และ PEA = non-shockable',
 'บทที่ 10', true),

('pre-035','pretest-default',35,'pea_asystole','easy',
 'Asystole บน ECG monitor มีลักษณะอย่างไร?',
 '[{"id":"a","text":"Sine wave ต่อเนื่อง"},{"id":"b","text":"Flat line (ยืนยันจาก 2 leads)"},{"id":"c","text":"Wide QRS ปกติ"},{"id":"d","text":"Narrow QRS regular"}]'::jsonb,
 'b',
 'Asystole = flat line; ต้องยืนยัน 2 leads เพื่อตัด lead disconnect / low gain ออก',
 'บทที่ 11', true),

('pre-036','pretest-default',36,'post_arrest','easy',
 'หลัง ROSC ผู้ป่วยควรได้รับการดูแลที่ใด?',
 '[{"id":"a","text":"Ward ทั่วไป"},{"id":"b","text":"ER เท่านั้น"},{"id":"c","text":"ICU หรือ Cardiac care unit"},{"id":"d","text":"กลับบ้านถ้ารู้สึกตัวดี"}]'::jsonb,
 'c',
 'ผู้ป่วยหลัง ROSC ต้องการ multidisciplinary post-arrest care ใน ICU/CCU — เฝ้าระวัง rearrest และจัดการ targeted temperature, hemodynamics',
 'บทที่ 12', true),

('pre-037','pretest-default',37,'post_arrest','easy',
 'เป้าหมาย MAP หลัง ROSC ควรอย่างน้อยเท่าใด?',
 '[{"id":"a","text":"≥ 50 mmHg"},{"id":"b","text":"≥ 65 mmHg"},{"id":"c","text":"≥ 80 mmHg"},{"id":"d","text":"≥ 100 mmHg"}]'::jsonb,
 'b',
 'MAP ≥ 65 mmHg เพื่อ cerebral perfusion ที่เพียงพอ; หลีกเลี่ยง hypotension ซึ่งสัมพันธ์กับ outcome แย่',
 'บทที่ 12', true),

('pre-038','pretest-default',38,'pharmacology','easy',
 'Epinephrine ใน cardiac arrest ใช้ขนาดเท่าใดต่อครั้ง?',
 '[{"id":"a","text":"0.5 mg IV"},{"id":"b","text":"1 mg IV/IO"},{"id":"c","text":"2 mg IV"},{"id":"d","text":"0.1 mg IV"}]'::jsonb,
 'b',
 'Epinephrine 1 mg IV/IO ทุก 3-5 นาที (1:10,000 concentration 10 mL) ใน adult arrest',
 'บทที่ 13', true),

('pre-039','pretest-default',39,'pharmacology','easy',
 'Adenosine ขนาดครั้งแรกสำหรับ stable SVT คือ?',
 '[{"id":"a","text":"3 mg"},{"id":"b","text":"6 mg rapid IV push"},{"id":"c","text":"12 mg"},{"id":"d","text":"24 mg"}]'::jsonb,
 'b',
 'Adenosine 6 mg rapid IV push (ใน large vein + flush 20 mL NSS); ถ้าไม่ตอบสนอง ให้ 12 mg ครั้งที่ 2-3',
 'บทที่ 13', true),

('pre-040','pretest-default',40,'pharmacology','easy',
 'Atropine ใน symptomatic bradycardia ขนาดสูงสุดรวม (cumulative max) คือ?',
 '[{"id":"a","text":"1 mg"},{"id":"b","text":"2 mg"},{"id":"c","text":"3 mg"},{"id":"d","text":"5 mg"}]'::jsonb,
 'c',
 '1 mg ทุก 3-5 นาที จนถึง cumulative max 3 mg — เกินกว่านี้ไม่เพิ่ม benefit',
 'บทที่ 13', true),

-- ============================================================
-- MEDIUM (19 new)
-- ============================================================

('pre-041','pretest-default',41,'overview','medium',
 'ในห่วงโซ่ Universal Chain ห่วงที่เน้น "ผู้พบเห็นทำ CPR ทันที" คือห่วงใด?',
 '[{"id":"a","text":"Recognition"},{"id":"b","text":"CPR"},{"id":"c","text":"Defibrillation"},{"id":"d","text":"Recovery"}]'::jsonb,
 'b',
 'ห่วงที่ 2 = early high-quality CPR; bystander CPR เพิ่มอัตราการรอด 2-3 เท่า',
 'บทที่ 1', true),

('pre-042','pretest-default',42,'assessment','medium',
 'อัตราส่วน compression:ventilation ใน 1-rescuer adult CPR ก่อนใส่ advanced airway คือ?',
 '[{"id":"a","text":"15:2"},{"id":"b","text":"30:2"},{"id":"c","text":"5:1"},{"id":"d","text":"100:10"}]'::jsonb,
 'b',
 '30:2 ทั้ง 1 และ 2 rescuer ก่อนใส่ advanced airway; หลังใส่แล้วเปลี่ยนเป็น continuous compression + 1 ventilation ทุก 6 วินาที',
 'บทที่ 2', true),

('pre-043','pretest-default',43,'assessment','medium',
 'High-quality CPR กำหนดให้ "minimize interruption" — chest compression fraction ควรเป็นเท่าใด?',
 '[{"id":"a","text":"≥ 40%"},{"id":"b","text":"≥ 60%"},{"id":"c","text":"≥ 80%"},{"id":"d","text":"100%"}]'::jsonb,
 'b',
 'CCF ≥ 60% (ideal ≥ 80%) — การหยุดกดหน้าอกแต่ละครั้งทำให้ coronary perfusion pressure ตกทันที',
 'บทที่ 2', true),

('pre-044','pretest-default',44,'rrt','medium',
 'เกณฑ์เรียก RRT ข้อใดถือเป็น early warning sign?',
 '[{"id":"a","text":"SBP < 90 mmHg"},{"id":"b","text":"RR > 30 ครั้ง/นาที"},{"id":"c","text":"SpO₂ < 90% on supplement O₂"},{"id":"d","text":"ถูกทุกข้อ"}]'::jsonb,
 'd',
 'ทุกข้อเป็น activation criteria ของระบบ RRT/MET — vital sign abnormality + clinical concern',
 'บทที่ 3', true),

('pre-045','pretest-default',45,'rrt','medium',
 'หลังรายงาน SBAR เสร็จ ผู้รายงานควรปิดท้ายด้วยอะไร?',
 '[{"id":"a","text":"ขอบคุณค่ะ"},{"id":"b","text":"คำถามหรือคำสั่งที่ชัดเจน (Recommendation/Request)"},{"id":"c","text":"พูดยาวๆ ต่อ"},{"id":"d","text":"วางสายเลย"}]'::jsonb,
 'b',
 'R ใน SBAR = Recommendation — ระบุชัดว่าอยากให้แพทย์ทำอะไร เช่น "ขอให้แพทย์มาประเมิน" / "ขอเริ่ม norepinephrine"',
 'บทที่ 3', true),

('pre-046','pretest-default',46,'acs','medium',
 'ผู้ป่วย NSTEMI ที่ดูแลแบบ non-invasive ควรได้ anticoagulant ตัวใดเป็นทางเลือก?',
 '[{"id":"a","text":"UFH bolus + infusion หรือ Enoxaparin SC"},{"id":"b","text":"Warfarin oral"},{"id":"c","text":"DOAC oral"},{"id":"d","text":"ไม่ต้องให้ anticoagulant"}]'::jsonb,
 'a',
 'NSTEMI: ใช้ parenteral anticoagulant (UFH หรือ Enoxaparin) ร่วมกับ DAPT; ไม่ใช้ warfarin/DOAC ใน acute phase',
 'บทที่ 4', true),

('pre-047','pretest-default',47,'acs','medium',
 'Nitrate เป็นข้อห้ามในผู้ป่วย ACS ที่มีลักษณะใด?',
 '[{"id":"a","text":"SBP > 100 mmHg"},{"id":"b","text":"RV infarction / SBP < 90 หรือใช้ PDE-5 inhibitor ภายใน 24-48 ชม."},{"id":"c","text":"Anterior MI"},{"id":"d","text":"Diabetes"}]'::jsonb,
 'b',
 'Nitrate ลด preload — RV infarct, hypotension, หรือใช้ sildenafil/tadalafil ล่าสุด → severe hypotension',
 'บทที่ 4', true),

('pre-048','pretest-default',48,'stroke','medium',
 'หลัง CT brain พบ ICH ในผู้ป่วยที่กำลังจะให้ thrombolytic ควรทำอย่างไร?',
 '[{"id":"a","text":"ให้ thrombolytic ต่อ"},{"id":"b","text":"งด thrombolytic ทันที"},{"id":"c","text":"ให้ heparin แทน"},{"id":"d","text":"ให้ aspirin"}]'::jsonb,
 'b',
 'ICH เป็น absolute contraindication ของ IV thrombolytic — งดทันทีและจัดการ BP, reverse anticoagulant ถ้ามี',
 'บทที่ 5', true),

('pre-049','pretest-default',49,'stroke','medium',
 'เป้าหมาย BP ก่อนให้ IV thrombolytic ใน ischemic stroke ตาม AHA คือ?',
 '[{"id":"a","text":"< 140/90 mmHg"},{"id":"b","text":"< 185/110 mmHg"},{"id":"c","text":"< 220/120 mmHg"},{"id":"d","text":"ไม่ต้องคุม"}]'::jsonb,
 'b',
 'ก่อนให้ tPA/TNK: BP ต้อง < 185/110; หลังให้ < 180/105 นาน 24 ชม. — ลดเสี่ยง symptomatic ICH',
 'บทที่ 5', true),

('pre-050','pretest-default',50,'bradycardia','medium',
 'หลัง Atropine ใน bradycardia ไม่ได้ผล ขั้นต่อไปตาม algorithm คือ?',
 '[{"id":"a","text":"Adenosine"},{"id":"b","text":"Synchronized cardioversion"},{"id":"c","text":"TCP หรือ dopamine/epinephrine infusion"},{"id":"d","text":"Magnesium"}]'::jsonb,
 'c',
 'ลำดับ: Atropine → TCP (transcutaneous pacing) หรือ dopamine 5-20 mcg/kg/min หรือ epinephrine 2-10 mcg/min infusion → expert consult/transvenous pacing',
 'บทที่ 6', true),

('pre-051','pretest-default',51,'tachycardia','medium',
 'SVT ที่ stable หลัง vagal maneuver ไม่ได้ผล ยาลำดับแรกคือ?',
 '[{"id":"a","text":"Amiodarone 150 mg"},{"id":"b","text":"Adenosine 6 mg IV rapid push"},{"id":"c","text":"Diltiazem"},{"id":"d","text":"Lidocaine"}]'::jsonb,
 'b',
 'Stable SVT (narrow + regular): Vagal → Adenosine 6 mg → 12 mg → ถ้ายังไม่ได้พิจารณา BB/CCB',
 'บทที่ 7', true),

('pre-052','pretest-default',52,'team','medium',
 'เมื่อสมาชิกทีมเห็นว่า Team Leader สั่งการผิดควรทำอย่างไร?',
 '[{"id":"a","text":"เงียบและทำตาม"},{"id":"b","text":"ใช้ constructive intervention — สุภาพ ชัดเจน อ้างอิงหลักฐาน"},{"id":"c","text":"ออกจากทีม"},{"id":"d","text":"หยุด resuscitation"}]'::jsonb,
 'b',
 'Constructive intervention เป็น core skill ของทีม — ระบุชื่อ + ปัญหา + เสนอทางแก้ เช่น "พี่ครับ ผมขอเสนอให้ใช้ amiodarone แทน lidocaine ครับ"',
 'บทที่ 8', true),

('pre-053','pretest-default',53,'airway','medium',
 'วิธีที่น่าเชื่อถือที่สุดในการยืนยันตำแหน่ง ETT คือ?',
 '[{"id":"a","text":"ฟังเสียงปอด 5 ตำแหน่ง"},{"id":"b","text":"Chest rise สมมาตร"},{"id":"c","text":"Continuous waveform capnography (ETCO₂)"},{"id":"d","text":"Pulse oximetry"}]'::jsonb,
 'c',
 'Waveform capnography เป็น gold standard — ยืนยันตำแหน่งและตรวจสอบต่อเนื่องระหว่าง resuscitation',
 'บทที่ 9', true),

('pre-054','pretest-default',54,'airway','medium',
 'Bag-mask ventilation ระหว่าง CPR (ก่อน advanced airway) ต้องใช้กี่คนจึงจะมีประสิทธิภาพสูงสุด?',
 '[{"id":"a","text":"1 คน"},{"id":"b","text":"2 คน (1 ครอบหน้ากาก + 1 บีบ bag)"},{"id":"c","text":"3 คน"},{"id":"d","text":"กี่คนก็ได้"}]'::jsonb,
 'b',
 'Two-person BMV: คนแรกใช้ E-C technique 2 มือครอบ + ยกกราม; คนที่สองบีบ bag — leak น้อยกว่าและ volume ดีกว่า single-rescuer',
 'บทที่ 9', true),

('pre-055','pretest-default',55,'vf_pvt','medium',
 'ระหว่าง CPR ใน VF ควรประเมิน rhythm ทุก?',
 '[{"id":"a","text":"1 นาที"},{"id":"b","text":"2 นาที (หลัง CPR ครบ 1 รอบ)"},{"id":"c","text":"5 นาที"},{"id":"d","text":"ทุก shock"}]'::jsonb,
 'b',
 'หยุดกดหน้าอกสั้นๆ ทุก 2 นาที เพื่อ rhythm check + pulse check ถ้ามี organized rhythm',
 'บทที่ 10', true),

('pre-056','pretest-default',56,'vf_pvt','medium',
 'ผู้ป่วย VF ที่ใช้ biphasic defibrillator ขนาดพลังงานครั้งแรกที่แนะนำคือ?',
 '[{"id":"a","text":"50 J"},{"id":"b","text":"120-200 J (ตาม manufacturer)"},{"id":"c","text":"360 J"},{"id":"d","text":"500 J"}]'::jsonb,
 'b',
 'Biphasic: ใช้ขนาดที่ manufacturer แนะนำ (ส่วนใหญ่ 120-200 J); ถ้าไม่ทราบใช้ maximum ทันที — ครั้งต่อไปเท่าเดิมหรือเพิ่ม',
 'บทที่ 10', true),

('pre-057','pretest-default',57,'pea_asystole','medium',
 'ใน 5H 5T ที่ใช้หาสาเหตุของ PEA/Asystole ข้อใดอยู่ในกลุ่ม "T"?',
 '[{"id":"a","text":"Hypovolemia"},{"id":"b","text":"Tension pneumothorax"},{"id":"c","text":"Hypoxia"},{"id":"d","text":"Hypothermia"}]'::jsonb,
 'b',
 '5T: Tension pneumothorax, Tamponade, Toxins, Thrombosis (PE), Thrombosis (MI); 5H: Hypovolemia, Hypoxia, H⁺ acidosis, Hyper/hypokalemia, Hypothermia',
 'บทที่ 11', true),

('pre-058','pretest-default',58,'post_arrest','medium',
 'ผู้ป่วยหลัง ROSC ที่ยังหมดสติ ควร "ไม่" ทำสิ่งใด?',
 '[{"id":"a","text":"Targeted temperature control"},{"id":"b","text":"ค้นหาและรักษาสาเหตุ"},{"id":"c","text":"Hyperventilate ให้ PaCO₂ < 30 mmHg"},{"id":"d","text":"คุม MAP ≥ 65 mmHg"}]'::jsonb,
 'c',
 'Hyperventilation → cerebral vasoconstriction + ↑intrathoracic pressure ลด venous return; target PaCO₂ 35-45 mmHg',
 'บทที่ 12', true),

('pre-059','pretest-default',59,'pharmacology','medium',
 'หลังให้ Adenosine 6 mg ไม่ตอบสนอง ขนาดถัดไปคือ?',
 '[{"id":"a","text":"6 mg ซ้ำ"},{"id":"b","text":"12 mg rapid IV push"},{"id":"c","text":"24 mg"},{"id":"d","text":"ห้ามให้ซ้ำ"}]'::jsonb,
 'b',
 'Adenosine 2nd และ 3rd dose = 12 mg rapid IV push (สามารถซ้ำ 12 mg อีกครั้งได้)',
 'บทที่ 13', true),

-- ============================================================
-- HARD (21 new)
-- ============================================================

('pre-060','pretest-default',60,'overview','hard',
 'การเปลี่ยนแปลงสำคัญใน Post-cardiac arrest care ตาม AHA 2025 คือ?',
 '[{"id":"a","text":"ยกเลิก TTM ไม่ต้องคุมอุณหภูมิ"},{"id":"b","text":"เปลี่ยนเป็น Temperature Control 32-37.5°C อย่างน้อย 36 ชม."},{"id":"c","text":"แนะนำ active hyperthermia"},{"id":"d","text":"ต้องทำ TTM 32-34°C ทุกราย"}]'::jsonb,
 'b',
 'AHA 2025: เปลี่ยนจาก TTM 32-36°C เป็น "Temperature Control" — เลือก target ใดก็ได้ระหว่าง 32-37.5°C คุมอย่างน้อย 36 ชม. + ป้องกัน fever 72 ชม.',
 'บทที่ 12', true),

('pre-061','pretest-default',61,'assessment','hard',
 'ระหว่าง CPR ค่า ETCO₂ < 10 mmHg ต่อเนื่อง สื่อถึงอะไรและควรทำอย่างไร?',
 '[{"id":"a","text":"ROSC ใกล้เกิด"},{"id":"b","text":"คุณภาพ CPR ต่ำ → ปรับ depth/rate/recoil/หรือเปลี่ยนผู้กด"},{"id":"c","text":"เครื่องเสีย ไม่ต้องสนใจ"},{"id":"d","text":"ต้องเพิ่มขนาด epinephrine"}]'::jsonb,
 'b',
 'ETCO₂ < 10 mmHg = CPR คุณภาพต่ำ หรือ severe pulmonary embolism; ETCO₂ พุ่งขึ้นทันที = สัญญาณ ROSC',
 'บทที่ 2', true),

('pre-062','pretest-default',62,'rrt','hard',
 'ตามแนวทาง pre-MET activation criteria GCS ที่ลดลงเท่าใดถือเป็นเกณฑ์เรียก?',
 '[{"id":"a","text":"ลดลง > 1 คะแนน"},{"id":"b","text":"ลดลง ≥ 2 คะแนน (acute drop)"},{"id":"c","text":"ลดลง ≥ 3 คะแนน"},{"id":"d","text":"GCS < 8 เท่านั้น"}]'::jsonb,
 'b',
 'Acute drop in GCS ≥ 2 เป็น MET trigger ในหลาย early warning score; ไม่ต้องรอ GCS < 8',
 'บทที่ 3', true),

('pre-063','pretest-default',63,'acs','hard',
 'STEMI ที่ห่างจาก PCI center ตาม AHA 2025 — FMC to device ภายในกี่นาทีจึงยังเลือก primary PCI?',
 '[{"id":"a","text":"≤ 60"},{"id":"b","text":"≤ 90"},{"id":"c","text":"≤ 120"},{"id":"d","text":"≤ 180"}]'::jsonb,
 'c',
 'FMC-to-device ≤ 120 นาที → เลือก primary PCI (ถ้าโรงพยาบาลแรกไม่มี PCI ให้ transfer); เกิน 120 นาทีพิจารณา fibrinolysis ก่อนแล้วค่อย transfer',
 'บทที่ 4', true),

('pre-064','pretest-default',64,'acs','hard',
 'NSTEMI high-risk (GRACE > 140 หรือ ongoing chest pain/instability) ควรทำ coronary angiography ภายใน?',
 '[{"id":"a","text":"≤ 2 ชม."},{"id":"b","text":"≤ 24 ชม."},{"id":"c","text":"24-72 ชม."},{"id":"d","text":"> 72 ชม."}]'::jsonb,
 'b',
 'Early invasive strategy ≤ 24 ชม. ลด death/MI ใน NSTEMI high-risk; very-high-risk (refractory angina, hemodynamic instability) → ≤ 2 ชม.',
 'บทที่ 4', true),

('pre-065','pretest-default',65,'stroke','hard',
 'Window สำหรับ mechanical thrombectomy ใน LVO stroke สามารถขยายได้สูงสุดถึงเท่าใดจาก last known well (DAWN/DEFUSE-3)?',
 '[{"id":"a","text":"4.5 ชม."},{"id":"b","text":"6 ชม."},{"id":"c","text":"12 ชม."},{"id":"d","text":"24 ชม."}]'::jsonb,
 'd',
 'DAWN (6-24 ชม.) และ DEFUSE-3 (6-16 ชม.) — extend window ถึง 24 ชม. ถ้ามี perfusion mismatch ที่เหมาะสม',
 'บทที่ 5', true),

('pre-066','pretest-default',66,'stroke','hard',
 'ผู้ป่วยกำลังกินยา DOAC (apixaban, rivaroxaban) — ปกติเป็นข้อห้าม IV thrombolysis ภายในกี่ชั่วโมงนับจาก last dose?',
 '[{"id":"a","text":"12 ชม."},{"id":"b","text":"24 ชม."},{"id":"c","text":"48 ชม."},{"id":"d","text":"72 ชม."}]'::jsonb,
 'c',
 'AHA: หลีกเลี่ยง IV thrombolytic ถ้ากิน DOAC ภายใน 48 ชม. ยกเว้นค่า coag/anti-Xa บอกว่า drug level ต่ำ',
 'บทที่ 5', true),

('pre-067','pretest-default',67,'bradycardia','hard',
 'Beta-blocker overdose ทำให้เกิด refractory bradycardia — antidote ที่จำเพาะที่สุดคือ?',
 '[{"id":"a","text":"Atropine เท่านั้น"},{"id":"b","text":"Glucagon high dose"},{"id":"c","text":"Magnesium sulfate"},{"id":"d","text":"Calcium gluconate"}]'::jsonb,
 'b',
 'High-dose glucagon เพิ่ม cAMP ผ่าน receptor อื่น bypass beta-receptor blockade; CCB overdose ใช้ calcium + high-dose insulin/dextrose',
 'บทที่ 6', true),

('pre-068','pretest-default',68,'bradycardia','hard',
 'Transcutaneous pacing — เมื่อจับ capture ได้ rate ที่ควรตั้งเริ่มต้นและกระแสที่ตั้งคือ?',
 '[{"id":"a","text":"Rate 30, current สูงสุด"},{"id":"b","text":"Rate 60-80/min ตั้ง current ขึ้นจนเห็น electrical+mechanical capture แล้วเพิ่มอีก 10 mA"},{"id":"c","text":"Rate 100, current ต่ำสุด"},{"id":"d","text":"Rate 120, current ต่ำสุด"}]'::jsonb,
 'b',
 'Set rate 60-80; เพิ่ม current จากต่ำสุด (โดยทั่วไป 40 mA) จน capture ทั้ง ECG (wide QRS หลังทุก spike) + คลำชีพจรได้ → +10 mA safety margin; ให้ sedation/analgesia',
 'บทที่ 6', true),

('pre-069','pretest-default',69,'tachycardia','hard',
 'Wide-complex tachycardia ที่ stable และไม่แน่ใจว่า VT หรือ SVT with aberrancy ตาม AHA 2025 ควรเลือกยาใดเป็นลำดับแรก?',
 '[{"id":"a","text":"Adenosine 6 mg"},{"id":"b","text":"Procainamide หรือ Amiodarone"},{"id":"c","text":"Verapamil"},{"id":"d","text":"Synchronized cardioversion 200 J ทันที"}]'::jsonb,
 'b',
 'AHA 2025: ไม่ใช้ adenosine ใน wide-complex ที่ไม่ชัดเจน เพราะอาจทำให้ polymorphic VT แย่ลง — ใช้ procainamide (preferred) หรือ amiodarone',
 'บทที่ 7', true),

('pre-070','pretest-default',70,'tachycardia','hard',
 'Torsades de pointes (polymorphic VT with prolonged QT) ยาลำดับแรกที่ควรให้คือ?',
 '[{"id":"a","text":"Amiodarone 300 mg"},{"id":"b","text":"Magnesium sulfate 1-2 g IV"},{"id":"c","text":"Lidocaine 1.5 mg/kg"},{"id":"d","text":"Procainamide"}]'::jsonb,
 'b',
 'Mg sulfate 1-2 g IV เป็น first-line สำหรับ TdP; แก้สาเหตุ (drugs, hypokalemia, hypomagnesemia); pace หรือ isoproterenol ถ้า pause-dependent',
 'บทที่ 7', true),

('pre-071','pretest-default',71,'tachycardia','hard',
 'ผู้ป่วย AF rapid ventricular response (RVR) ที่ stable แต่ EF ลด ควรเลือก rate-control ยาใด?',
 '[{"id":"a","text":"Diltiazem IV"},{"id":"b","text":"Verapamil IV"},{"id":"c","text":"Amiodarone หรือ digoxin (หลีกเลี่ยง non-DHP CCB)"},{"id":"d","text":"Adenosine"}]'::jsonb,
 'c',
 'Heart failure with reduced EF: หลีกเลี่ยง non-DHP CCB (diltiazem/verapamil) เพราะ negative inotrope → ใช้ amiodarone หรือ digoxin แทน',
 'บทที่ 7', true),

('pre-072','pretest-default',72,'team','hard',
 'Debriefing หลัง resuscitation ตามแนวทาง 2025 ควรประกอบด้วย?',
 '[{"id":"a","text":"เน้นเฉพาะหาคนผิด"},{"id":"b","text":"Hot debrief สั้นๆ ทันทีที่หน้างาน + cold debrief เชิงระบบในภายหลัง"},{"id":"c","text":"Cold debrief เท่านั้น"},{"id":"d","text":"ไม่จำเป็นต้องทำ"}]'::jsonb,
 'b',
 'Hot debrief (5-10 นาที ทันที) + cold debrief (formal, multidisciplinary, ทบทวนข้อมูล + แก้ระบบ) เป็น double-loop ที่ AHA แนะนำ',
 'บทที่ 8', true),

('pre-073','pretest-default',73,'airway','hard',
 '"Cannot intubate, can ventilate" (DAS Plan B) — อุปกรณ์หลักที่แนะนำคือ?',
 '[{"id":"a","text":"Surgical cricothyroidotomy ทันที"},{"id":"b","text":"Second-generation supraglottic airway (i-gel, LMA ProSeal)"},{"id":"c","text":"Awake fiberoptic intubation"},{"id":"d","text":"Tracheostomy"}]'::jsonb,
 'b',
 'Plan B: 2nd-gen SGA (มี gastric port) — maintain oxygenation พร้อมวางแผน definitive airway; Plan D = front-of-neck access เมื่อ CICO',
 'บทที่ 9', true),

('pre-074','pretest-default',74,'vf_pvt','hard',
 'Refractory VF หลัง 3 shocks + amiodarone + epinephrine — ทางเลือกที่ AHA 2025 ระบุ?',
 '[{"id":"a","text":"Magnesium sulfate 2 g IV"},{"id":"b","text":"Lidocaine 1-1.5 mg/kg หรือพิจารณา dual sequential defibrillation / ECPR"},{"id":"c","text":"Sodium bicarbonate 1 mEq/kg routine"},{"id":"d","text":"Calcium chloride 10%"}]'::jsonb,
 'b',
 'Refractory VF: ทางเลือก lidocaine (alternative ต่อ amiodarone), dual sequential defibrillation (2 เครื่อง), ECPR ในผู้ป่วยที่เหมาะสม; Mg เฉพาะ TdP เท่านั้น',
 'บทที่ 10', true),

('pre-075','pretest-default',75,'vf_pvt','hard',
 'หลัง defibrillation ครั้งแรกใน VF ขั้นต่อไปทันทีคือ?',
 '[{"id":"a","text":"คลำชีพจรทันที"},{"id":"b","text":"กลับมากดหน้าอกต่อทันทีอีก 2 นาที"},{"id":"c","text":"ใส่ ETT"},{"id":"d","text":"Shock ซ้ำทันที"}]'::jsonb,
 'b',
 'Post-shock pause ต้อง < 5 วินาที — กลับมา CPR ทันทีเพราะ stunned myocardium ยังไม่สร้าง perfusing rhythm; rhythm check ที่ 2 นาที',
 'บทที่ 10', true),

('pre-076','pretest-default',76,'pea_asystole','hard',
 'Cardiac arrest ที่สงสัย pulmonary embolism (PEA, narrow complex, เคย DVT/risk factor) — ทางเลือกพิจารณาคือ?',
 '[{"id":"a","text":"Thrombolytic (tPA) ระหว่าง CPR"},{"id":"b","text":"Epinephrine ขนาดสูง 5 mg"},{"id":"c","text":"Atropine"},{"id":"d","text":"Procainamide"}]'::jsonb,
 'a',
 'Suspected/confirmed massive PE: ให้ tPA ระหว่าง CPR และทำ CPR ต่ออย่างน้อย 60-90 นาทีหลังให้ยา',
 'บทที่ 11', true),

('pre-077','pretest-default',77,'pea_asystole','hard',
 'PEA ที่มี QRS แคบและ rate เร็ว ควรนึกถึงสาเหตุกลุ่มใดเป็นหลัก?',
 '[{"id":"a","text":"Mechanical/obstructive (hypovolemia, tamponade, tension pneumothorax, PE)"},{"id":"b","text":"Metabolic (hyperkalemia, severe acidosis)"},{"id":"c","text":"Hypothermia"},{"id":"d","text":"Hypoxia เพียงอย่างเดียว"}]'::jsonb,
 'a',
 'PEA QRS แคบ + เร็ว → กลุ่ม mechanical/obstructive; QRS กว้าง + ช้า → กลุ่ม metabolic/toxin (hyperK, sodium channel blocker, acidosis)',
 'บทที่ 11', true),

('pre-078','pretest-default',78,'post_arrest','hard',
 'การพยากรณ์ neurological prognosis ในผู้ป่วยหลัง ROSC ที่ยังไม่ทำตามคำสั่ง ควรทำเมื่อใด?',
 '[{"id":"a","text":"ภายใน 6 ชม."},{"id":"b","text":"ภายใน 24 ชม."},{"id":"c","text":"อย่างน้อย 72 ชม. หลัง ROSC และหลังหยุด sedation/normothermia"},{"id":"d","text":"บอกได้ทันที"}]'::jsonb,
 'c',
 'Multimodal prognostication ≥ 72 ชม. หลัง ROSC (และหลังหยุด sedative effect, normothermia) เพื่อหลีกเลี่ยง false pessimism จาก WLST เร็วเกินไป',
 'บทที่ 12', true),

('pre-079','pretest-default',79,'post_arrest','hard',
 'การจัดการ blood glucose ในผู้ป่วยหลัง ROSC ควรเป็นเช่นใด?',
 '[{"id":"a","text":"Tight control 80-110 mg/dL"},{"id":"b","text":"Moderate control 144-180 mg/dL หลีกเลี่ยง hypoglycemia"},{"id":"c","text":"ไม่ต้องคุม"},{"id":"d","text":"เป้าหมาย < 70 mg/dL"}]'::jsonb,
 'b',
 'AHA: หลีกเลี่ยงทั้ง hypoglycemia และ severe hyperglycemia; target moderate (≈ 144-180 mg/dL) — tight control เพิ่มเสี่ยง hypoglycemia โดยไม่เพิ่ม outcome',
 'บทที่ 12', true),

('pre-080','pretest-default',80,'pharmacology','hard',
 'Amiodarone ใน refractory VF/pVT — ขนาดครั้งที่สองคือ?',
 '[{"id":"a","text":"150 mg IV/IO"},{"id":"b","text":"300 mg IV/IO ซ้ำ"},{"id":"c","text":"450 mg IV/IO"},{"id":"d","text":"ห้ามให้ครั้งที่สอง"}]'::jsonb,
 'a',
 'Amiodarone ใน arrest: 1st dose 300 mg IV/IO; 2nd dose 150 mg; total cumulative max 2.2 g/day (รวม infusion)',
 'บทที่ 13', true);
