// Airway post-test — Set A. Certificate requirement (pass ≥ 80%).
export const setA = {
  id: 'aw-posttest-a',
  title: 'ชุด A',
  questions: [
    { id: 'aw-post-a1', question: 'ทำไม Airway ต้องมาก่อนเสมอใน A-B-C-D-E?',
      choices: [{ id: 'a', text: 'ง่ายที่สุด' }, { id: 'b', text: 'การอุดกั้นทำให้ขาดออกซิเจนและเสียชีวิตเร็วกว่าปัญหาระบบอื่น' }, { id: 'c', text: 'ใช้เวลามากที่สุด' }, { id: 'd', text: 'ไม่มีเหตุผลพิเศษ' }],
      correctId: 'b', explanation: 'ทางเดินหายใจอุดกั้นทำให้ขาดออกซิเจนเร็วกว่าปัญหาอื่น จึงต้องแก้ก่อนเสมอ' },
    { id: 'aw-post-a2', question: 'อุดกั้นสมบูรณ์ (complete obstruction) มีลักษณะอย่างไร?',
      choices: [{ id: 'a', text: 'ไอแรง พูดได้' }, { id: 'b', text: 'ไม่มีลมผ่าน ไม่มีเสียง หน้าอกขยับแบบ see-saw' }, { id: 'c', text: 'มีเสียง wheeze เบา ๆ' }, { id: 'd', text: 'หายใจปกติ' }],
      correctId: 'b', explanation: 'อุดกั้นสมบูรณ์ไม่มีลมผ่านเลย ไม่มีเสียง และหน้าอกอาจขยับแบบ paradoxical' },
    { id: 'aw-post-a3', question: 'Head-tilt/chin-lift ห้ามใช้ในกรณีใด?',
      choices: [{ id: 'a', text: 'ผู้ป่วยหมดสติทั่วไป' }, { id: 'b', text: 'สงสัยบาดเจ็บกระดูกสันหลังส่วนคอ (ใช้ jaw-thrust แทนก่อน)' }, { id: 'c', text: 'ผู้ป่วยนอนหงาย' }, { id: 'd', text: 'ผู้ป่วยไม่หายใจ' }],
      correctId: 'b', explanation: 'สงสัย spine injury ให้ลอง jaw-thrust ก่อน (แต่เปลี่ยนกลับได้ถ้าไม่ได้ผล)' },
    { id: 'aw-post-a4', question: 'การดูดสิ่งคัดหลั่งแต่ละครั้งไม่ควรเกินกี่วินาที?',
      choices: [{ id: 'a', text: '5' }, { id: 'b', text: '10–15' }, { id: 'c', text: '30' }, { id: 'd', text: '60' }],
      correctId: 'b', explanation: 'ดูดนานเกินเสี่ยง hypoxia' },
    { id: 'aw-post-a5', question: 'ทำไม OPA ใช้ได้เฉพาะผู้ป่วยหมดสติสนิท?',
      choices: [{ id: 'a', text: 'เพราะแพง' }, { id: 'b', text: 'เพราะกระตุ้น gag reflex จนอาเจียน/สำลักได้ถ้ายังมี reflex' }, { id: 'c', text: 'เพราะใช้เวลานาน' }, { id: 'd', text: 'ไม่มีเหตุผลพิเศษ' }],
      correctId: 'b', explanation: 'ผู้ป่วยที่ยังมี gag reflex จะอาเจียนเมื่อใส่ OPA' },
    { id: 'aw-post-a6', question: 'ขนาด OPA ที่เล็กเกินไปมีผลอย่างไร?',
      choices: [{ id: 'a', text: 'ดันลิ้นเข้าไปอุดกั้นทางเดินหายใจ' }, { id: 'b', text: 'กระตุ้น laryngospasm' }, { id: 'c', text: 'ไม่มีผล' }, { id: 'd', text: 'ป้องกัน aspiration ได้ดีขึ้น' }],
      correctId: 'a', explanation: 'ขนาดเล็กเกินไปดันลิ้นเข้าไปอุดกั้นแทนที่จะเปิดทางเดินหายใจ' },
    { id: 'aw-post-a7', question: 'NPA เหมาะกับผู้ป่วยแบบใดมากกว่า OPA?',
      choices: [{ id: 'a', text: 'ผู้ป่วยหมดสติสนิทเท่านั้น' }, { id: 'b', text: 'ผู้ป่วยกึ่งรู้สึกตัวที่ยังมี gag reflex บ้าง' }, { id: 'c', text: 'ผู้ป่วยกระดูกฐานกะโหลกหัก' }, { id: 'd', text: 'ไม่มีข้อแตกต่าง' }],
      correctId: 'b', explanation: 'NPA ทนต่อ gag reflex ได้ดีกว่า OPA' },
    { id: 'aw-post-a8', question: 'ก่อนใช้ BVM ควรต่อ O₂ flow เท่าไรเพื่อให้ได้ FiO₂ สูงสุด?',
      choices: [{ id: 'a', text: '2–4 L/min' }, { id: 'b', text: '10–15 L/min (high-flow) ต่อ reservoir' }, { id: 'c', text: 'ไม่ต้องต่อ O₂' }, { id: 'd', text: '1 L/min' }],
      correctId: 'b', explanation: 'High-flow O₂ ต่อ reservoir ให้ FiO₂ ใกล้ 100%' },
    { id: 'aw-post-a9', question: 'เมื่อใดควรเปลี่ยนจาก 1-rescuer เป็น 2-rescuer BVM?',
      choices: [{ id: 'a', text: 'เมื่อ seal ไม่แนบสนิทและหน้าอกไม่ยก' }, { id: 'b', text: 'ไม่ต้องเปลี่ยนเลย' }, { id: 'c', text: 'หลัง 10 นาที' }, { id: 'd', text: 'เมื่อผู้ป่วยตื่น' }],
      correctId: 'a', explanation: 'ปรับทันทีเมื่อสังเกตว่า seal ไม่ดีหรือหน้าอกไม่ยก ไม่ต้องรอ' },
    { id: 'aw-post-a10', question: 'ระหว่าง CPR ที่ยังไม่มี advanced airway อัตรากดหน้าอกต่อช่วยหายใจในผู้ใหญ่คือ?',
      choices: [{ id: 'a', text: '15:2' }, { id: 'b', text: '30:2' }, { id: 'c', text: '5:1' }, { id: 'd', text: 'กดต่อเนื่องไม่มีช่วยหายใจ' }],
      correctId: 'b', explanation: '30 กดหน้าอก ต่อ 2 ครั้งช่วยหายใจ เมื่อยังไม่มี advanced airway' },
    { id: 'aw-post-a11', question: 'SGA (i-gel/LMA) ใส่ได้เร็วกว่า ETT เพราะอะไร?',
      choices: [{ id: 'a', text: 'ไม่ต้องมองเห็น vocal cords โดยตรง' }, { id: 'b', text: 'ราคาถูกกว่า' }, { id: 'c', text: 'ไม่ต้องฝึกฝน' }, { id: 'd', text: 'ใช้ในเด็กเท่านั้น' }],
      correctId: 'a', explanation: 'SGA ดันไปตามแนวกายวิภาคโดยไม่ต้องเห็นกล่องเสียงโดยตรง' },
    { id: 'aw-post-a12', question: 'ระหว่างพยายามใส่ ETT ไม่ควรหยุดกดหน้าอกเกินกี่วินาทีต่อครั้ง?',
      choices: [{ id: 'a', text: '5' }, { id: 'b', text: '10' }, { id: 'c', text: '30' }, { id: 'd', text: '60' }],
      correctId: 'b', explanation: 'จำกัดการหยุดกดหน้าอกไว้ไม่เกิน 10 วินาทีต่อครั้ง' },
    { id: 'aw-post-a13', question: 'วิธียืนยันตำแหน่งท่อที่ต้องใช้ต่อเนื่องตลอดการช่วยชีวิต คือ?',
      choices: [{ id: 'a', text: 'X-ray' }, { id: 'b', text: 'Waveform capnography' }, { id: 'c', text: 'คลำชีพจร' }, { id: 'd', text: 'วัดอุณหภูมิ' }],
      correctId: 'b', explanation: 'Capnography ต้องติดตามต่อเนื่อง ไม่ใช่ตรวจครั้งเดียว' },
    { id: 'aw-post-a14', question: 'EtCO₂ ต่ำต่อเนื่องระหว่าง CPR บ่งบอกอะไร?',
      choices: [{ id: 'a', text: 'CPR มีคุณภาพดีมาก' }, { id: 'b', text: 'CPR อาจไม่มีประสิทธิภาพหรือ cardiac output ต่ำ' }, { id: 'c', text: 'ผู้ป่วยฟื้นแล้ว' }, { id: 'd', text: 'เครื่องวัดผิดปกติเสมอ' }],
      correctId: 'b', explanation: 'ใช้ EtCO₂ ติดตามคุณภาพ CPR ได้' },
    { id: 'aw-post-a15', question: 'ผู้ป่วยผู้ใหญ่อ้วนมากที่โอบเอวไม่ได้ ควรใช้เทคนิคใดแทน abdominal thrust?',
      choices: [{ id: 'a', text: 'Chest thrust (กลางกระดูกอก)' }, { id: 'b', text: 'ตบหลังอย่างเดียว' }, { id: 'c', text: 'ไม่ต้องช่วยเหลือ' }, { id: 'd', text: 'ให้ดื่มน้ำ' }],
      correctId: 'a', explanation: 'ใช้ chest thrust แทนเมื่อโอบเอวไม่ได้ (หญิงตั้งครรภ์ระยะท้าย/อ้วนมาก)' },
    { id: 'aw-post-a16', question: 'เทคนิคช่วยเหลือทารก (< 1 ปี) ที่สำลักคือ?',
      choices: [{ id: 'a', text: 'Abdominal thrust อย่างเดียว' }, { id: 'b', text: 'สลับตบหลัง 5 ครั้ง + กดหน้าอก 5 ครั้ง' }, { id: 'c', text: 'จับห้อยหัวเขย่า' }, { id: 'd', text: 'ไม่ต้องทำอะไร' }],
      correctId: 'b', explanation: 'ห้ามทำ abdominal thrust ในทารก ใช้เทคนิคสลับ 5-5 แทน' },
    { id: 'aw-post-a17', question: 'หลังช่วยเหลือผู้ป่วยสำลักสำเร็จแล้ว ควรทำอย่างไรต่อ?',
      choices: [{ id: 'a', text: 'ปล่อยกลับบ้านได้ทันที' }, { id: 'b', text: 'ให้ EMS/แพทย์ประเมินต่อเสมอ' }, { id: 'c', text: 'ทำ thrust ซ้ำเพื่อความมั่นใจ' }, { id: 'd', text: 'ไม่ต้องบันทึกอะไร' }],
      correctId: 'b', explanation: 'Thrusts เสี่ยงบาดเจ็บอวัยวะภายในและอาจมีเศษสิ่งของหลงเหลือ' },
    { id: 'aw-post-a18', question: 'Jaw-thrust ทำอย่างไร?',
      choices: [{ id: 'a', text: 'เอียงศีรษะไปด้านหลังแรง ๆ' }, { id: 'b', text: 'ใช้มือทั้งสองข้างจับมุมขากรรไกรล่างดันขึ้นมาด้านหน้า โดยไม่เอียงศีรษะ' }, { id: 'c', text: 'กดหน้าผากอย่างเดียว' }, { id: 'd', text: 'ดึงลิ้นออกมาด้วยมือ' }],
      correctId: 'b', explanation: 'Jaw-thrust ไม่เอียงศีรษะ ใช้มือทั้งสองข้างดันขากรรไกรขึ้นมาด้านหน้า' },
    { id: 'aw-post-a19', question: 'สาเหตุอุดกั้นทางเดินหายใจที่พบบ่อยที่สุดในผู้ป่วยหมดสติคืออะไร?',
      choices: [{ id: 'a', text: 'เสมหะ' }, { id: 'b', text: 'ลิ้นตกไปอุดผนังคอหลัง' }, { id: 'c', text: 'เนื้องอก' }, { id: 'd', text: 'สิ่งแปลกปลอมเสมอ' }],
      correctId: 'b', explanation: 'ลิ้นเป็นสาเหตุอุดกั้นที่พบบ่อยที่สุดในผู้ป่วยหมดสติ — head-tilt/chin-lift แก้ปัญหานี้โดยตรง' },
    { id: 'aw-post-a20', question: 'ข้อใดสรุปหลักการป้องกัน gastric inflation ได้ถูกต้อง?',
      choices: [{ id: 'a', text: 'บีบให้สุดถุงทุกครั้ง' }, { id: 'b', text: 'บีบพอเห็นหน้าอกยก ~1 วินาที/ครั้ง หลังเปิดทางเดินหายใจดีแล้ว' }, { id: 'c', text: 'บีบเร็วที่สุดเท่าที่ทำได้' }, { id: 'd', text: 'ไม่ต้องเปิดทางเดินหายใจก่อนบีบ' }],
      correctId: 'b', explanation: 'บีบพอเห็นหน้าอกยก ด้วยจังหวะ ~1 วินาที และเปิดทางเดินหายใจให้ดีก่อนเสมอ' },
  ],
};
