// Airway pre-test — Set A. Diagnostic check before starting the lessons
// (not a certificate requirement — same pattern as bls-hcp/preTest/setA.js).
// คำเฉลยเขียนเชิงสอน: ทำไมถูก + กลไก + ทำไมตัวเลือกที่ล่อผิด
export const setA = {
  id: 'aw-pretest-a',
  title: 'ชุด A',
  questions: [
    { id: 'aw-pt-a1', question: 'ตัวอักษรใดใน A-B-C-D-E หมายถึงทางเดินหายใจและมาก่อนเสมอ?',
      choices: [{ id: 'a', text: 'B' }, { id: 'b', text: 'A' }, { id: 'c', text: 'C' }, { id: 'd', text: 'D' }],
      correctId: 'b', explanation: 'A = Airway มาก่อน B (Breathing) และ C (Circulation) เสมอ เพราะทางเดินหายใจอุดกั้นทำให้สมองขาดออกซิเจนภายในไม่กี่นาที (เสียหายถาวรที่ ~4–6 นาที) เร็วกว่าปัญหาระบบไหลเวียน จึงต้องเปิดทางเดินหายใจให้โล่งก่อน' },
    { id: 'aw-pt-a2', question: 'เสียง stridor บ่งบอกการอุดกั้นระดับใด?',
      choices: [{ id: 'a', text: 'หลอดลมฝอย (ส่วนล่าง)' }, { id: 'b', text: 'กล่องเสียงหรือสูงกว่า' }, { id: 'c', text: 'ปอด' }, { id: 'd', text: 'กระบังลม' }],
      correctId: 'b', explanation: 'Stridor เกิดจากลมผ่านช่องแคบระดับกล่องเสียง/upper airway (เช่น laryngospasm, angioedema, croup) — ต่างจาก wheeze ที่มาจากหลอดลมฝอยส่วนล่างหดเกร็ง และ snoring ที่มาจากลิ้นตกระดับคอหอย จำหลัก: snoring=ลิ้น · stridor=กล่องเสียง · wheeze=หลอดลมเล็ก · gurgling=มีของเหลว' },
    { id: 'aw-pt-a3', question: 'ท่าเปิดทางเดินหายใจที่ปลอดภัยกว่าเมื่อสงสัย spine injury คือ?',
      choices: [{ id: 'a', text: 'Head-tilt/chin-lift' }, { id: 'b', text: 'Jaw-thrust' }, { id: 'c', text: 'Trendelenburg' }, { id: 'd', text: 'Sniffing position' }],
      correctId: 'b', explanation: 'Jaw-thrust ดันขากรรไกรไปข้างหน้าโดย "ไม่เอียงศีรษะ" จึงลดการเคลื่อนของกระดูกคอ — ต่างจาก head-tilt/chin-lift และ sniffing ที่ต้องเงยศีรษะ; แต่ถ้า jaw-thrust ไม่ได้ผล ความโล่งของทางเดินหายใจสำคัญกว่า ให้กลับมา head-tilt' },
    { id: 'aw-pt-a4', question: 'OPA ใช้ได้เฉพาะผู้ป่วยแบบใด?',
      choices: [{ id: 'a', text: 'รู้สึกตัวดี' }, { id: 'b', text: 'หมดสติสนิท ไม่มี gag reflex' }, { id: 'c', text: 'กึ่งรู้สึกตัว' }, { id: 'd', text: 'ทุกกรณี' }],
      correctId: 'b', explanation: 'OPA วางในคอหอยจะกระตุ้น gag reflex ทำให้อาเจียน/สำลักถ้าผู้ป่วยยังมี reflex — จึงใช้เฉพาะผู้หมดสติสนิท; ผู้กึ่งรู้สึกตัวให้เลือก NPA ที่ทน gag ได้ดีกว่า' },
    { id: 'aw-pt-a5', question: 'วัดขนาด OPA จากจุดใดถึงจุดใด?',
      choices: [{ id: 'a', text: 'ปลายจมูกถึงติ่งหู' }, { id: 'b', text: 'มุมปากถึงมุมกราม/ติ่งหู' }, { id: 'c', text: 'คางถึงหน้าอก' }, { id: 'd', text: 'หน้าผากถึงคาง' }],
      correctId: 'b', explanation: 'OPA วัดจากมุมปากถึงมุมกราม/ติ่งหู เพื่อให้ปลายพอดีเหนือคอหอย — ขนาดผิด: สั้นไปดันลิ้นไม่พ้น, ยาวไปกดกล่องเสียง; ส่วน "ปลายจมูกถึงติ่งหู" เป็นวิธีวัด NPA' },
    { id: 'aw-pt-a6', question: 'ข้อห้ามสำคัญของ NPA คืออะไร?',
      choices: [{ id: 'a', text: 'ผู้ป่วยขากรรไกรค้าง' }, { id: 'b', text: 'สงสัยกระดูกฐานกะโหลกหัก' }, { id: 'c', text: 'ผู้ป่วยรู้สึกตัว' }, { id: 'd', text: 'ผู้ป่วยหายใจเองได้' }],
      correctId: 'b', explanation: 'เมื่อมี basilar skull fracture การสอด NPA ทางจมูกเสี่ยงทะลุเข้าโพรงกะโหลก/สมอง — จึงเป็นข้อห้าม; ในทางกลับกัน NPA เหมาะกับผู้กึ่งรู้สึกตัวที่ยังหายใจเอง (ทน gag ได้)' },
    { id: 'aw-pt-a7', question: 'EC-clamp technique ใช้กับอุปกรณ์ใด?',
      choices: [{ id: 'a', text: 'OPA' }, { id: 'b', text: 'Bag-Mask Ventilation' }, { id: 'c', text: 'ETT' }, { id: 'd', text: 'Suction' }],
      correctId: 'b', explanation: 'EC-clamp คือเทคนิคจับหน้ากาก BVM: นิ้วโป้ง/ชี้ทำรูป "C" กดหน้ากาก อีก 3 นิ้วทำรูป "E" เกี่ยว "กระดูก" ขากรรไกรยกขึ้นชนหน้ากาก (ไม่กดเนื้อใต้คาง) — ไม่เกี่ยวกับ OPA/ETT/suction' },
    { id: 'aw-pt-a8', question: 'สาเหตุหลักของ gastric inflation ระหว่างบีบ BVM คืออะไร?',
      choices: [{ id: 'a', text: 'บีบเบาเกินไป' }, { id: 'b', text: 'บีบแรง/เร็วเกินไปและทางเดินหายใจเปิดไม่พอ' }, { id: 'c', text: 'ใช้ reservoir bag' }, { id: 'd', text: 'ใส่ NPA' }],
      correctId: 'b', explanation: 'การบีบแรง/เร็วเกินสร้างแรงดันสูงกว่าที่หูรูดหลอดอาหารทนได้ ลมจึงเข้ากระเพาะแทนปอด (โดยเฉพาะเมื่อเปิดทางเดินหายใจไม่ดี) → ดันกระบังลม + เสี่ยงสำลัก; แก้โดยเปิดทางเดินหายใจให้ดี บีบพอเห็นหน้าอกยก ~1 วินาที/ครั้ง' },
    { id: 'aw-pt-a9', question: 'หลังใส่ advanced airway ระหว่าง CPR ควรช่วยหายใจผู้ใหญ่อัตราใด?',
      choices: [{ id: 'a', text: '30:2' }, { id: 'b', text: '1 ครั้งทุก 6 วินาที ต่อเนื่องไม่หยุดกดหน้าอก' }, { id: 'c', text: '1 ครั้งทุก 3 วินาที' }, { id: 'd', text: 'หยุดกดหน้าอกทุกครั้ง' }],
      correctId: 'b', explanation: 'เมื่อมี ETT/SGA ที่ป้องกันทางเดินหายใจแล้ว ช่วยหายใจได้โดยไม่ต้องหยุดกด → ผู้ใหญ่ 1 ครั้งทุก 6 วินาที (10/นาที) กดต่อเนื่อง; "30:2" ใช้ก่อนมี advanced airway และ "ทุก 3 วินาที" เร็วเกิน = over-ventilate (ลดเลือดไหลกลับหัวใจ)' },
    { id: 'aw-pt-a10', question: 'วิธีที่เชื่อถือได้สุดในการยืนยันตำแหน่งท่อหลังใส่ advanced airway คือ?',
      choices: [{ id: 'a', text: 'ฟัง breath sound อย่างเดียว' }, { id: 'b', text: 'Waveform capnography' }, { id: 'c', text: 'ดูสีผิว' }, { id: 'd', text: 'วัดความดัน' }],
      correctId: 'b', explanation: 'Waveform capnography เป็นมาตรฐานทอง: ยืนยันตำแหน่งท่อ + วัดคุณภาพ CPR + จับ ROSC และใช้ต่อเนื่องจับท่อเลื่อน/หลุดได้ — การฟังปอด/ดูสีผิวเป็นการยืนยันเสริม ไม่ไวและเชื่อถือได้เท่า (ไม่มี waveform = สงสัยท่อผิดที่ทันที)' },
    { id: 'aw-pt-a11', question: 'EtCO₂ พุ่งขึ้นฉับพลันระหว่าง CPR มักบ่งบอกอะไร?',
      choices: [{ id: 'a', text: 'ท่อหลุด' }, { id: 'b', text: 'ROSC' }, { id: 'c', text: 'เครื่องเสีย' }, { id: 'd', text: 'ผู้ป่วยหยุดหายใจ' }],
      correctId: 'b', explanation: 'เมื่อหัวใจกลับมาเต้นเอง cardiac output พุ่งขึ้น พา CO₂ มาระบายที่ปอดมากขึ้น EtCO₂ จึงกระโดดสูงและคงอยู่ = สัญญาณ ROSC (มักมาก่อนคลำชีพจรได้) — ตรงข้ามกับ "ท่อหลุด/เครื่องหลุด" ที่ EtCO₂ ตกฮวบเป็น 0' },
    { id: 'aw-pt-a12', question: 'ข้อแตกต่างหลักระหว่าง SGA กับ ETT คืออะไร?',
      choices: [{ id: 'a', text: 'SGA ป้องกัน aspiration ดีกว่า' }, { id: 'b', text: 'ETT ต้องมองเห็น vocal cords และผู้ชำนาญเป็นผู้ใส่ ส่วน SGA ใส่เร็วกว่า' }, { id: 'c', text: 'เหมือนกันทุกประการ' }, { id: 'd', text: 'SGA ใช้เฉพาะเด็ก' }],
      correctId: 'b', explanation: 'SGA (i-gel/LMA) วางเหนือ glottis โดยไม่ต้องมองสายเสียง จึงใส่เร็ว เหมาะกับผู้ใส่ประสบการณ์น้อย/ต้องการเร็ว — ETT ผ่านสายเสียงมี cuff ป้องกัน aspiration "ดีกว่า" (ไม่ใช่ SGA) แต่ต้องมองเห็น glottis + ทักษะสูง' },
    { id: 'aw-pt-a13', question: 'ผู้ป่วยผู้ใหญ่สำลักที่ยังไอและพูดได้ ควรทำอย่างไร?',
      choices: [{ id: 'a', text: 'ทำ abdominal thrust ทันที' }, { id: 'b', text: 'ให้ไอต่อไปเอง เฝ้าสังเกตใกล้ชิด' }, { id: 'c', text: 'ตบหลังแรง ๆ' }, { id: 'd', text: 'เริ่ม CPR' }],
      correctId: 'b', explanation: 'ยังไอ/พูดได้ = อุดกั้น "บางส่วน" การไอเองมีประสิทธิภาพสูงสุดในการขับสิ่งแปลกปลอม การแทรกแซง (thrust/ตบหลัง) โดยไม่จำเป็นอาจทำให้แย่ลง — เฝ้าดูใกล้ชิด พร้อมช่วยทันทีถ้าเปลี่ยนเป็นอุดกั้นสมบูรณ์ (ไอไม่ออก/เงียบ)' },
    { id: 'aw-pt-a14', question: 'ทำไมห้ามทำ abdominal thrust ในทารก?',
      choices: [{ id: 'a', text: 'ไม่ได้ผล' }, { id: 'b', text: 'เสี่ยงบาดเจ็บอวัยวะภายใน — ใช้ back blows + chest thrusts แทน' }, { id: 'c', text: 'ทารกไม่สำลัก' }, { id: 'd', text: 'ใช้เหมือนผู้ใหญ่' }],
      correctId: 'b', explanation: 'ตับของทารกใหญ่และไม่มีซี่โครงล่างปกป้องดีพอ abdominal thrust จึงเสี่ยงบาดเจ็บอวัยวะภายในรุนแรง — ใช้สลับ back blows 5 ครั้ง + chest thrusts 5 ครั้งแทน' },
    { id: 'aw-pt-a15', question: 'ผู้ป่วยหมดสติระหว่างทำ Heimlich ควรทำอย่างไรต่อ?',
      choices: [{ id: 'a', text: 'หยุดช่วยเหลือ' }, { id: 'b', text: 'ประคองลงพื้นแล้วเริ่ม CPR ทันที' }, { id: 'c', text: 'ทำ Heimlich ต่อจนสำเร็จ' }, { id: 'd', text: 'รอ EMS เฉย ๆ' }],
      correctId: 'b', explanation: 'เมื่อหมดสติ ให้ประคองลงพื้นแล้วเริ่ม CPR ทันที — การกดหน้าอกสร้างแรงดันในทรวงอกช่วยไล่สิ่งแปลกปลอมได้เช่นกัน และก่อนช่วยหายใจแต่ละครั้งให้เปิดปากมองหาสิ่งแปลกปลอมที่ "เห็นได้" (ไม่ล้วงมั่ว)' },
  ],
};
