// Airway pre-test — Set A. Diagnostic check before starting the lessons
// (not a certificate requirement — same pattern as bls-hcp/preTest/setA.js).
export const setA = {
  id: 'aw-pretest-a',
  title: 'ชุด A',
  questions: [
    { id: 'aw-pt-a1', question: 'ตัวอักษรใดใน A-B-C-D-E หมายถึงทางเดินหายใจและมาก่อนเสมอ?',
      choices: [{ id: 'a', text: 'B' }, { id: 'b', text: 'A' }, { id: 'c', text: 'C' }, { id: 'd', text: 'D' }],
      correctId: 'b', explanation: 'A = Airway มาก่อนเสมอเพราะการอุดกั้นทำให้ขาดออกซิเจนเร็วที่สุด' },
    { id: 'aw-pt-a2', question: 'เสียง stridor บ่งบอกการอุดกั้นระดับใด?',
      choices: [{ id: 'a', text: 'หลอดลมฝอย (ส่วนล่าง)' }, { id: 'b', text: 'กล่องเสียงหรือสูงกว่า' }, { id: 'c', text: 'ปอด' }, { id: 'd', text: 'กระบังลม' }],
      correctId: 'b', explanation: 'Stridor เกิดจากลมผ่านช่องแคบระดับ larynx/upper airway' },
    { id: 'aw-pt-a3', question: 'ท่าเปิดทางเดินหายใจที่ปลอดภัยกว่าเมื่อสงสัย spine injury คือ?',
      choices: [{ id: 'a', text: 'Head-tilt/chin-lift' }, { id: 'b', text: 'Jaw-thrust' }, { id: 'c', text: 'Trendelenburg' }, { id: 'd', text: 'Sniffing position' }],
      correctId: 'b', explanation: 'Jaw-thrust ไม่ต้องเอียงศีรษะ จึงลดความเสี่ยงต่อ spine' },
    { id: 'aw-pt-a4', question: 'OPA ใช้ได้เฉพาะผู้ป่วยแบบใด?',
      choices: [{ id: 'a', text: 'รู้สึกตัวดี' }, { id: 'b', text: 'หมดสติสนิท ไม่มี gag reflex' }, { id: 'c', text: 'กึ่งรู้สึกตัว' }, { id: 'd', text: 'ทุกกรณี' }],
      correctId: 'b', explanation: 'OPA กระตุ้นอาเจียนถ้ายังมี gag reflex' },
    { id: 'aw-pt-a5', question: 'วัดขนาด OPA จากจุดใดถึงจุดใด?',
      choices: [{ id: 'a', text: 'ปลายจมูกถึงติ่งหู' }, { id: 'b', text: 'มุมปากถึงมุมกราม/ติ่งหู' }, { id: 'c', text: 'คางถึงหน้าอก' }, { id: 'd', text: 'หน้าผากถึงคาง' }],
      correctId: 'b', explanation: 'วัดจากมุมปากถึงมุมกราม (หรือติ่งหู)' },
    { id: 'aw-pt-a6', question: 'ข้อห้ามสำคัญของ NPA คืออะไร?',
      choices: [{ id: 'a', text: 'ผู้ป่วยขากรรไกรค้าง' }, { id: 'b', text: 'สงสัยกระดูกฐานกะโหลกหัก' }, { id: 'c', text: 'ผู้ป่วยรู้สึกตัว' }, { id: 'd', text: 'ผู้ป่วยหายใจเองได้' }],
      correctId: 'b', explanation: 'เสี่ยงสอดทะลุเข้ากะโหลกศีรษะถ้ามี basilar skull fracture' },
    { id: 'aw-pt-a7', question: 'EC-clamp technique ใช้กับอุปกรณ์ใด?',
      choices: [{ id: 'a', text: 'OPA' }, { id: 'b', text: 'Bag-Mask Ventilation' }, { id: 'c', text: 'ETT' }, { id: 'd', text: 'Suction' }],
      correctId: 'b', explanation: 'EC-clamp คือเทคนิคจับหน้ากากขณะช่วยหายใจด้วย BVM' },
    { id: 'aw-pt-a8', question: 'สาเหตุหลักของ gastric inflation ระหว่างบีบ BVM คืออะไร?',
      choices: [{ id: 'a', text: 'บีบเบาเกินไป' }, { id: 'b', text: 'บีบแรง/เร็วเกินไปและทางเดินหายใจเปิดไม่พอ' }, { id: 'c', text: 'ใช้ reservoir bag' }, { id: 'd', text: 'ใส่ NPA' }],
      correctId: 'b', explanation: 'แรงดันสูงเกินดันลมเข้ากระเพาะแทนปอด' },
    { id: 'aw-pt-a9', question: 'หลังใส่ advanced airway ระหว่าง CPR ควรช่วยหายใจผู้ใหญ่อัตราใด?',
      choices: [{ id: 'a', text: '30:2' }, { id: 'b', text: '1 ครั้งทุก 6 วินาที ต่อเนื่องไม่หยุดกดหน้าอก' }, { id: 'c', text: '1 ครั้งทุก 3 วินาที' }, { id: 'd', text: 'หยุดกดหน้าอกทุกครั้ง' }],
      correctId: 'b', explanation: '10 ครั้ง/นาที แบบต่อเนื่อง แยกจังหวะจากการกดหน้าอก' },
    { id: 'aw-pt-a10', question: 'วิธีที่เชื่อถือได้สุดในการยืนยันตำแหน่งท่อหลังใส่ advanced airway คือ?',
      choices: [{ id: 'a', text: 'ฟัง breath sound อย่างเดียว' }, { id: 'b', text: 'Waveform capnography' }, { id: 'c', text: 'ดูสีผิว' }, { id: 'd', text: 'วัดความดัน' }],
      correctId: 'b', explanation: 'Capnography เป็นมาตรฐานทองและต้องใช้ต่อเนื่อง' },
    { id: 'aw-pt-a11', question: 'EtCO₂ พุ่งขึ้นฉับพลันระหว่าง CPR มักบ่งบอกอะไร?',
      choices: [{ id: 'a', text: 'ท่อหลุด' }, { id: 'b', text: 'ROSC' }, { id: 'c', text: 'เครื่องเสีย' }, { id: 'd', text: 'ผู้ป่วยหยุดหายใจ' }],
      correctId: 'b', explanation: 'มักเป็นสัญญาณแรกของการกลับมาไหลเวียนเลือดเอง' },
    { id: 'aw-pt-a12', question: 'ข้อแตกต่างหลักระหว่าง SGA กับ ETT คืออะไร?',
      choices: [{ id: 'a', text: 'SGA ป้องกัน aspiration ดีกว่า' }, { id: 'b', text: 'ETT ต้องมองเห็น vocal cords และผู้ชำนาญเป็นผู้ใส่ ส่วน SGA ใส่เร็วกว่า' }, { id: 'c', text: 'เหมือนกันทุกประการ' }, { id: 'd', text: 'SGA ใช้เฉพาะเด็ก' }],
      correctId: 'b', explanation: 'SGA ใส่เร็วไม่ต้องมองกล่องเสียง ส่วน ETT ป้องกันทางเดินหายใจสมบูรณ์กว่าแต่ต้องผู้ชำนาญ' },
    { id: 'aw-pt-a13', question: 'ผู้ป่วยผู้ใหญ่สำลักที่ยังไอและพูดได้ ควรทำอย่างไร?',
      choices: [{ id: 'a', text: 'ทำ abdominal thrust ทันที' }, { id: 'b', text: 'ให้ไอต่อไปเอง เฝ้าสังเกตใกล้ชิด' }, { id: 'c', text: 'ตบหลังแรง ๆ' }, { id: 'd', text: 'เริ่ม CPR' }],
      correctId: 'b', explanation: 'อุดกั้นบางส่วนที่ยังไอได้ ให้ไอเองต่อไปก่อน' },
    { id: 'aw-pt-a14', question: 'ทำไมห้ามทำ abdominal thrust ในทารก?',
      choices: [{ id: 'a', text: 'ไม่ได้ผล' }, { id: 'b', text: 'เสี่ยงบาดเจ็บอวัยวะภายใน — ใช้ back blows + chest thrusts แทน' }, { id: 'c', text: 'ทารกไม่สำลัก' }, { id: 'd', text: 'ใช้เหมือนผู้ใหญ่' }],
      correctId: 'b', explanation: 'ใช้เทคนิคสลับตบหลัง-กดหน้าอก 5-5 ครั้งในทารก' },
    { id: 'aw-pt-a15', question: 'ผู้ป่วยหมดสติระหว่างทำ Heimlich ควรทำอย่างไรต่อ?',
      choices: [{ id: 'a', text: 'หยุดช่วยเหลือ' }, { id: 'b', text: 'ประคองลงพื้นแล้วเริ่ม CPR ทันที' }, { id: 'c', text: 'ทำ Heimlich ต่อจนสำเร็จ' }, { id: 'd', text: 'รอ EMS เฉย ๆ' }],
      correctId: 'b', explanation: 'การกดหน้าอกช่วยดันแรงดันไล่สิ่งแปลกปลอมได้เช่นกัน' },
  ],
};
